### ISSUE TITLE
powertagging your profile for location, topics, and gear

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#104]
- [x] basic profile tagging infrastructure
- [x] note what geographies you are associated with or interested in
- [x] note if you are an organizer, so that your @organizer.publiclab.org could be displayed publicly
- [x] geographic profile tagging infrastructure (#1416)
- [x] display of which activities you've done https://github.com/publiclab/plots2/issues/928

## User interfaces

- [ ] indicate interest in being contacted about particular topics or related to your expertise, possibly connected to the new Q & A feature of what you are subscribed to
- [x] prompts to add location on profile
- [ ] prompts to add other profile tags (roles, affinities, interests) on profile
- [ ] prompt for (on profile page) what equipment you have and are willing to show up with to a group field event 
- [ ] prompt for (on profile page) what equipment you have and are willing to loan out. 
- [x] prompt for adding self to a group (#1954)

**Comment by ebarry** [comment]
@steviepubliclab wrote in issue https://github.com/publiclab/plots2/issues/71 several other ideas: 

* highlight what role individuals play in chapters, such that in combination with specifying what chapter one is a part of, this role information could also be displayed on chapter pages
* similarly, chapter pages can also display tools held locally as specified by individuals on their profile pages

This combination of features would assist chapters to self-organize by establishing a clearer picture of what exists as well as a model to aim for. It would be good to compare notes with FarmHack community on the models they are setting up as they are dealing with some of the same issues about [who] is using [what tools] [where].

**Comment by jywarren** [comment]
organizer tagging as described in #215 could be made possible by this.

**Comment by ebarry** [comment]
@jywarren suggests: 
`skill:area`
`gear:balloon`
`gear:spectrometer`
`resources:type`
`willtravel:circumference`
`email:addy@addy`
`phone:555...`

Addendum: 
all projects - contact person
- active projects
- past projects
- possible projects / issues that need attention

Addendum 2:
local mailing list overlays

**Comment by ebarry** [comment]
Point of reference: our sister community FarmHack is getting requests for this same type of thing http://farmhack.org/forums/search-functionmap-people-and-others

**Comment by steviepubliclab** [comment]
Hoping the the profile powertagging system will allow us to more easily see connections between people, projects and places. Visual example below of connections that could be potentially be highlighted and more easily traced with a system like this:
![tagging](https://cloud.githubusercontent.com/assets/7490478/10766716/c4d4e8b4-7ca6-11e5-9454-85f8dd1ec73f.jpg)

**Comment by jywarren** [comment]
A visualizer like that would be an additional project, but for a basic
example of how to see connections that is definitely in-scope, see Github's
profiles: https://github.com/jywarren/

**Comment by steviepubliclab** [comment]
oh no - I didn't mean to build that in. I just meant that with power
tagging we'd more easily be able to draw those connections from profiles.
These are connections that right now you almost just need to know from
working on the projects or knowing the people. But through the power tags,
these relationships will be more visible online as well.

**Comment by jywarren** [comment]
Oh cool, thanks for the clarification!

**Comment by ananyo2012** [comment]
I think most of these are covered in the Rich Profiles Project by @lalithr95. Can this be closed now perhaps opening a new issue for the left out points.

**Comment by jywarren** [comment]
Yes, I think we need to articulate clear tasks for:

* designing an interface for entering topical interests or available gear
* implementing the design in the drawing at
https://github.com/publiclab/plots2/pull/650 in a template
* connecting the template to a location tag controller
* writing tests for above (maybe first)
* designing a display for above data (one of several possible displays)

**Comment by jywarren** [comment]
I've moved a number of these into more articulated pieces in #1070. But this could be further broken up with regard to the non-geographic profile tagging. But that's lower-priority than #1070, which is quite long already.

**Comment by jywarren** [comment]
Updated a few more completed items on this list. Ready to start doing prompts to add other things like equipment, affinities? This could be as simple as a button that says "Add a piece of equipment" and displays a list of possibilities (for first version), like `balloon-mapping-kit`.

**Comment by jywarren** [comment]
@ebarry @steviepubliclab for this one:

>  indicate interest in being contacted about particular topics or related to your expertise, possibly connected to the new Q & A feature of what you are subscribed to

Could we list what people have offered to answer questions about, on the profile, and if there aren't any, prompt them to add some?

**Comment by steviepubliclab** [comment]
Hi,
The tag there would give them an email if there was a question posted on
that topic right? If so, it seems like maybe it's just the same thing twice
and we could just find words that suit both these things.

-Stevie

**Comment by jywarren** [comment]
Oh, sorry, same thing as what? we don't currently show subscriptions on the profile page, so if we did that we could maybe hit two 🐦  with one stone? Would that be ok?

**Comment by gauravano** [comment]
Hey @jywarren @ebarry @steviepubliclab as most of the goals of the checklist are achieved, how about closing this one and opening separate issues for remaining checklist goals?

Thanks!

**Comment by steviepubliclab** [comment]
Wow this is an old thread.. sure whatever you think works best!

**Comment by gauravano** [comment]
Thanks @steviepubliclab! Opened new issue at https://github.com/publiclab/plots2/issues/5105 . Thanks!
