### ISSUE TITLE
Major geographic feature planning issue

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1070]
We've had a wide variety of geographic features planned, built, attempted... this is the issue to organize them all! This is from a planning session with @ebarry and @steviepubliclab. Ask if you'd like to be involved!

Things listed here can/should be broken out into their own issues, and added to the Geography milestone: https://github.com/publiclab/plots2/milestone/7

## Add location to profile

* [x] User interface design - done-ish? by @ebarry? #1035 -- in the gif on this one
* [x] Blank template at url https://publiclab.org/locations/form so we can test it out - claimed! - #1035 - completed in #1044
* [x] HTML markup of the location form - would go into template from #1035, but leave map as a grey square at the top, for now - broken out into #1107 and complete in #1120.
* [x] move actual input form into a partial template for use in location entry across the site (in #1131)
* [x] Leaflet map display - at top of #1035's blank template - use Leaflet as per examples to display a zoomable/draggable map in the form (above) -- build on this helper: #1094 - code example here: ` <%= render_map(@node.lat, @node.lon, @maps) %>` (in #1131)
* [x] Display a dot at the center of the map, that stays fixed at the center as you pan the map underneath/around it (see [example code for this here](http://stackoverflow.com/questions/30838938/in-leaflet-how-to-set-a-marker-to-a-fixed-position-on-map)) (fixed in #1149 by @mridulnagpal)
* [x] Get an integer lat/lon grid to show up on the map: https://www.npmjs.com/package/leaflet-virtual-grid (fixed in #1171 by @mridulnagpal)
* [x] Shade or highlight the grid square the center dot is inside of (done in #1202 by @mridulnagpal)
* [x] Placename autocompletion (break me up) like MapKnitter new map form, as done [in this interface](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/location_tags.js#L3-L9), which you can view at https://publiclab.org/profile/info/your_username 
* [ ] zoom/pan the map as you autocomplete a textual search for a place, to center on the new location
* [ ] make `gridSquareNWCorner()` method which returns upper-left bound of active grid square
* [ ] Get form to submit request with lat/lon bounds
* [ ] Make dragging the map trigger reverse geocoding (turning lat/lon into a textual place name) to populate a "location" text input [using this code](https://github.com/publiclab/plots2/blob/master/app/views/users/_tags_form.html.erb#L312-L338)
* [ ] offer to use the [geolocation API](https://github.com/publiclab/mapknitter/blob/master/app/views/maps/_geocoder.js.erb) to find where you are now
* [ ] Write controller action to receive the region box and add it to user profile
  * https://github.com/publiclab/plots2/blob/master/app/controllers/location_tags_controller.rb (already written, look into)
* add powertag: `region:lat-lon` - https://github.com/publiclab/plots2/blob/master/app/controllers/user_tags_controller.rb
* [ ] Redirected to your profile with message "Your location was saved"

## Profile display

* [ ] Design a display for a location on a profile page (like https://publiclab.org/profile/liz)
* Choose a single, random "example location" (Publiclandia) for someone to figure out how to display
* Hide this display behind a "geo" GET parameter like https://publiclab.org/profile/liz?geo=true
* Display grid as in above `leaflet-virtual-grid` issue and shade the appropriate 
* [ ] Display a small map to show on profile pages -- hidden behind get param (same as above) and show example location
* [ ] Connect small profile map to profile stored location

## Remove location from profile

* [ ] Controller action to do this -- 
* use user_tag_controller
* Message: Your location was removed.
* [ ] Interface on the profile -- button with "confirm"

## View people by region on a map

* [ ] Create a template at https://publiclab.org/people/map (for starters)
* [x] Get a zoomable Leaflet map to show up there, like https://publiclab.org/archive page
* [ ] Get a grid to show up on the map: https://www.npmjs.com/package/leaflet-virtual-grid
* [ ] Redirect to URL: https://publiclab.org/region/lat/lon when you click a region
* [ ] Publish the map at https://publiclab.org/people
* [ ] Create a JSON action listing regions (lat/lon) and headcount
* [ ] Shade the grid by # of ppls in that square based on JSON format from above

****

### Other projects to plan for:

* Think about how people and projects and questions and other things are listed in a common map
* Map view for tag page
* Location-based notifications
  * subscription to location notifications
  * subscriptions to additional region grid squares you're not in yourself
  * callouts to regions: `@location:lat,lon` -- "oh hai @region:42,-75 did you see this new permit that got filed for a sand frac mine?"
* adding location using above location input form, but to notes or wiki pages
* a map view for notes/wiki pages
* a generalizable/parametric partial template for location entry

**Comment by ebarry** [comment]
Quick reading shows that the convention might be to use the lower left coordinate pair lat,lng to indicate a grid square. Any other thoughts on this?

**Comment by jywarren** [comment]
sounds good - can you edit the issue to reflect this? THanks!

**Comment by jywarren** [comment]
Hi @mridulnagpal -- if you're interested in a new challenge, these two (from above) could become a new issue:

* move actual input form into a partial template for use in location entry across the site
* Leaflet map display - at top of #1035's blank template - use Leaflet as per examples to display a zoomable/draggable map in the form (above) -- build on this helper: #1094 - code example here: <%= render_map(@node.lat, @node.lon, @maps) %>

**Comment by mridulnagpal** [comment]
@jywarren Roger that :+1:

**Comment by mridulnagpal** [comment]
@jywarren How do I proceed?

**Comment by jywarren** [comment]
So, first if you could use the helper method in #1094 to display a map in the provided box, then change the template to a partial template. You can look up partial templates in the rails docs but it means you can include it in another template. Make sense? Thanks!!!

**Comment by mridulnagpal** [comment]
@jywarren What would be the arguments for the helper method?

**Comment by jywarren** [comment]
Let's just start with a random example location of your choice, and an
empty array of items.

**Comment by mridulnagpal** [comment]
@jywarren It gives an error because of the empty array of objects undefined method `each' for nil:NilClass

**Comment by jywarren** [comment]
Ah, but could you pass an empty array like `[]`?

**Comment by mridulnagpal** [comment]
Cool, I tried it and it worked but cannot see a map on the page yet.

**Comment by jywarren** [comment]
Hmm, perhaps you could look at the js console in the browser?

**Comment by mridulnagpal** [comment]
It says Map container not found

**Comment by jywarren** [comment]
Ah -- does the helper template in /app/views/map/map_helper contain the div
w id "map" that the helper is inserting the map into?

**Comment by mridulnagpal** [comment]
No its just the script tag in _leaflet no div tags

**Comment by jywarren** [comment]
Ah - it needs a `div` with the right ID -- check out how it's done in /views/sidebar/_related.html.erb, for reference. And perhaps we should move the div into the helper template, since it'll usually be needed? Or people may want to style it differently and we should keep it outside?

Let's also create a new issue for this sub-issue, so we don't clutter the comments up for this umbrella-issue, since we'll be using it for a while :-) sound good? Thanks, and apologies for the slower pace of input while I'm traveling for the next few days!

**Comment by mridulnagpal** [comment]
@jywarren I think #1130 is resolved in #1131. Please review.

**Comment by jywarren** [comment]
Yes -- thanks! If you'd like to tackle the next two here, they have to do with Leaflet JavaScript work.

**Comment by mridulnagpal** [comment]
@jywarren Yeah sure

**Comment by jywarren** [comment]
https://publiclab.org/locations/form

**Comment by jywarren** [comment]
This is really coming along, @mridulnagpal -- I checked them off up to "Shade or highlight the grid square the center dot is inside of"

Thanks!

**Comment by jywarren** [comment]
Great work, @mridulnagpal -- maybe this new next step?

> make `gridSquareNWCorner()` method which returns upper-left bound of active grid square

**Comment by mridulnagpal** [comment]
@jywarren delayFactor decides how much interval is there in rendering different cells, for example if delayFactor is high all the cells come after some interval one after the other, we can set it to 0 if we want alll the cells to render at the same time.

**Comment by jywarren** [comment]
Ah, interesting. Well, I think it's only shading on the initial draw, and
we need it to refresh the active cell as the map moves. Do you think that's
a next step you could attempt?

Thanks for your hard work!

**Comment by mridulnagpal** [comment]
@jywarren I have made another PR for it. It works fine now.

**Comment by mridulnagpal** [comment]
@jywarren how do we start on the next one?

**Comment by jywarren** [comment]
>  Placename autocompletion (break me up) like MapKnitter new map form, as done in this interface, which you can view at https://publiclab.org/profile/info/your_username

So I think we'll need to start using the Google Geocoding API, so look into the links from the above list, especially the form here:

https://github.com/publiclab/plots2/blob/master/app/views/users/_tags_form.html.erb#L101

You can try this search-location-by-text interface here: https://publiclab.org/profile/info/warren (but with your own username)

**Comment by mridulnagpal** [comment]
@jywarren Okay so I studied the code for the API but how do I implement it for this one?

**Comment by jywarren** [comment]
Hi, Mridul - why don't you try copying in the key portions of the form from the other document, and we'll see how it runs?

**Comment by mridulnagpal** [comment]
@jywarren What is our API_KEY for geocoding API?

**Comment by jywarren** [comment]
I think we can't share that out publicly, but you should be able to get your own. But now that I think about it, i'm not sure it's required anymore! Are you sure?

**Comment by mridulnagpal** [comment]
How do I import the autocomplete method if I can't import the object google? Is there any other way to Import google?

**Comment by jywarren** [comment]
Hi, Mridul, perhaps we should open a new issue for this, as we're making a very long comments thread on this more general issue. But i looked and apologies, it looks like the Google Maps API and key are shown here: https://github.com/publiclab/plots2/blob/master/app/views/users/info.html.erb#L8

**Comment by mridulnagpal** [comment]
@jywarren What's next?

**Comment by jywarren** [comment]
HI, @mridulnagpal - I notice that the update doesn't happen until you deselect the search form box, do you think you could make it happen upon selecting a place?

Next up will be a method to get the northwest corner of the current box, then working down the list above. I've been checking them off as we go! 

Thanks!

**Comment by jywarren** [comment]
OK, lots just moved over to: https://github.com/publiclab/leaflet-blurred-location/issues/1 -- this will continue, though `plots2`-side issues will remain here.

**Comment by jywarren** [comment]
OK, i'm now closing this and will open a new one for those `plots2`-side functions we'll need!

**Comment by jywarren** [comment]
Yep!
