### ISSUE TITLE
Planning issue for Wiki Discussion GSoC project

### ISSUE THREAD

**Issue by aspriya** [publiclab/plots2#1438]
### Why
Wiki pages are web pages that anyone can create or edit. PublicLab use them to collect information, documentation and instructions on projects. At present users can create wikis, edit them and associate tags with them. But users can not add comments to this, can not make suggestions, can not tag a user for a special part in the wiki. Wikis can made more interactive by implementing these features. For this I will use the publiclab/inline-markdown-editor.

### Phase 1

- [ ] Add a comment button aside of the pencil button (edit button)
- [ ] Building a inline form for commenting
- [ ] Wirte tests to check the functionlity of comment and building forms attributes.
- [ ] Add view suggestions and view Comments Buttons

### Phase 2

- [ ] Make a table to store comments for a perticuler wiki page
- [ ] Make the comment form submittable
- [ ] Write tests to check the Commenting functionality
- [ ] List suggestions when view suggestions button is clicked.
- [ ] create two functions to approve and discard suggestions by a valid user.
- [ ] Write tests to check the functionality of approval fucntion and discarding function.
- [ ] List comments when view Comments button is clicked.
- [ ] Create a function to remove comments by admin or moderators.
- [ ] Check the functionality of appearing of comments by tests.

Will keep updating this thread as and when things get clearer. Please feel free to provide feedback and suggestions.

**Comment by jywarren** [comment]
I'm thinking some rearranging could make sense so that we don't have to merge in a non-functional comment button before the commenting functionality is ready.

So, what's the first step in getting a commenting form to appear? Let's think through where we'd want to make the form ([template here](https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb)) appear.

Even before that, maybe we want to create a functional test of adding a comment to a wiki page. This could be a good project to break out and make a checklist out of. Comment controller is functionally tested here: https://github.com/publiclab/plots2/blob/master/test/functional/comment_controller_test.rb#L20-L30

Is there anything stopping us from making a comment attached to a wiki page instead of a note? Could we test that out in the comment controller functional test, as a first step? 

(The above is copied in [from here](https://github.com/publiclab/plots2/pull/1441#discussion_r119249749), but could be used to edit/revise the checklist above.) 

Also - thanks for posting this checklist, it looks great!!! Very helpful.

**Comment by jywarren** [comment]
Also see how ` Make a table to store comments for a perticuler wiki page` may already exist in the comment controller, since comments are attached to `nodes` and we may not have actually ever prevented them from being made on Wiki nodes, instead of just Note nodes?

**Comment by jywarren** [comment]
Let's break out the suggestions into its own phase -- that's a lot more complex than just comments, right?

Then let's have the first phase be backend Comments functionality, and the second be Commenting interface (that way the interface comes online only after the backend already works!). 

How does that sound? Thanks!!!

**Comment by aspriya** [comment]
Wow thanks for you feedback @jywarren. Yes phases in that way seems more logical and accurate. Will rearachge the above check list and will start writing tests as you mentioned. Thanks again.

**Comment by jywarren** [comment]
Good note from #1443 -- (https://github.com/publiclab/plots2/pull/1444#discussion_r119707141) excerpted here:

> I think adding regular comments to wiki pages, and making a comments tab to display them, is a good stepping stone on the way to inline comments. Then we can display all comments on the tab, with a later step of making an inline display of those comments that have reference to a specific section. (@aspriya, mayeb this is a really good step to add to your checklist!)

This also resolves one of the items in the checklist of using the same column for all comments. See how @ananyo2012 added an `aid` column to the comments table here: https://github.com/publiclab/plots2/blob/master/db/migrate/20160616035549_add_aid_to_comments.rb

You could do the same to add a reference to where the comment is supposed to be inserted. This migration could be its own step on the checklist. Would it be a string column containing the entire text of the subsection? And as a sub-checklist-item, would we need to change that reference each time the subsection text is edited, so we never loose track of where the comment is supposed to be inserted?

**Comment by jywarren** [comment]
I'd also like to suggest a 1.5 "mini phase" which could be:

* [ ] make a Question button which opens (in a new window) a form to post a question, using the `extraButtons` array 
  * plus a function which runs on the element (see documentation for inline-markdown-editor) to add an `href` to the button leading to `/questions/new?tags=____` with some related tags. 
  * We can insert the tags using `<%= @wiki.tagnames %>`, I think -- but let's try this one step at a time!

**Comment by jywarren** [comment]
If you can add the above "mini phase" in, that'd be great, also I'm adding some links to where relevant code can be found for some of the checklist above.

**Comment by jywarren** [comment]
Oh noooo! I was doing a big edit of the issue, adding links to relevant lines of code, but then lost it all when the page refreshed! Ughhhhh. Ok, will start over.

**Comment by aspriya** [comment]
Oh no! :face_with_head_bandage:

**Comment by jywarren** [comment]
learned my lesson yet again. I'm doing it in smaller chunks now and saving each time.

**Comment by jywarren** [comment]
Starting to think about documenting your plan not only for yourself and me, but for other people you could recruit to contribute, can you continue fleshing out links to relevant code and documentation in your checklist, trying to think about how it looks to a newcomer? For example, where you reference `extraButtons`, you might link to the corresponding docs in https://github.com/publiclab/inline-markdown-editor/

**Comment by jywarren** [comment]
OK! I finished rearranging a bit - even broke out a 2.5 section to separate basic commenting from inline commenting. This means you can tackle the project in smaller pieces and each phase leaves you with something working :-)

Make sense? If there are other places you can add links to code, please do, and perhaps help other students in GSoC organize their own projects a bit in this way!

**Comment by aspriya** [comment]
Sure, will do @jywarren , thanx a bunch!

**Comment by jywarren** [comment]
Marked 1.5 as done, great work! If #1453 is ready to merge, you're ready for Phase 2 :-)

**Comment by jywarren** [comment]
Also, i rearranged to put the test issue first in Phase 2, since it's also linked to the following item.

**Comment by jywarren** [comment]
Phase 2 will be fun since you'll be able to publish it to the live site pretty soon and ask people to try it out!

**Comment by jywarren** [comment]
Also added a bit on functional testing the email notifications for wiki comments :-)

**Comment by jywarren** [comment]
How are things going? I added another small request here: https://github.com/publiclab/inline-markdown-editor/issues/5 which will be a good intro to JavaScript testing too. 

Then let's start with phase 2!!! Exciting!

**Comment by jywarren** [comment]
Now that you have good familiarity with these different systems, i think phase 2 will go quite quickly. Just remember to submit separate PRs for each checklist item!

**Comment by ananyo2012** [comment]
@aspriya So we have come the Last Phase of GSoC and the most important part of your Project which includes Inline comments and suggestions feature. I have modified your timeline so that it comes in `Phase 3.1` and `Phase 3.2`. Think of how you can leverage the `inline-markdown-editor` to implement these features. Also there is an issue https://github.com/publiclab/plots2/issues/1554 where I have assigned you. Since this is a big work and may need many modifications I advice you to work in WIP PRs and regularly push your code so that we can quickly discuss all of these.

**Comment by aspriya** [comment]
Thanks @ananyo, Yes I'm currently studing the code base of
`inline-mardown-edito` for doing this phase. Once started will send a WIP
PR.

**Comment by ananyo2012** [comment]
Also have a look at https://github.com/publiclab/plots2/issues/1554 any try fixing it in the mean time.
