### ISSUE TITLE
Planning issue for Search integration

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1463]
* [x] #1466 -- done!

Start hooking up Solr Node.search to various things, one at a time:

1. Solr Typeahead? 
    * [ ] Add Node.search with toggle to: https://github.com/publiclab/plots2/blob/master/app/services/typeahead_service.rb#L56 (doing in #1537)
1. Start stripping back different search interfaces from: https://github.com/publiclab/plots2/blob/master/config/routes.rb#L143-L152
    * [x] Remove https://github.com/publiclab/plots2/blob/master/app/controllers/questions_search_controller.rb
    * [x] Remove almost all methods from https://github.com/publiclab/plots2/blob/master/app/controllers/searches_controller.rb#L69-L79 (keep dynamic for now)
    * [x] rewire normal search methods with search (form) and results methods/views
    * [x] rewire these to use SearchService - #1470
    * [ ] rewire SearchService to use Solr `Node.search`
        * [ ] Use fallbacks using toggle: https://github.com/publiclab/plots2/blob/master/lib/solr_toggle/solr_toggle.rb
    * [ ] Use UI from https://publiclab.org/search/dynamic/  (this uses JSON API)
1. Consolidate:
    * [x] Does https://github.com/publiclab/plots2/blob/master/app/models/search.rb relate to SearchService, or could it? -- attempting removal in #1469
    * [x] remove typeahead code from https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb#L64-L93
    * [ ] Functional test https://github.com/publiclab/plots2/blob/master/app/api/srch/search.rb and https://github.com/publiclab/plots2/blob/master/app/api/srch/typeahead.rb
    * [ ] Unit test https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb and https://github.com/publiclab/plots2/blob/master/app/services/typeahead_service.rb
    * [x] Get rid of: https://github.com/publiclab/plots2/blob/master/app/models/search_record.rb
1. search tags, profiles, comments? Add new search fields: 
    * [ ] Comments: https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L32
        * Add to `Node.search`:    `fields(:title, :body, :comments)`
    * [ ] Begin indexing tags: https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L32
        * `text :tags do / tags.map(&:name) / end`
        * and add: `fields(:title, :body, :tags)`
1. [ ] Expand `DISABLE_SOLR_CHECK` flag so we can diable READ, WRITE, or BOTH: https://github.com/publiclab/plots2/blob/master/lib/solr_toggle/solr_toggle.rb#L4

Question: when are node.tags and node.comments reindexed?

* We should test it to see, but if it's not automatic, we can add on Comment.on_save: https://github.com/sunspot/sunspot#reindexing-objects

**Comment by jywarren** [comment]
Initial done in #1464

**Comment by jywarren** [comment]
#1467 for one more
