### ISSUE TITLE
PLANNING ISSUE: Dashboard

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2103]
- [ ] https://github.com/publiclab/plots2/issues/2076 - Dashboard overwhelmed with just a few posts on a single topic
- [x] https://github.com/publiclab/plots2/issues/762 - Design stronger entry point for Questions system on dashboard
- [ ] https://github.com/publiclab/plots2/issues/837 - New "answers" to questions are not featured on dashboard activity feed
- [ ] https://github.com/publiclab/plots2/issues/288 - display comments from SpectralWorkbench.org and MapKnitter.org in dashboard comment feed
- [x] https://github.com/publiclab/plots2/issues/2101 - Discussion list tab in dashboard shows primarily site notifications
- [ ] https://github.com/publiclab/plots2/issues/2102 - Reduce "above the fold" space on dashboard given to the /Blog

**Comment by jywarren** [comment]
Closing in favor of new style guide based design! Thanks!
