### ISSUE TITLE
PLANNING: Email notifications and subscriptions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2104]
As we move our email-based communications off GoogleGroups and onto our website, our ability to subscribe to updates by topic and location becomes more important. Let's make a holistic design approach. 

Breaking out sub-projects:

## Periodic Email Digests

- [x] #2027 - Display a page of "activity from past day" in a list at /subscriptions/digest -- this will help show what people would be getting by subscribing (#2058)
- [ ] email templates for topic digests (needs breaking out into a new issue -- potentially #2091 !)
- [x] add whenever gem for easily writing and deploying cron jobs which will be used in case of email digest.
- [x] #1584 regularly scheduled email triggers with ActiveJob
- [x] https://github.com/publiclab/plots2/issues/1119 - another planning issue for Weekly/ Monthly email digest system, part of which is bring dealt with in the next issue: 
- [ ] Better organize the Digest page - #2378
    - [ ] Suggest a possible design for the email template (building on the digest page)
- [ ] ability to change timeframe of `/subscriptions/digest` to `weekly` or `monthly` like [Github Pulse](https://github.com/publiclab/plots2/pulse/weekly) has
- [x] Add a method in [Subscription mailer](https://github.com/publiclab/plots2/blob/master/app/mailers/subscription_mailer.rb) for sending digests
* [x] we made a `User.subscribed_content(period)` which collected all the nodes answers, and comments made in the specified period (solved in #2027)
* [x] write unit tests against `User.subscribed_content(period)`
- [x] add link and explanation from https://publiclab.org/subscriptions/ to https://publiclab.org/subscriptions/digest
- [x] Choose a queuing backend (http://edgeguides.rubyonrails.org/active_job_basics.html#backends)
- [x] Using resources like [this](https://www.krautcomputing.com/blog/2015/11/22/testing-async-actionmailer-jobs-with-activejob-in-minitest/), figure out if we can write a test for the email/activejob method

## Reply-by-email

- [x] Reply to comment by email - #2668
- [x] install mailman gem - #2669 
- [x] Designing Mailers and email templates for Email Digest
- [x] parsing incoming emails for correct comment text (see [GitHub design reference](https://blog.github.com/2011-03-10-reply-to-comments-from-email/)
- [x] Generating Node from email ( it would include processing the attachment like PDF's in case of a newsletter )

## Configurable subscriptions

Ability of users to configure when they get a digest email and what content it contains. 

- [x] Simple starting point: as email digests come online, let's strongly consider using a UserTag to "activate" them for people. So only people with a UserTag like `digest:weekly` or `digest:daily` will receive a digest. 
    - [x] later, advanced subscription settings -- `TagSelection`s, the primary means of subscribing, could have a `type` attribute -- like `type = immediate|weekly|daily` -- to provide more granular control over what you get in your digest
- [ ] https://github.com/publiclab/plots2/issues/70 - signup offers to auto-subscribe you to tags you were looking at
- [ ] https://github.com/publiclab/plots2/issues/880 - tag aliasas and subscription interaction
- [x] https://github.com/publiclab/plots2/issues/213 - configurable email notification preferences, or "what does subscribing to everything really mean?"
- [x] subscribing to authors: https://github.com/publiclab/plots2/issues/2088

## Design issues

- [x] simplify/consolidate "subscribe vs follow" and related UIs: https://github.com/publiclab/plots2/issues/2693

- [x] https://github.com/publiclab/plots2/issues/1960 - Move display of tags to more prominent location on content pages

### Additional related issues 

- [x] https://github.com/publiclab/plots2/issues/179 - we've gotten almost everything done on this giant issue except taking powertags out of the main tag list. Not sure why tag spam isn't a problem anymore, but it doesn't seem to be. 
- [ ] https://github.com/publiclab/plots2/issues/2097 - ghost tag (just a bug)

**Comment by jywarren** [comment]
Hi, @Gauravano -- does this work on replying to an answer, or to a comment on an answer? I found that perhaps it didn't -- can you give that a try? Thanks!!!

**Comment by Gauravano** [comment]
Okay, I will let you know soon.

**Comment by gauravano** [comment]
No, Email digests are not active. Thanks!

**Comment by oorjitchowdhary** [comment]
I think we have our email layout ready..
https://github.com/publiclab/plots2/blob/master/app/views/subscription_mailer/send_digest.html.erb

So do we need help regarding the backend code meaning the ruby code to send emails, organize the mail etc..??

**Comment by jywarren** [comment]
I believe we've completed almost all of this except for some template issues on the digests page, which is now it's own issue and part of GCI 2019. Closing, thanks!
