### ISSUE TITLE
Calculate "answered" rate for questions posted in a certain time period, by tag

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2120]
THIS ISSUE IS PARTIALLY COMPLETE THANKS TO @cesswairimu -- PLEASE READ ALL THE WAY THROUGH TO SEE WHAT IS REMAINING: 

### What problem could this idea solve?

How can we know how many questions posted on publiclab.org are answered? Related: over in https://github.com/publiclab/plots2/issues/2037 we're working on sorting the display of unanswered questions by recency of posting. **But what is our overall answer rate in a period?**

this snippet https://gist.github.com/jywarren/fd31cb03abfac4012362109b4cc47573 shows this calculation for the entire year 2017. 

### Next Steps

* We should display this number on /questions, perhaps with a dropdown menu to choose year, like 2017, 2016, 2015. I think this would be very motivating to people, to answer more questions and get our rate closer to 100%!
* **DONE!** We should also work in % answered rate to the time bounded stats pages, for instance it should appear here https://publiclab.org/stats/range/1-1-2017/31-12-2017/, and be updated for whatever date range is chosen in the URL
* We should also consider showing this on question pages by tag, for instance https://publiclab.org/questions/tag/water-quality - so that we can see for a given topic area what the rate of answered questions is. This will help us target our outreach efforts. 

> What did you expect to see that you didn't?

I just couldn't find what our "answer rate" was for a given time period. That's what i was looking for. 

### Please show us where to look

https://publiclab.org/stats/range/1-1-2017/31-12-2017/
https://publiclab.org/questions
https://publiclab.org/questions/tag/water-quality

**Comment by jywarren** [comment]
This sounds great -- it seems it could be broken into a few separate issues, one for each of the pages Liz points to. Thanks!

For the /questions pages, it could be for "all time" while on the "stats/range" page, we could use the `start` and `end` time periods from that page to set the range:

https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/stats/range.html.erb#L3

Thanks!

**Comment by ryzokuken** [comment]
This sounds like a nifty addition indeed, and I would love to add this feature to the codebase.

@jywarren @ebarry help me make a list of things to do/add?

**Comment by ryzokuken** [comment]
# TODO

- [ ] Display the stats on `/questions`
- [ ] Use a starting and ending datepicker
- [ ] Display the percentage on `/range` pages.
- [ ] Also display a percentage for a particular tag on the tag's tag page.

**Comment by jywarren** [comment]
Perhaps the gist could be made into a unit-tested feature of Node -- like,
`Node.answered(start, end)` , which defaults to no time bounds?

**Comment by ebarry** [comment]
Hi! Lost track of this for a minute, coming back to it now as it's one of the few very tangible ways to measure "exchanges"

It would also be a cool way to incentivize Answering!

IS there any more information i could provide on this to make it doable?
I would like to be able to say a sentence like "During 2017, X questions were posted, and Y% of them were answered within Z days"

**Comment by ebarry** [comment]
hi @publiclab/soc , could we bump up this issue for the Google Code In? It's nice and discreet.

**Comment by Souravirus** [comment]
Yeah sure @ebarry

**Comment by ebarry** [comment]
UPDATE: I just updated the initial issue as the second of three feature requests has been implemented!!! Now, the /stats page does have a date picker, and a bar graph that seems to show the ratio of asked questions to answered questions in that period. See https://publiclab.org/stats?start=01-08-2019&end=31-10-2019 and experiment with the dates either in the URL or from the date picker: 
<img width="831" alt="Screen Shot 2019-11-16 at 3 18 16 PM" src="https://user-images.githubusercontent.com/161439/68998756-69aef380-0884-11ea-8f38-04effff1cdca.png">

Based on this success, at the next time we rotate through this "metrics" functions on the website, let's look into the first and third idea above, which are: 
- adding the same stats bar to https://publiclab.org/questions
- adding a stats bar per topic (this will be important for research area reviews)

**Comment by cesswairimu** [comment]
Hey @ebarry, I created the issue for adding the status bar on  tag page #6790 ..I think it would be best if it goes to this the tag stats page https://publiclab.org/tag/community/stats. thoughts?. On the questions page I remember I implemented the logic some time back https://github.com/publiclab/plots2/pull/4256 but it wasn't published.. I think we opted to just have the bar on the '/stats' page or maybe @jywarren might remember the reason more clearly...Just checking to make sure we also need it on the questions page too. Thanks

**Comment by ebarry** [comment]
Wonderful that you planned for this information to go on the tag stats
page! Agree.
Yes, let's confirm with the forthcoming UI design for the questions page
and see if there may be a good spot for a progress bar.
Thank you Cess :D

**Comment by jywarren** [comment]
With #6790 are we done here? Great work everyone!

**Comment by cesswairimu** [comment]
I believe this feature has been live for a while now. Closing this
