### ISSUE TITLE
PLANNING ISSUE: Draft Feature 

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2667]
Hi @jywarren @steviepubliclab,

**I want to inform you guys that my exams are scheduled from 21st May to 6th June, so I wouldn't be able to do much in that time period. I would be available for task discussions/calls/messages. I will try to open and solve small issues in-between exams. So, I would try to do as much work as possible till 18th May and possibly we would be done with this issue till then.** 

Issue progress: #2307 contains checklist but some more points need to be added and discussed that's why I opened this issue. Most of Back-end for this feature is ready #2308. 

Remaining Tasks:

1. [x] Displaying Draft on author's, moderator and admin's dashboard (Solved in #2666 )
2. [x] Change in `_node_default.html.erb` and `_node_meta.html.erb` to distinguish draft from normal notes as we do for first-timer posts (Solved in #2747 )
3. [x] Addition of "draft" field in output data of PublicLab editor object (Solved in https://github.com/publiclab/PublicLab.Editor/pull/138 ) 
4. [x] Addition of checkbox and JavaScript function in `rich.html.erb` (Solved in #2747 )
5. [x] Addition of "Draft" label on `notes/show.html.erb`  (Solved in #2682 )
6. [x] Publish_draft method in the controller (Solved in #2747 ) 
7. [x] Addition of Publish button on `notes/show.html.erb`   (Solved in #2747 ) 
8. [x] Adding tests for publish method and the overall test of feature (In progress in #2747 )
9. [x] Writing wiki page about the draft feature
10. [x] An alert at the top of a draft page that offers a shareable link to the post for sending around
11. [x] Like, a secret URL token that allows access to the post even if someone doesn't have an account?

I have tried to divide the issue in minimum part as possible, I can solve 2,4,5,6 and 7 in a single PR or multiple, but I see that some parts can be good FTO candidates like 2,3,5 and 7. What do you guys think, should I open FTO's or not ? Thanks.

**Comment by jywarren** [comment]
I think ftos would be great and if any new community members are joining
our soc programs this summer and haven't had the experience of helping a
newcomer complete a PR this could be a great chance! @publiclab/reviewers
what do you think?

**Comment by Gauravano** [comment]
Ok, I will open FTO issues.

**Comment by Gauravano** [comment]
@jywarren which label class would be appropriate for Draft. We are using danger class for unpublished 
![unpub](https://user-images.githubusercontent.com/20878070/39389289-92941090-4aa4-11e8-8cca-3bb3962dbc2f.png)

**Comment by jywarren** [comment]
How about -success -- that'll be green, more friendly :-)

**Comment by Gauravano** [comment]
hi @namangupta01 , totally agreed. Let's open a new issue or move to channel for further discussion. Thanks !

**Comment by sagarpreet-chadha** [comment]
Hi @namangupta01 ,  @Gauravano  !
Should i create a new **Planning issue** for  Reply by Twitter feature  as well ? 
Thanks !

**Comment by Gauravano** [comment]
In our case, we all have same project ideas, so a Planning issue is important to sync with each other. Although, if you create Planning issue for your project, we may get chance to chime in so, good to create one.

**Comment by jywarren** [comment]
:-)))) great going, team!

**Comment by Gauravano** [comment]
hey @jywarren , I just published an article https://medium.com/@gauravano/https-medium-com-gauravano-gsoc-18-with-public-lab-46588104ad0d . Your comments and suggestions are welcome and should I post it on PL website ?

**Comment by jywarren** [comment]
Awesome - great to see this at PublicLab.org now too! https://publiclab.org/profile/gauravano

@publiclab/soc -- if anyone else is interested in writing updates like these, or anything about your work, it's very welcome on PublicLab.org -- thank you!!!!

**Comment by Gauravano** [comment]
@jywarren @steviepubliclab which design would be good for displaying draft on the dashboard. Also, please state if user view needs to be different that mod/admin or not. Like, we have for the moderated post.

Design 1: Similar to Moderated node with some text
![draft](https://user-images.githubusercontent.com/20878070/40139564-e460f23a-596d-11e8-970f-56720a9f3018.png)

Design 2: Label with node
![draft_label](https://user-images.githubusercontent.com/20878070/40139788-a74b78ec-596e-11e8-8715-21ea91910fb7.png)

Or any other ideas are welcome : )

**Comment by jywarren** [comment]
ooh, i like the green label. but could we put it preceding the title on the
same line?

This would only be visible to people who are working on a draft, right? or
to admins? What would set the "publish date" of the post?

**Comment by Gauravano** [comment]
How about this position ?
![position](https://user-images.githubusercontent.com/20878070/40144540-a20a01b0-597c-11e8-94ba-0da4251e5fd8.png)

Also, please comment on the opacity of the above draft listing.

yup, it would be visible to the author, moderator, and admin for now : )

**Comment by steviepubliclab** [comment]
Oh I also like the green for draft. I think the Publish button might need
to be a bit more prominent?

Best,
Stevie

**Comment by jywarren** [comment]
We can have a prominent "Publish Draft" button in the alert banner that
says "This is a draft" maybe?

**Comment by Gauravano** [comment]
okay, I'll post new design for "Publish draft" button in few hours. Thanks.

**Comment by Gauravano** [comment]
ok, I guess "green" is liked by all of us so just a final call in-between these two:

#### 1. With Opacity: 0.5 (Similar to Moderated)
 
![first_opt](https://user-images.githubusercontent.com/20878070/40168753-e879c8c8-59e1-11e8-81a3-bc7f48ba8357.png)

#### 2. With normal Opacity:
![sec_opt](https://user-images.githubusercontent.com/20878070/40168801-02f6df42-59e2-11e8-9bd7-ca34a878c1c2.png)

Which one for dashboard ? After this, I can open a FTO for this, if you guys say.

### For "Publish draft" -- 

We use design like this for moderated alerts at top: 
![this_2](https://user-images.githubusercontent.com/20878070/40168901-59ac08ee-59e2-11e8-8228-5e757ceeb5cb.png)

If we want to highlight the button, providing color is one way, which would look like this 
![design_here](https://user-images.githubusercontent.com/20878070/40169946-e0f19b46-59e4-11e8-9143-febd41e14ca0.png)

We can choose color for button from these 
![btn_style](https://user-images.githubusercontent.com/20878070/40169965-f13d5b34-59e4-11e8-979c-c8d385e759fe.png)

keeping in mind the label color, please provide your thoughts on this. Thanks.

**Comment by jywarren** [comment]
Hi Gaurav - I was wondering a couple things. First, does everyone get to
see drafts on the dashboard (meaning just title and photo)? Or did I read
that logic wrong. Maybe it should be just the author...

Second, we set a final url with the publish date in it. I wonder if we
should reset the url at the moment of final publication, and before then we
can use a temporary one, resetting this on publication? This is a little
complex but seems workable, no? There's a generate_path method to
recalculate the path with the current title and date. That way the title
could be changed as well and this would reflect in the final URL.

**Comment by jywarren** [comment]
Great that looks right! Sometimes conditional logic is tough to follow.
Great work!

**Comment by Gauravano** [comment]
Hey @jywarren please merge #2735 and #2666 in `unstable` whenever you are free. Thanks. And, what do you think about https://github.com/publiclab/plots2/issues/2667#issuecomment-389809487 ?

**Comment by jywarren** [comment]
Hi, @Gauravano -- you should be able to merge to `unstable` with `git push -f git@github.com:publiclab/plots2.git unstable` -- just drop in a note to the chatroom when you do so you're not colliding with others!

**Comment by jywarren** [comment]
I like the dimmed title version above -- and the green button on the alert! Thanks!!! 💪 🎉 😄

**Comment by Gauravano** [comment]
hi @jywarren I have pushed #2666 on `unstable` and wanted to check the status of https://unstable.publiclab.org/ before pushing further changes but the page shows 502. Could you help?

**Comment by jywarren** [comment]
Hi @icarito did you see this and could you chime in? Thanks!

**Comment by icarito** [comment]
Sure, I hadn't seen it. I'll have a look.

**Comment by icarito** [comment]
The issue is we haven't yet merged changes to the Makefile. I'll add one commit that has it.

Note the unstable build logs are here:
https://jenkins.laboratoriopublico.org/job/Plots-Unstable/lastFailedBuild/console

**Comment by icarito** [comment]
I've just pushed commit b0848a4484a17d0525d44e15395b03ac2e14abe8 on top of unstable and it' building now. We're transitioning our deployment procedure to an automated process handled by Makefile and managed in Git along with the repository. At the current time only Unstable is using Makefile but once we've merged https://github.com/publiclab/plots2/pull/2593 I can setup stable to use it too.

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab @ebarry @icartio , I am done with the initial implementation of Draft Feature. Here's the demo --- 
https://drive.google.com/file/d/1SA_pFA3BOKj9DMzuqqNERXH0gl5WWw9T/view?usp=sharing

I have done work in #2744 and will merge into `unstable` where we can further test it and build it further. Hopefully, `unstable` would be back soon @icarito is working in #2593 . Thanks @icarito.  

There is a decision to make whether we want to give this functionality to first-timers or not (keeping spam in mind). Currently, they can save as draft too. What do you think about it ? Thanks.

**Comment by Gauravano** [comment]
hi @jywarren @icarito there is error from my part while merging #2666 . Please check here https://github.com/publiclab/plots2/pull/2666#issuecomment-391979076 .Thanks.

**Comment by steviepubliclab** [comment]
Hi,
Interesting question about first timers on drafting. I'm split on it. Can
we say no, first time posters don't have a draft option for now, see how it
goes for a bit then add it later? Or do we need to decide now and set it in
stone?

Another couple questions on implications of this feature for co-publishing:
1) can you both edit the draft? I think that would be great. Also, what
would it look like to each person?
2) who has the ability to publish the draft? Anyone who's an author? I
think this makes sense for now.
3)  If we restrict the draft feature to those who have published before,
would it prevent those who are publishing with someone who's not a first
timer to have this feature on a piece they're working on together? I think
as long as there's someone on the post who's not a first time poster the
draft option should be available if we can work it that way.

Thanks for your work on this! I wasn't able to get the GIF to work, but I'm
sure it looks great. Is there another way to share it?

Best!
-Stevie

**Comment by Gauravano** [comment]
>Can
we say no, first time posters don't have a draft option for now, see how it
goes for a bit then add it later? Or do we need to decide now and set it in
stone?

We can change later, I will just hide this option for first-timers for now if you want.

>1) can you both edit the draft? I think that would be great. Also, what
would it look like to each person?

yes, the power of editing the draft would be there with the author, co-author, moderators, admins.


>2) who has the ability to publish the draft? Anyone who's an author? I
think this makes sense for now.

The power of publishing is there with the author, co-author, moderators, and admin. Should I change publishing power only to note creator i.e., author?


>3)  If we restrict the draft feature to those who have published before,
would it prevent those who are publishing with someone who's not a first
timer to have this feature on a piece they're working on together? I think
as long as there's someone on the post who's not a first-time poster the
draft option should be available if we can work it that way.

That's a nice one. For this, the user who is not a first-timer had to create a draft and after that, he/she can collaborate with anyone by just adding that user as co-author.

Currently, co-author can't see the draft on his dashboard but can access it by the link. I am working on it and would be ready by tomorrow, otherwise from a single-user point of view draft feature is ready and can be tested in few hours on https://unstable.publiclab.org/ . Any other question?

**Comment by Gauravano** [comment]
hi @jywarren @steviepubliclab Draft feature is working at http://unstable.publiclab.org . please try. Thanks.

**Comment by Gauravano** [comment]
hi @steviepubliclab @jywarren , here are some designs for starting: 

Design 1: 
![design1](https://user-images.githubusercontent.com/20878070/40680921-46556eee-63a5-11e8-9637-bc761f19a9bc.png)

Design 2:
![design2](https://user-images.githubusercontent.com/20878070/40681310-685849c0-63a6-11e8-8e9c-24ffeff1abbb.gif)

**Comment by jywarren** [comment]
These look pretty good! What if we made it the same font/color/size as `2
of 2 steps left` and added it there -- so `[ ] Save as draft | 2 of 2 steps
left [Publish]`

Then the red notice could be also right-aligned, the same font and size as
"Save as draft" (although still red?) and say "Others won't be able to see
this until you're ready - _Learn more_" with a link to a page we'll make at
/wiki/drafts

How does that sound? Thanks-- this looks amazing!!!

**Comment by Gauravano** [comment]
Like you asked for @jywarren  

![design3](https://user-images.githubusercontent.com/20878070/40744916-a60272d2-6473-11e8-8a9e-446d009a304e.gif)
Any more improvements?

**Comment by jywarren** [comment]
Amazing! Two small things. How does that look on a mobile display - should
we disable that feature for mobile or does it wrap nicely?

Second, perhaps the Publish button should change to Save when you check the
box?

Fantastic work!

**Comment by Gauravano** [comment]
>How does that look on a mobile display - should
we disable that feature for mobile or does it wrap nicely?

Looking messy on mobile view. You can try it on https://unstable.publiclab.org

>Second, perhaps the Publish button should change to Save when you check the
box?

Done 


![new_view](https://user-images.githubusercontent.com/20878070/40750614-7d415248-6485-11e8-97bf-19078d83dc63.gif)

**Comment by jywarren** [comment]
You can test yourself also by making the window narrower - maybe worth
hiding this feature with the "hidden-xs" class so it's not awkward on
smartphones? What do you think?

**Comment by Gauravano** [comment]
In GIF, I have also tried mobile view. How about trying media queries first ?

**Comment by jywarren** [comment]
Well, the Bootstrap hidden classes use those and are designed to be more
succinct, since they require only a few characters to implement. Give them
a try! Otherwise we'll have to write and maintain several lines of CSS,
which isn't too bad either.

**Comment by Gauravano** [comment]
@jywarren here's the mobile view 

![screenshot_20180601-050026](https://user-images.githubusercontent.com/20878070/40813577-341201c4-6559-11e8-88cb-1452ca87de29.png)

![screenshot_20180601-050031](https://user-images.githubusercontent.com/20878070/40813587-41cdd25c-6559-11e8-97cc-36b9070ee603.png)

**Comment by Gauravano** [comment]
hi @jywarren @steviepubliclab , here's the current notice text after draft is published. 

![note_after_publishing_draft](https://user-images.githubusercontent.com/20878070/40879317-aed7cfac-66bb-11e8-8567-7b014b0d02e6.png)

Please suggest the new one or changes if any. Also, @jywarren I have added the generate_method in PR. Thanks.

**Comment by jywarren** [comment]
This looks perfect. I think it's ready for merge if you agree?

**Comment by Gauravano** [comment]
Here are the draft related priviledges 

| User role | Draft Creation | Draft Editing | Draft publishing |
|-------------|--------------------|-------------------|-----------------------|
|New Comer | No | Yes, if co-author made by normal user | Yes, if co-author |
| Normal User | Yes | yes, if creator or co-author | Yes, if creator or co-author |
| Moderator and admin | yes | yes | yes | 

Any change required in this ?

**Comment by jywarren** [comment]
i think that looks good!

**Comment by Gauravano** [comment]
Awesome so the feature is complete. Let me throw some final tests and then we could merge it. Thanks.

**Comment by jywarren** [comment]
Amazing! Maybe this could use a little documentation on a wiki page using
your table above, and I wonder if the contributor looking to do technical
writing would be interested?

**Comment by Gauravano** [comment]
Actually, I was also thinking of the same, also we could maintain a new doc (or existing) to store the different status values i.e., for nodes, comments, users, etc. How about this?

**Comment by jywarren** [comment]
That's a really good idea!!!!

**Comment by Gauravano** [comment]
hi @jywarren , there are some things which hadn't been considered about the feature
1. Changes in API for hiding draft -- how about we check API in separate PR?
2. Currently, the user would be able to access his/her draft only through dashboard just like moderated notes. 
3. Although, I have checked all suspicious areas where the draft can appear on our website, but can't find one. So, only eligible users would be able to see. After merging this, I guess we can be attentive if we see any draft content publically.
4. This `set_sidebar` method is giving me some pain as I am unable to get control on these lines https://github.com/publiclab/plots2/blob/master/app/controllers/application_controller.rb#L38-L57 after trying many routes, I guess some API may be using this.
5. Do you know any area where `index` method is in use  https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L5-L8  ? 

Thanks

**Comment by Gauravano** [comment]
Update: `index` method was used in old tests and show the recent, popular, etc. -- This one is resolved.

**Comment by Gauravano** [comment]
As basic implementation of `Draft feature` is done, should I begin with the next stage which would be sharing secret URL with non-PL users or I can implement Subscription part of #2104 , and @ViditChitkara and I can merge our work after that? Thanks.

**Comment by jywarren** [comment]
That sounds wonderful!

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab  , I am starting on Subscription settings part, some points to discuss:
1. How about making a settings page where we would have different sub-sections?
2. Do you guys like this design:

https://user-images.githubusercontent.com/20878070/37797928-44caff74-2e41-11e8-925b-36e91080c3b0.gif

Also, @jywarren could you please approve my post https://stable.publiclab.org/notes/Gaurav/06-05-2018/first-note at https://stable.publiclab.org 
Thanks!

**Comment by jywarren** [comment]
I love the design and I just approved your post! Super work, Gaurav!

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab , I have my last exam on 13th as I notified [here](https://github.com/publiclab/plots2/issues/2764#issuecomment-395860635) . After that I will start working on this. Thanks.

**Comment by jywarren** [comment]
Super, good luck!!

**Comment by Gauravano** [comment]
Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab I have created the wiki page about the Draft feature at https://publiclab.org/wiki/draft-feature , please edit it or tell if you think any modifications are required. Thanks.

**Comment by Gauravano** [comment]
Hi, @jywarren @steviepubliclab #2796 would take some time to merge as it depends on Vidit's PR.In the meantime, I would like to give this one a final push. 

Here's the plan, we want to give a secret URL to people for having their review. For this, we need to store a token somewhere which would make Secret URL effective. Now, instead of storing URL for each note in the database, we can generate `user_tag` containing token. That token would be deleted at the time of publishing draft. how does it sound?

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab , I have a raised a PR for part of Draft feature ie., sharing secret URL. Here's demo : https://drive.google.com/file/d/1lxhz-v2WhPwBR9GMut83SrOAwPxdH-mX/view?usp=sharing

Also, I have pushed on `unstable` , you can try there too.

Here's some queries regarding design:
1. Where the "Generate secret URL" should be placed and how should it look?
Current view: 

![screen1](https://user-images.githubusercontent.com/20878070/41502694-bd048ffc-71dd-11e8-9581-9d0aa4ba5839.png)

2. The URL is shared via a alert for now - is it appropriate?
Current view: 

![screen2](https://user-images.githubusercontent.com/20878070/41502701-ee7abab6-71dd-11e8-85a4-c270cd5f3d5d.png)

Thanks.

**Comment by jywarren** [comment]
Wow this is very cool. I'd say, let's display the prompt to share within
the Draft Note alert at top, with a button that says "Share a secret link".
And i like your using an `alert()` but we can do one better -- a
`prompt('This link will give recipients access to ','link')` -- what do you
think?

What about using a normal node tag, since the URL will not be visible
anyways... i guess the node tag may appear in some listings, so it's not as
secure. But user tags also will be publicly visible...

Could we hide this particular user tag? It seems a little bit delicate for
maintainability, to use user tags in such a unique way. But you're right, I
can't think of another easy way.

Wait -- what if we added a unique hash to the end of the draft URL path,
since that's not public, and since we'll overwrite it on publication?

And then the notice of "Draft Note" could explain that "the temporary URL
of this post can be shared to give others access to read it. Click here to
add a co-author"... what do you think?

Thanks for thinking this through!!

**Comment by Gauravano** [comment]
Hi @jywarren, i will use prompt, thanks for pointing!

>Wait -- what if we added a unique hash to the end of the draft URL path,
since that's not public, and since we'll overwrite it on publication?

Just to be sure we are on the same page - I am storing a unique token in a power tag as you can see and then secret URL is generated by appending that token to the end of normal URL, as you said, at time of publishing, the URL is changed. Do you mean something like hash function?

**Comment by jywarren** [comment]
The only issue is that any tag is readable to the public, even if it's not super obvious. like they're listed alphabetically on /tags, for example. So since:

* the `node.slug` field is only viewable to admins and authors/coauthors when it's a draft, AND
* we change it anyways once published

we could use that to append an alphanumeric hash to the end like `slug-of-node-abcdefg` which is relatively secret (not shown anywhere publicly). Make sense?

**Comment by jywarren** [comment]
Aha, for example, in unstable, i saw:

![screen shot 2018-06-21 at 1 09 05 pm](https://user-images.githubusercontent.com/24359/41737225-a4f050ea-755c-11e8-8c41-07db248e03c9.png)

Hard to predict where it might pop up! Maybe best to not use a tag.

**Comment by Gauravano** [comment]
Yes, you are right @jywarren. I will update my PR. Thanks.

**Comment by Gauravano** [comment]
Hey @jywarren , I updated my PR with slug to save the secret token and also changed alert to prompt. Please review it. Thanks! 

Also, please comment about the "Generate secret URL" button and prompt text. Thanks again!

![prompt_using_slug](https://user-images.githubusercontent.com/20878070/41811787-f848e0c6-7733-11e8-89a4-9d6da72d8079.png)

**Comment by jywarren** [comment]
Let's name the button "share private link" and put it in the alert?

**Comment by jywarren** [comment]
And "with which" instead of "using which" -- and then this looks good!

**Comment by Gauravano** [comment]
@jywarren putting button in an alert?

**Comment by Gauravano** [comment]
Do you mean notice?

**Comment by Gauravano** [comment]
Here's the updated view

![pic_draft](https://user-images.githubusercontent.com/20878070/41813038-8502ef7c-774b-11e8-9785-4d7c8a8b4820.png)

**Comment by jywarren** [comment]
Oops, yeah - you got it. Maybe just "This is a draft note. Once you're
ready, click [Publish] to make it public. You can share it with
collaborators [using this private link]" ?

Exciting!!

**Comment by Gauravano** [comment]
@jywarren we can also generate the sharable link at the time of draft creation and then can show it in notice as you mentioned, instead of "Generate link" button in notice. What do you think?

**Comment by Gauravano** [comment]
Also, I have opened an issue at #2920 regarding the display of Drafts, I would like to have your thoughts there @jywarren @steviepubliclab .Thanks!

**Comment by jywarren** [comment]
That sounds good - one step simpler?

**Comment by Gauravano** [comment]
Any other change @jywarren ? Thanks.

![draft_notice](https://user-images.githubusercontent.com/20878070/42124164-96b63906-7c7b-11e8-96f3-1c0e3cb80a50.png)

**Comment by jywarren** [comment]
Looks fantastic!!!

**Comment by jywarren** [comment]
Let's do it!

**Comment by jywarren** [comment]
Ping me when you're ready to merge it! Great work!

**Comment by Gauravano** [comment]
It's ready @jywarren! :smiley:
