### ISSUE TITLE
Refactor Search API

### ISSUE THREAD

**Issue by stefannibrasil** [publiclab/plots2#3070]
- [x] Remove API Search endpoints duplication (#3045) 
- [x] Remove API Typeahead endpoints duplication (#3107)
- [x] Unify models scopes from Search and Typeahead services (#3108)
