### ISSUE TITLE
Compile checklist of PR review steps and more clearly share responsibility for readying PRs

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3563]
Looking to help check off pull request review steps and get the workflow more clear so we don't get backlogged and more people can help!

@publiclab/reviewers what are our steps?

* [ ] link to original issue
* [ ] description in title
* [ ] reviewed/approved by at least one reviewer
* [ ] screenshot if applicable
* [ ] passes tests

What else?
* [ ] label as `ready`

**Comment by SidharthBansal** [comment]
Please check modularity also.

**Comment by jywarren** [comment]
Yes, so:

* [ ] PR is (ideally) less than 50 lines of code & generally tries to implement only a single feature or fix
* [ ] PR doesn't affect highly sensitive areas of the site such as header or top of dashboard or signup form without input from `@publiclab/community-reps`
* [ ] Gemfile.lock, yarn.lock, and other unrelated files are not included (message below)

> Hi, this is looking great, but would you mind removing the Gemfile.lock from your PR, as I think it's just a version tweak? https://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git

How about these couple extra as well? Thanks!!!

**Comment by tech4GT** [comment]
@jywarren Awesome!! Lot's of nice things in this list!! How about these
- [] Issue should be claimed before opening the pull request
- [] Double check if it contains any feature that will be difficult to roll back(Possibly ask for review from other reviewers as well)

**Comment by gauravano** [comment]
We also have this step in summer:
* [ ] label as `review-me` if review required from another reviewer

**Comment by jywarren** [comment]
We could start requiring 2 reviews, potentially -- and/or we could mark
some people as reviewers who have deeper experience with the site and
getting at least one review from this group... what are your thoughts?

Thanks, all!

**Comment by tech4GT** [comment]
@jywarren I think we should have a project specific team, since not everyone on plots is familiar with Image sequencer and vice versa, apart from the standard reviewers team let's have specific project specific teams with deeper experience with that project, like `plots-experts` and `IS-experts`

**Comment by SidharthBansal** [comment]
Instead of tagging we can direct Image sequencer to your review only. Leaflet to sagar's review only. Because no one else I assume have knowledge of those projects. After your review jeff can re- review them and merge them. 
What you say?

**Comment by tech4GT** [comment]
@SidharthBansal I think making an experts team still makes sense since in future we may have others who could also get added to that, also there is @ccpandhare who knows the project inside out, and since @jywarren is the only one merging prs anyway, he can review them then. Thanks!

**Comment by SidharthBansal** [comment]
Actually I have not thought about future. I am really sorry I forget to
think about future. Yeah your idea is better. I completely agree with you.
Thanks

**Comment by jywarren** [comment]
❤️ this convo. Could we think of a name a little less exclusive sounding than `experts`? I guess that is what the name `reviewers` is for, in part. Something else?

**Comment by jywarren** [comment]
Does everyone know how to use saved replies? It's really helpful to keep a consistent nice tone and provide common links. Sidharth maybe "install saved replies" is itself a task we could make?

**Comment by SidharthBansal** [comment]
We should just inform this to mentors, there is no need of creating an
issue. This depends on individuals, not on community.

If we may create an issue then there are potential chances that students
will get confused.

**Comment by SidharthBansal** [comment]
Hi @jywarren we currently have most of the active members in @publiclab/mentors instead of @publiclab/reviewers. So it would be better to ask from @publiclab/mentors by tagging them. Also, this will be easy for students who are very new to open source.

**Comment by SidharthBansal** [comment]
We should not use @publiclab/reviewers any more I think so.
We should always use @publiclab/mentors

**Comment by tech4GT** [comment]
@jywarren how about `image-sequencer-specialists` ??

**Comment by SidharthBansal** [comment]
@jywarren can we mark it as gci issue so that gci students can review each other commits and we will have a self-sustained system at Public labs

**Comment by SidharthBansal** [comment]
This could be multiple instance count (probably infinity) gci issue. If you agree please add ``gci candidate`` label.
Thanks

**Comment by jywarren** [comment]
What about "plots-guides"?


Sidharth, this issue? Maybe we should tidy it up a bit? But I like the idea!!!

**Comment by SidharthBansal** [comment]
>>What about "plots-guides"?

@ jywarren Sorry I can't understand what you are referring to.
Yeah, there is a need of making a documentation for this issue.

**Comment by jywarren** [comment]
Oops, sorry - catching up -- i meant like a group called `@publiclab/plots-guides` and `@publiclab/image-sequencer-guides` maybe for people who can guide each project as @tech4GT suggested, and review PRs for each project. So for each pull request we'd mention this group to get a review.

**Comment by tech4GT** [comment]
Yeah that sounds good to me!

**Comment by SidharthBansal** [comment]
Hi @jywarren can we add this issue to gci candidate issue?
This way we will have a self sustainable system at pl. Even though we would be busy in some work, students will make issues, solve issues, review PRS. You just need to merge it up. This will save a lot of mentors time too.

**Comment by sk9331657** [comment]
@SidharthBansal @jywarren We can assign each project to the different group of mentors for reviewing. This way mentors can concentrate on reviewing particular projects PR much better.

**Comment by SidharthBansal** [comment]
All mentors can review PRS throughout all the repositories of public lab
 We have many new mentors who don't know about more than a single repo. Also, it depends on interest of the person, we can't divide people. People have different interests.

**Comment by aSquare14** [comment]
Yes ! I agree with both of you.

**Comment by tech4GT** [comment]
@sidharthbansal where are we with the teams, did we do it?

**Comment by SidharthBansal** [comment]
Jeff is out of US. Mentorship form is closed. Applications will be reviewed by 21 october. After he returns US.

**Comment by tech4GT** [comment]
Oh I meant the `guides` teams.

**Comment by jywarren** [comment]
OK! I created @publiclab/leaflet-environmental-layers-guides and @publiclab/image-sequencer-guides -- let's see how this works and we can expand to more repositories if we find it's useful. Thanks!

**Comment by jywarren** [comment]
In general, we can make "sub-teams" for different purposes for different repositories. But I'm cautious. We don't want to fragment our community too much, as @SidharthBansal points out. I think we should do our best to have a consistent unified community where people can move easily between projects. So, this is kind of an experiment and we can re-assess how well it works.

**Comment by jywarren** [comment]
@tech4GT  says: 

> Okay so I am thinking that only the plots-guides and image-sequencer-guides should approve pull requests. This will save us a lot of confusion and prevent incomplete PRS from getting merged.

This sounds reasonable. Can we restrict the specific right to "approve" to a certain team? I haven't seen that exactly. @tech4GT you are an admin in `image-sequencer`, can you check if this is possible? If so, we could discuss if we want to do this for a bigger project like `plots2`. Thanks!

**Comment by tech4GT** [comment]
@jywarren I'll check this out!
