### ISSUE TITLE
Wiki page locking

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#397]
## Overview

For extremely cautious use, for around 10 or so "most visible" pages on the site and/or those related to the staff only (board, for example), we need some locking abilities. Pages like:

- https://publiclab.org/wiki/board (has been hit a lot)
- https://publiclab.org/about
- https://publiclab.org/getting-started

Admins (`user.role == "admin"`) would have ability to lock, and moderators to edit locked pages. We'd show a clear message indicating that it's locked and why, and a way to appeal this, probably by linking to now-draft https://publiclab.org/wiki/moderation. in an alert. 

**Update:** as of #1095, tag creation permissions are done and we now just have to disallow the `edit` and `update` actions on https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb -- See **Tasks**, below.

Goal is to keep locking to an absolute minimum -- only for the most trafficked and spam-hit pages. Wiki page edit notifications for anything else. (#396)

****

## Tasks

1. [x] Maybe display a lock icon, with Bootstrap tooltip explanation, where Edit button is. (#1099)
2. [x] Also, link to a listing of all locked pages, at `/tag/locked`, from an explanation page at https://publiclab.org/wiki/locked (that'll be done in #1099)
3. [x] And an entry in the power tags page to go to `/wiki/locked`: https://publiclab.org/wiki/power-tags
4. [x] Intercept requests to the `edit` page. Look to see if the "locked" tag exists, and if it does, redirects back to the wiki page with an error message, by adding just after this line: https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L74 as follows  (complete in #1114):

```ruby
if @node.has_power_tag('locked') && (current_user.role != "admin" && current_user.role != "moderator")
  flash.now[:warning] = "This page is <a href='/wiki/power-tags#Locking'>locked</a>, and only <a href='/wiki/moderators'>moderators</a> can edit it."
  redirect_to @node.path
end
```

5) [x] (closed in #1155) We'd want to add the same kind of catch to `def update` in the same controller (for when you click `save` on a wiki page), except that we'd want to put all of these lines in an `else` block, so they don't get run if there's a lock:

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L137-L173

* [x] (closed in #1155) Add the tag `locked` to a page in a test, and make sure a normal user can't edit that page. A test of a wiki page (example: https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L124-L133) looks like this: 

```ruby
  test "basic user blocked from updating a locked wiki page" do
    node(:organizers).add_tag('locked', rusers(:admin)) # lock the page with a tag

    # then try updating it
    post :update,
         id:  node(:organizers).id, 
         uid:   rusers(:bob).id, 
         title: ""

    assert_template "wiki/show"
    assert_select ".alert", "expected message"
  end
```

* [x] follow the steps in the last task to add a test for the "edit" action (in #1114)
* [ ] test that admins can indeed access both of the pages above

This issue needs breaking up!

**Comment by jywarren** [comment]
@ebarry  - input on list of pages to lock?

**Comment by 500swapnil** [comment]
I would need your help with this. How do I begin?

**Comment by jywarren** [comment]
Basically as mentioned above, we need to add a conditional (if) check just after two lines in the wiki controller --

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L74

and

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L136

These will intercept requests to the `edit` page or the results of that page (when you click save on a wiki page) and it tries to `update` that page. 

Both interceptions will look to see if the "locked" tag exists, and if it does, redirects back to the wiki page with an error message. 

So, one first step might be to add the tag `locked` to a page in a test. A test of a wiki page looks like this:

https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L124-L133

```ruby
  test "updating wiki with bad title" do

    post :update, 
         id:  node(:organizers).id, 
         uid:   rusers(:bob).id, 
         title: ""

    assert_template "wiki/edit"
    assert_select ".alert"
  end
```

And yours could add the additional line to add the "locked" tag:

```ruby
node(:organizers).add_tag('locked', rusers(:admin))
```

Now, because you're logged in as test user "bob"  [on this line](https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L23), you should get redirected and we should be able to tell that it didn't work. 

Let's start there -- if you open a PR with this test, i can guide you on the next steps.

**Comment by 500swapnil** [comment]
Okay so what should I do first?

**Comment by jywarren** [comment]
Try making a test to ensure a non-admin cannot edit a locked page. Then you
should see the PR travis checks fail, and then you can try to implement
that feature in the controller action `update` -- make sense?

**Comment by 500swapnil** [comment]
Okay so this test will do I guess  
test "basic user blocked from updating a locked wiki page" do
    node(:organizers).add_tag('locked', rusers(:admin)) # lock the page with a tag

    # then try updating it
    post :update,
         id:  node(:organizers).id, 
         uid:   rusers(:bob).id, 
         title: ""

    assert_template "wiki/show"
    assert_select ".alert", "expected message"
  end

**Comment by jywarren** [comment]
Yes, I believe that's right -- you might also use an `assert_redirected_to`
-- and this should correctly test this because the default user in the
wiki_controller_test.rb is "bob" -- a regular user.

**Comment by 500swapnil** [comment]
Okay I have opened a PR #1114

**Comment by jywarren** [comment]
#1114 merged -- now just need the same but for the wiki `update` action!

**Comment by 500swapnil** [comment]
I have added a PR #1155 for update action. Please have a look!

**Comment by jywarren** [comment]
I'm going to reopen and suggest one more addition -- a test that admins do not get redirected, but can indeed both `edit` and `update` locked wiki pages. @500swapnil - any interest in this last one? It'd just be two tests. 

Thanks!!!

**Comment by jywarren** [comment]
Also, i'd like to request that this line be modified to link to the `/wiki/edit/pagetitle` rather than the `/wiki/locked` URL if the current user is an "admin" or "moderator":

https://github.com/publiclab/plots2/blob/master/app/views/wiki/show.html.erb#L45

That way it's easier for admins and mods to actually make edits!

**Comment by 500swapnil** [comment]
@jywarren Yeah I can add. But where should I add the test?

**Comment by jywarren** [comment]
You could put it alongside the ones that test disallowing normal users'
edits. Thanks!

**Comment by 500swapnil** [comment]
I made a PR #1163. Please have a look.
