### ISSUE TITLE
Identify unique pages across website where user needs to authenticate

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4132]
We are creating modal for the login/signup process. We need to integrate it throughout the website to all the pages wherever login/signup is needed to use that area. Examples
* [x] I have done the activity column #4161
* [x] https://publiclab.org/w/power-tags#Inline+power+tags #4155
* [x] write a research note
         link- https://publiclab.org/post
        `plots2/app/views/sidebar/_related.html.erb` #4151
* [x] follow a post
        link - https://publiclab.org/notes/joyofsoy/11-09-2018/fighting-the-flood-community-activism-and-education-in-pensacola
        `app/views/users/_follow.html.erb` #4152
* [x] like a research note
       link - https://publiclab.org/notes/joyofsoy/11-09-2018/fighting-the-flood-community-activism-and-education-in-pensacola
       `app/views/like/_like.html.erb` #4153
* [x] like a wiki page #4154
- [x] **Comments page on notes**
[publiclab.org/notes/](url)
`app/views/notes/_comments.html.erb`

![screenshot 54](https://user-images.githubusercontent.com/39333058/49604710-a572e500-f9b4-11e8-9d97-4f4d0e5fba4b.png) #4156

- [x] **Answers page on /questions** 
[publiclab.org/questions/](url)
`app/views/questions/_answers.html.erb`

![screenshot 55](https://user-images.githubusercontent.com/39333058/49604855-01d60480-f9b5-11e8-9137-f206a66cb77e.png) #4157

- [x] **Compose new answer on Answers on /questions**
[publiclab.org/questions/](url)
`app/views/questions/_answer.html.erb` #4158

- [x] **Questions page** #4159
[publiclab.org/questions/](url)
`app/views/questions/show.html.erb`

![image](https://user-images.githubusercontent.com/20972099/49638506-5a95b380-fa2e-11e8-814a-7744bf192fdd.png)

- [x] **Subscribe/Follow Tags** #4160
[publiclab.org/tags/](url)
`app/views/tag/index.html.erb`

![screenshot 56](https://user-images.githubusercontent.com/39333058/49605767-6db96c80-f9b7-11e8-9ad2-643fb3b10ff3.png)
* [x] dashboard ask a question #4169
* [x] Sidebar on wiki pages
![image](https://user-images.githubusercontent.com/20972099/49637518-94b18600-fa2b-11e8-8562-fca584e5dfa7.png) #4165
* [x] header of the website #4162 
* [x] Link Login Modal to Join Now on dashboard #4170
* [x] Try out the activity on the sidebar #4171
![image](https://user-images.githubusercontent.com/20972099/49638999-d3493f80-fa2f-11e8-9c5c-206843c2b4c6.png)

- [x] https://github.com/publiclab/plots2/issues/4231 Help answer future questions on wiki page
- [x] https://github.com/publiclab/plots2/issues/4230 Ask a Question on wiki page
- [x]  https://github.com/publiclab/plots2/issues/4229 Request an activity on wiki page
- [x] https://github.com/publiclab/plots2/issues/4241 Empty Notes Grids on wiki page
Folks are requested to tell other possible missing places so that they can be worked upon. @ebarry @jywarren @publiclab/reviewers @publiclab/mentors

**Comment by SidharthBansal** [comment]
NO PR REQUIRED.
Just tell me some places where we need login modal to be displayed on clicking the login/sign up.
Example we should have login modal on the question page. You know that OAuth modal is worked upon in other prs. So this issue's implementation will be after that issues completion. I hope this makes sense.

**Comment by oorjitchowdhary** [comment]
Okay.. that seems good.. I'll then claim this one on gci in a while

**Comment by mohitRJranjan** [comment]
* [ ] write a research note
* [ ] follow a post
* [ ] like a post

**Comment by oorjitchowdhary** [comment]
@SidharthBansal 
* ask a question
* comment
* I have done activity column
* Get Involved tab => Post your work
* Like, follow, Flag as spam, Emoji on posts, comments and wikis
* Tag click => Follow => Login/Sign up

**Comment by SidharthBansal** [comment]
@mohitRJranjan @oorjitchowdhary please don't write same points. Also, supply the route for it.
Thanks

**Comment by oorjitchowdhary** [comment]
okay

**Comment by SidharthBansal** [comment]
@oorjitchowdhary please organise in the form of checkboxes. Append the above changes also. 
Thanks

**Comment by oorjitchowdhary** [comment]
- [ ] Get Involved Tab -> Post your work
`app/views/layouts/_header.html.erb`
- [ ] Like, follow, Flag as Spam, Emoji on comments and wikis
`app/views/notes/_comment.html.erb`
`app/views/questions/_answers.html.erb`
`app/views/questions/_answer.html.erb`
`app/views/wiki/_header.html.erb`

**Comment by oorjitchowdhary** [comment]
This works? @SidharthBansal

**Comment by SidharthBansal** [comment]
> Like, follow, Flag as Spam, Emoji on comments and wikis
app/views/notes/_comment.html.erb
app/views/questions/_answers.html.erb
app/views/questions/_answer.html.erb
app/views/wiki/_header.html.erb

break this properly into different checkboxes and write sequence of flow for modal to get integrated.
Also append https://github.com/publiclab/plots2/issues/4132#issue-387916183 checkboxes with description.
Thanks

**Comment by JonathanXu1** [comment]
@mohitRJranjan @oorjitchowdhary have you guys claimed this task? I see it's still available on the dashboard.

**Comment by SidharthBansal** [comment]
@JonathanXu1 it is multiple instance count task. They have done the task. If you wish to do it you can claim and suggest me. Thanks

**Comment by SidharthBansal** [comment]
@oorjitchowdhary Can you please help me for creating issues for your comment https://github.com/publiclab/plots2/issues/4132#issuecomment-444972178

**Comment by SidharthBansal** [comment]
I have created some tasks so please see that your tasks will not repeat with my issues created.

**Comment by SidharthBansal** [comment]
* [x] Sidebar on wiki pages
![image](https://user-images.githubusercontent.com/20972099/49637518-94b18600-fa2b-11e8-8562-fca584e5dfa7.png) #4165

**Comment by JonathanXu1** [comment]
Here's some more areas to add logins:

- [ ] Ask a question in public lab store:
![image](https://user-images.githubusercontent.com/22998430/49688576-6a6ecf80-fae2-11e8-89f1-847dac8e8236.png)
https://store.publiclab.org/collections/featured-kits/products/papercraft-spectrometer-intro-kit?variant=6100877213724
- [ ] Log in icon on pubic lab store:
![image](https://user-images.githubusercontent.com/22998430/49688604-b883d300-fae2-11e8-9fe8-1b0126f89212.png)
- [ ] Subscribe to emails in requests page:
![image](https://user-images.githubusercontent.com/22998430/49688628-08629a00-fae3-11e8-8713-8ab30dd84617.png)
https://publiclab.org/wiki/requests
- [ ] Join public lab link on research page:
![image](https://user-images.githubusercontent.com/22998430/49688645-3f38b000-fae3-11e8-9e21-b5e439b4790d.png)
https://publiclab.org/research

@SidharthBansal is this sufficient?

**Comment by dinaelhanan** [comment]
@JonathanXu1 so for the store, I'm seeing this as the login:
![screenshot from 2018-12-08 12-21-15](https://user-images.githubusercontent.com/19677511/49688686-cbe36e00-fae3-11e8-92b7-e27131009919.png)

Do you mean that we should add Oauth to it?

**Comment by SidharthBansal** [comment]
Great work!!!
It will be great if you can raise separate issues for these tasks and link them to this issue.

**Comment by dinaelhanan** [comment]
@oorjitchowdhary that's what I'm going to do :)

**Comment by SidharthBansal** [comment]
@dinaelhanan no you need not to do the OAuth for providers on the store. Store is a different website. Its codebase is not available to us.
I think we need not to link the login/sign up modal to that store page.

**Comment by oorjitchowdhary** [comment]
Oh i see.. So perhaps we can implement only its design for our login modal?

**Comment by JonathanXu1** [comment]
So should I remove both #4190 and #4191?

**Comment by dinaelhanan** [comment]
@JonathanXu1 no I just edited the title, we just have to make it a modal

**Comment by oorjitchowdhary** [comment]
I guess yes..

**Comment by SidharthBansal** [comment]
Let's have this conversation in the issue created.
No need to close issues @JonathanXu1

**Comment by JonathanXu1** [comment]
Alright. Can I submit this task on GCI then?

**Comment by SidharthBansal** [comment]
Yes. Go ahead.

**Comment by JonathanXu1** [comment]
Great, thanks! I'll send it in after the redundant share your work task has been approved.

**Comment by SidharthBansal** [comment]
You have not claimed it yet. I am online let's do it now.

**Comment by JonathanXu1** [comment]
![image](https://user-images.githubusercontent.com/22998430/49688927-77da8880-fae7-11e8-8396-7ad05f087986.png)

**Comment by SidharthBansal** [comment]
Approved

**Comment by dinaelhanan** [comment]
@SidharthBansal for this PR: #4149 I did all the requirements by @jywarren . I would like to get started on other tasks since the deadline is near, so can you please approve this task?
https://codein.withgoogle.com/dashboard/task-instances/4824240835526656/
Jeff has reviewed it and I met all criteria :)

**Comment by SidharthBansal** [comment]
@dinaelhanan @JonathanXu1 this issue is about ``identification of different pages to link the login modal``, please don't make this conversation divergent. I hope you both will not mind if you will tag me in the respective issues.

@dinaelhanan I will try to do it.

**Comment by SidharthBansal** [comment]
@oorjitchowdhary https://github.com/publiclab/plots2/issues/4132#issuecomment-444972178 please do the task which you forget to do in this issue. Thanks everyone

**Comment by oorjitchowdhary** [comment]
Oh.. I'll make the issues

**Comment by JonathanXu1** [comment]
@SidharthBansal For the future, where can we best contact mentors like you about non-task specific questions?

**Comment by SidharthBansal** [comment]
For gci related issues on the gci platform, for the reward related queries in the issue itself.
If still the task is not related to any issue on github or gci then you can contact us on gitter chat or #3698.
I hope this helps

**Comment by oorjitchowdhary** [comment]
> Oh.. I'll make the issues

@SidharthBansal #4194

**Comment by JonathanXu1** [comment]
Thanks, that's very helpful.

**Comment by SidharthBansal** [comment]
@oorjitchowdhary emojis are remaining. Can you create an issue for it also?

**Comment by oorjitchowdhary** [comment]
> @oorjitchowdhary emojis are remaining. Can you create an issue for it also?

Yes.. I was just searching if an issue was made for it.. I'll make it

**Comment by SidharthBansal** [comment]
No issue is created for the emojis

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I think the emojis aren't shown when you aren't logged in.. So we don't need an issue for linking... My bad there..

**Comment by SidharthBansal** [comment]
Thanks for the correction. I have already rewarded you for this task.
I missed to ask you to create issues for them

**Comment by SidharthBansal** [comment]
Sorry about that.

**Comment by dinaelhanan** [comment]
[x] Joining a group:

**Comment by SidharthBansal** [comment]
Please provide two more similar places where we want to link login modal

**Comment by kevinzluo** [comment]
- [ ] https://github.com/publiclab/plots2/issues/4231 Help answer future questions
- [ ] https://github.com/publiclab/plots2/issues/4230 Ask a Question
- [ ]  https://github.com/publiclab/plots2/issues/4229 Request an activity
- [ ] https://github.com/publiclab/plots2/issues/4241 Empty Notes Grids

**Comment by SidharthBansal** [comment]
Thanks a lot

**Comment by dinaelhanan** [comment]
@SidharthBansal looking back, I did find two! I found the store one, but Jonathan helped and opened the issue, so I identified two already :) I will add image of the joining a group but I don't know where to find it on the website

**Comment by SidharthBansal** [comment]
No problem. Please claim the task to get your rewards. I will give you rewards.

**Comment by dinaelhanan** [comment]
@SidharthBansal I have currently claimed the link login modal to follow post task, so I will wait till I finish that one, thanks!

**Comment by SidharthBansal** [comment]
ok

**Comment by dinaelhanan** [comment]
@SidharthBansal I have abandoned another task so I can get this approved. Please check it out here:
https://codein.withgoogle.com/dashboard/task-instances/5943340534071296/

**Comment by jywarren** [comment]
Wow, amazing work folks!

**Comment by SidharthBansal** [comment]
#4303 is related to this.

**Comment by SidharthBansal** [comment]
Issues are being worked upon. This issue is broken down into subsissues. 
So closing this.

**Comment by oorjitchowdhary** [comment]
I'm creating a fto for `ask related question`

**Comment by SidharthBansal** [comment]
Please note that linking to login modal common function is made. So for
that you can create a fto
 But linking to signup modal common Js function is not made as per as I
remember. So please don't form fto for that.
Please link fto to here for sure. Thanks a lot.

**Comment by oorjitchowdhary** [comment]
Here, #4416 for adding login modal

**Comment by oorjitchowdhary** [comment]
#4419 linking login modal to `ask a related question`
![image](https://user-images.githubusercontent.com/39333058/50468765-76f29380-09cf-11e9-9a91-288a0c590799.png)

**Comment by SidharthBansal** [comment]
Hi all, in case you find an issue related to this please feel free to jot it here in form of unchecked check boxes here into the list. Your help is very much needed here.
We will make separate issues for them once the issues present on the issue tracker are solved. We want to decrease the issues on issue tracker to less than 500 before creating new issues from this list.
Thanks all.

**Comment by oorjitchowdhary** [comment]
* [ ] `ask a question about tag` on tags.. #4431

**Comment by SidharthBansal** [comment]
Hi everyone, can you please search the website and tell us if still more such linking issues are present. If they are present then please write comment in this thread and make a fto for it. 
Thanks

**Comment by SidharthBansal** [comment]
@oorjitchowdhary can you please create ftos for the remaining stuff of https://github.com/publiclab/plots2/issues/4132#issuecomment-450020938. I believe that you know what is remaining so it will be quite easy for you. Hence pinging you. Don't forget to link them here.
Thanks.

**Comment by SidharthBansal** [comment]
Can you please create fto for it?

**Comment by SidharthBansal** [comment]
Also check at the website if there are more places where we need to link
the modals. That would be a great help.
Thank you

**Comment by SidharthBansal** [comment]
- [ ] flash message
- [ ] add one row
![image](https://user-images.githubusercontent.com/20972099/50536431-8b26c400-0b7a-11e9-9d16-760a6cd47019.png)

**Comment by SidharthBansal** [comment]
@oorjitchowdhary did you see any other similar issues?

**Comment by oorjitchowdhary** [comment]
Found just one..
* [ ] `Log in` button on /signup page

![image4](https://user-images.githubusercontent.com/39333058/50541096-4de72400-0bc4-11e9-862f-bed3c80472da.jpeg)

But we're implementing the signup modal too right.. so is this required? Will we keep the `log in` button in the modal?

**Comment by kevinzluo** [comment]
@oorjitchowdhary 
I believe @JonathanXu1 has linked the log in button on the signup modal to the log in modal.

Take a look at stable.publiclab.org

![modallinked](https://user-images.githubusercontent.com/44309027/50541663-f028ec80-0b6f-11e9-84bb-27028e927859.gif)

**Comment by geekychaser** [comment]
- [ ] #4437
login modal should be prompted while clicking on follow icon
![image](https://user-images.githubusercontent.com/24489162/50542515-205ea280-0be5-11e9-9010-a5e263b5a9b5.png)

**Comment by SidharthBansal** [comment]
@kevinzluo @oorjitchowdhary Jonathan has made the links to both the modals and they are woking correctly. But on hte /signup and /login they are not redirecting to each other pages. We need to have submit a fix after forming issue for it. @oorjitchowdhary can you kindly solve this? Kevin is taking some other work so I don't want to burden him much. Thanks both of you.

**Comment by oorjitchowdhary** [comment]
@sidharthbansal okay.. You mean to solve #4437 right?

**Comment by geekychaser** [comment]
@SidharthBansal @oorjitchowdhary i think this can be solved now , i should post a PR after this get merged https://github.com/publiclab/plots2/pull/4453

**Comment by SidharthBansal** [comment]
@oorjitchowdhary some work is done in #4457. Please refer it before submitting a pr for https://github.com/publiclab/plots2/issues/4132#issuecomment-450551508.
Thanks for the amazing work you are doing at public lab.

**Comment by oorjitchowdhary** [comment]
@sidharthbansal I saw the stable PL status..
The log in on /signup doesn't work and sign up on /login doesn't work.. So should I link the respective modals to the buttons or the respective pages?

**Comment by kevinzluo** [comment]
You are right @oorjitchowdhary! #4457 also depends on this. Do we want the links at /signup and /login to open the modals or redirect to the pages? I am in favor of the modals.

**Comment by SidharthBansal** [comment]
Having the signup modal over login page looks ambiguous to me. I think we
should redirect to the pages if present in the pages.

**Comment by oorjitchowdhary** [comment]
I'm a little confused about our modals..
If we have made modals, we should link to everywhere. And then why do we need the /login and /signup pages?

We could eliminate the /login and /signup pages, and just keep the modals..




On Dec 31, 2018, at 4:08 PM, Sidharth Bansal <notifications@github.com<mailto:notifications@github.com>> wrote:

Having the signup modal over login page looks ambiguous to me. I think we
should redirect to the pages if present in the pages.

**Comment by SidharthBansal** [comment]
Hi, @oorjitchowdhary actually Public Lab is a website which we are maintaining since 10 yrs. So there are many places which contain link to login and signup as /signup or /login. In case we will remove these pages those links will stop working. Functionality is more important than redundancy. I liked your suggestion but we cannot implement it.
Thanks for the suggestion.

**Comment by SidharthBansal** [comment]
- [*] Link login modal to 'Write a research note' at '/wiki/comment-templates'
#4481

**Comment by SidharthBansal** [comment]
@oorjitchowdhary we are creating the modals so that the person will not get derailed from the public labs while signup. I hope this solves your query.

**Comment by jywarren** [comment]
This is a spectacular effort, folks! Very impressive to see. Do you think it's worth adding to the README or docs somewhere that this new class can be added to any link to require login first? 

Thanks!!! 👍 🎉

**Comment by jywarren** [comment]
Also it's useful to have distinct /login and /signup pages so that we can send people the link to those if necessary. Modals don't have a URL, although of course we could send them the URL of a page that they can't access, but that's a little more complex to remember.

**Comment by jywarren** [comment]
I.e. "Oh, welcome! Try making an account at https://publiclab.org/signup"!

**Comment by oorjitchowdhary** [comment]
* [ ] fix login link at /signup #4507

**Comment by SidharthBansal** [comment]
I hope we have created issues for all the buttons/links where ever we require the login modal. In case we will require any more button to be linked we can simply open up a `first timer only` labelled issue @jywarren so wrapping up here and closing this IMMENSE issue. Thanks to all the folks who helped PL for the login/sign up front end migration for better UI.

**Comment by jywarren** [comment]
this is the most epic issue! :-) thank you all SO MUCH
