### ISSUE TITLE
Email digest follow-up changes list

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4732]
Our daily email digest is now working! Now we have a few follow ups to do. 

* [x] Images seem broken
* [x] dates on posts don't seem right (https://github.com/publiclab/plots2/pull/4851)
* [x] daily digest is labeled weekly (https://github.com/publiclab/plots2/issues/4822) (solved in https://github.com/publiclab/plots2/pull/4955)
* [x] some page width oddities on a smartphone
* [x] images not loading https://github.com/publiclab/plots2/issues/5230
* [x] item content is in Markdown and needs to be parsed to HTML
* [x] looks like maybe updated wiki pages are included? For now let's just show notes (https://github.com/publiclab/plots2/pull/5568)
* [x] are we sure the same posts aren't being sent out multiple times? #5907
* [x] adding today's date to the heading title of the digest email https://github.com/publiclab/plots2/pull/5331/

Overall this is very exciting!

**Comment by jywarren** [comment]
@viditchitkara check it out!

![screenshot_20190129-221111](https://user-images.githubusercontent.com/24359/51949215-d569c200-2412-11e9-986c-b825871b64e4.png)

![screenshot_20190129-221118](https://user-images.githubusercontent.com/24359/51949223-d995df80-2412-11e9-8e6f-e9ee381da3b1.png)

**Comment by jywarren** [comment]
Also linking with #2378 and with the browser based view of the digest at https://publiclab.org/subscriptions/digest

**Comment by jywarren** [comment]
That would be great! What part do you want to work on?

**Comment by ViditChitkara** [comment]
Wow, feels really good to see this working @jywarren. @arungoel123456 in my opinion you may start with dates and label of mail. This is what I feel would be a good starting point. It's totally up to you if you want to start with another. Ping me if you need any help with this.

**Comment by IshaGupta18** [comment]
@ViditChitkara @jywarren could I work on some other parts of this issue?

**Comment by gauravano** [comment]
Hi @IshaGupta18, feel free to proceed. But, before working on a part please drop a message here to let others know, to avoid any conflict. 

Also, @arungoel123456 and @IshaGupta18 you can discuss and divide parts here. Thanks!

**Comment by IshaGupta18** [comment]
Yes absoluely @gauravano. Thanks a lot! I actually found the places where the 'daily digest is labeled weekly' and 'dates on posts don't seem right' are mentioned. Maybe I can start with them, if @arungoel123456 hasn't already done that? Please let me know in either case.

**Comment by IshaGupta18** [comment]
I think that 'are we sure the same posts aren't being sent out multiple times?'  would be a relatively harder one, because we'll have to keep a record of what content has already been sent in the previous day's mail and a mail should be sent on that day if and only is the content is slightly different from the one sent the day before. I have received I think 2-3 redundant mails for a tag.

**Comment by arungoel123456** [comment]
@IshaGupta18 I would like to work on the date and label issue .... Sorry for the late reply

**Comment by arungoel123456** [comment]
@ViditChitkara I will sure contact u if I need some help . Thanks for advising

**Comment by jywarren** [comment]
Awesome folks, thanks! Yes Isha i agree on the redundancy issue - what we
can do is just be sure we're only reporting things that occurred in the
past day or week.

Also, things like wiki page edits and such are perhaps lower priority; we
could list them at the bottom in a section called "Active wiki pages"
without showing the full entry we do for notes; does that make sense?

**Comment by IshaGupta18** [comment]
@arungoel123456 kindly proceed then! @jywarren I think that could be great idea!

**Comment by IshaGupta18** [comment]
I think for the width related problems, we can do 2 things:

1) Make the existing code responsive
2) Make a new email format using tables and make that responsive

What's your take on this @ViditChitkara @jywarren ?

**Comment by jywarren** [comment]
Let's do responsive! Shouldn't we be able to use a layout similar to, or
even based on the same code as, the main PublicLab.org codebase? Thanks
Isha!

**Comment by IshaGupta18** [comment]
Hey @jywarren how should I test my changes that I will make to make the email responsive?

**Comment by IshaGupta18** [comment]
@jywarren @ViditChitkara Images are working fine to some extent, like if you change your gmail 
settings->images-> "always show", some of them show up, but not all, like the PL logo and default profile picture.

**Comment by jywarren** [comment]
Hi, Isha - there's a "test digest" button on the profile, i don't know if
it will pop up an email for you if you click it, but give it a try?

The other option is that we had made this page as an "online" version in
order to test the digest display: https://publiclab.org/subscriptions/digest

If you can track down the template there, perhaps we could have that page
display the same HTML as the email will, so it can be used to test out the
digest display online as well?

**Comment by IshaGupta18** [comment]
Hey sorry to bother you, I actually found a template in the /test/mailers/preview folder and I am trying to work on that! Thanks a lot for your help though!

**Comment by IshaGupta18** [comment]
I also wanted to let you know @jywarren that I will be having my mid semester exams during early mid-feb so I may not be as active, but I'll try to stay in touch as much as I can!

**Comment by jywarren** [comment]
ok, good luck with the exams, Isha!

**Comment by IshaGupta18** [comment]
Okay so I think I may have found a way to get rid of the page width problems, however, I am not too sure that if it will be considered as a very good way because it will require some refactoring of the existing code. Should I make a PR for it @jywarren ?

**Comment by jywarren** [comment]
sure!

**Comment by IshaGupta18** [comment]
#4780 is my PR in an attempt to fix width issues. @jywarren kindly have a look at it and let me know if there's anything else that can be done! Thanks a lot!

**Comment by arungoel123456** [comment]
what all issues are solved ? Can u please tell

**Comment by arungoel123456** [comment]
@jywarren  what is the status of this issue ? Can u please tell

**Comment by IshaGupta18** [comment]
Width related problems have been solved, author's profile picture problem
has been solved and some work is being done on weekly or daily title, I and
@jywarren are discussing that. You can make a PR for the date issue if you
want to. Thanks a lot!

**Comment by arungoel123456** [comment]
OK , let me check the date issue. Thanks

**Comment by IshaGupta18** [comment]
Okay @jywarren , so I am seeing, on using byebug, that the main_image_id field is nil even for a post that contains an image, for example (this is just a test post I made)

`#<Node nid: 49, vid: 49, type: "note", language: "", title: "try image", uid: 2, status: 1, created: 1549696643, changed: 1549696643, comment: 2, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/moderator/02-09-2019/try-image", main_image_id: nil, slug: "try-image", legacy_views: 0, views: 1>`

So I think this is why the images of the post are not appearing. Any ideas?

**Comment by arungoel123456** [comment]
#4792  is my pr for why dates dont appear right in emails

**Comment by IshaGupta18** [comment]
> #4792 is my pr for why dates dont appear right in emails

Moved to #4793

**Comment by IshaGupta18** [comment]
@arungoel123456 , for your query in #4792 , https://github.com/publiclab/plots2/issues/4732#issuecomment-462351446 read this.

Also, me and @jywarren discussed about `* are we sure the same posts aren't being sent out multiple times?` and I believe about `* looks like maybe updated wiki pages are included? If so we should present them a bit differently` as well and I have asked him about https://github.com/publiclab/plots2/issues/4732#issuecomment-462359915 as well. So I think we should wait for his reply on the progress of things in the issue.

**Comment by jywarren** [comment]
Re main image - try using this code here, which looks for a main image, and if it doesn't find one, actually tries to scrape out the first image in the post:

https://github.com/publiclab/plots2/blob/fe50428f4c56f12fcea92ae76343346d0421da70/app/views/notes/_notes.html.erb#L7-L11

Thanks!

**Comment by jywarren** [comment]
Just responded in https://github.com/publiclab/plots2/pull/4780#discussion_r255303340, but this is looking great, and we can do the refactoring of `weekly` vs `daily` in a new issue!

**Comment by IshaGupta18** [comment]
#4822 for the weekly vs daily issue!

**Comment by arungoel123456** [comment]
#4824  For dates to appear right In E-MAIL

**Comment by IshaGupta18** [comment]
@jywarren #4875 is the PR for fixing broken images! Let me know what else can be done! Thanks a ton!

**Comment by jywarren** [comment]
Hi, thanks @IshaGupta18 - merged that one! Reopening for the remainder of this checklist! Thanks!

**Comment by jywarren** [comment]
I added some notes and tips to https://github.com/publiclab/plots2/issues/4822 -- great!

**Comment by jywarren** [comment]
And @arungoel123456 solved the date one in https://github.com/publiclab/plots2/pull/4851 -- great work!

**Comment by jywarren** [comment]
Daily/weekly fix is live! Checked it off.

![image](https://user-images.githubusercontent.com/24359/54772233-55bfce80-4bdd-11e9-8a2a-a884dce40922.png)

I noticed not all images are loading so I added a new item to the checklist above. 

The image URLs were:

profile pic: http:///system/profile/photos/1/thumb/bio-jeff-warren.jpg

post picture: http:///system/images/photos/000/030/324/medium/IMG_20190320_162254_076.jpg

It looks like we're skipping the "publiclab.org" part in the template. We should be able to add in `Rails.root` in `/app/views/mailers/...`

Getting there!

**Comment by jywarren** [comment]
Made a FTO for this! https://github.com/publiclab/plots2/issues/5230

**Comment by jywarren** [comment]
Making new ones for Markdown and for the date in the title!

https://github.com/publiclab/plots2/issues/5340 and https://github.com/publiclab/plots2/issues/5341 !

**Comment by jywarren** [comment]
Added: `looks like maybe updated wiki pages are included? For now let's just show notes` (#5568)

**Comment by IshaGupta18** [comment]
Okay, so I think there are a couple of more bugs with the email digest.

![image](https://user-images.githubusercontent.com/40794215/56497444-232a2e00-651b-11e9-804e-b4e79753e0dc.png)

(Like the date problem and the links at the bottom)

 I am gonna work on them as well as the ones you have added here @jywarren, just some refining is needed I think, and a little more integration with the parts we have broken up this issue into.

**Comment by IshaGupta18** [comment]
@jywarren #5638 is my PR for the broken date issue as shown above, kindly review and let me know if its good to go. Thanks!

**Comment by IshaGupta18** [comment]
So I have seen that all the links (after being updated to full path) are breaking somewhere and hence, both authors' and notes' images are being broken. Could someone tell me why we need to keep the full path because by keeping the original paths, the images seem to work just fine? Thanks!

**Comment by jywarren** [comment]
Whoa, that's odd because i'm seeing digests like this:


![image](https://user-images.githubusercontent.com/24359/57020756-509c6900-6bf8-11e9-82e8-b30fe90432f9.png)

Which is not perfect but better than what you seem to be receiving?

**Comment by IshaGupta18** [comment]
Yeah, I think so, but in my mail box, the links ( the "click here" links at the bottom) and the images seem to be broken:
![image](https://user-images.githubusercontent.com/40794215/57021926-3b045f00-6c4b-11e9-936e-4b088d9207ce.png)

What do you think should be done?

**Comment by IshaGupta18** [comment]
And also, I think we can open up an FTO for the` date in the heading` checkpoint, because the PR #5331 is for the path links part of this issue. Please correct me if I am wrong?

**Comment by jywarren** [comment]
hmm, this is so weird! Are you sure that email is from our production
server? Thanks Isha!!!

**Comment by IshaGupta18** [comment]
This comes from the production right?
![image](https://user-images.githubusercontent.com/40794215/57023094-c4696080-6c4e-11e9-9b7a-6980fed34e38.png)

This is really weird.

**Comment by jywarren** [comment]
Almost there now! I think we need to adjust image aspect ratio:

![image](https://user-images.githubusercontent.com/24359/58059923-f4649f00-7b3c-11e9-9e6c-af0c76276ffd.png)

Also, i confirmed, posts are getting included day after day, so I'm not sure why but maybe it's sending for any revisions, or something?

**Comment by jywarren** [comment]
OK, last thing -- this section fetches revisions by timestamp, which is why old posts are getting re-added to the digest when they are updated (i.e. their revision gets a new timestamp):

https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L245-L260

I'm going to make a parameter to include revisions and default it to false.

**Comment by jywarren** [comment]
OK! This should be completely finished when #5907 merges. Thanks all!!!!!
