### ISSUE TITLE
Collect and solve Bootstrap 4 follow-up fixes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5612]
Hi, we have finally upgraded to Bootstrap4 in #3937. Thanks @Souravirus for your awesome work :tada: :100: 

Let's team up to look at the newly updated Bootstrap 4 UI https://stable.publiclab.org and compare to https://publiclab.org -- and note issues below.

Please report the issue below by leaving a comment and don't open a separate issue so that we can keep everyone synced :arrows_counterclockwise: 

We also want your help with the issues reported below so sit back with your :headphones: :computer: and raise a PR. Make sure to comment below if you're working on a specific issue so that no one else work on the same. 

Thanks everyone :raised_hands: !!!

****

![image](https://user-images.githubusercontent.com/24359/56694495-ce221f80-66b4-11e9-9086-b376eff9b767.png)

^ Looks like the posting form main image upload button is oddly shaped!

**Comment by Souravirus** [comment]
Hi @jywarren, here is the updated gist for the updated carousel
https://gist.github.com/Souravirus/1f70b1ec63da1adaa686ccff7186ab2f

**Comment by Souravirus** [comment]
The main image button is appearing fine in firefox. 
![image](https://user-images.githubusercontent.com/17192149/56695612-18cc8780-6707-11e9-8192-3936f0506e27.png)
There might be some differences with the browser. Seeing this.

**Comment by jywarren** [comment]
OK thanks @Souravirus and thanks @gauravano, i thought we should start a new one 🙌

**Comment by gautamig54** [comment]
I would love to contribute in this issue! Thanks!

**Comment by gauravano** [comment]
@jywarren just edited the issue :sweat_smile:. Also, adding @stefannibrasil and @sashadev-sky's observations from #5182. Thanks!

**Comment by gauravano** [comment]
Issues reported by @stefannibrasil 
------
oh, okay :v: 

The front page is looking weird. Maybe someone pushed other commits again?
The carousel is not working and all of the static content (social media icons, questions button, etc.) are not showing.

### Some spaces to be added:
 * between the nodes and the pagination buttons (front page);
 * after node types buttons on /search page;
 * between nodes results ( the read more button is attached to the other node's image);
 

### General notes
* Any misalignments seen in radio buttons or checkboxes can be fixed using the classes in `btsp_checkbox_override.css.scss`. Note these misalignments were there before the update and the update has not fixed them --- by @sashadev-sky. Refer https://github.com/publiclab/plots2/issues/5182#issuecomment-481104366 for details 
* The footer is different when you navigate between the pages. For example, in the Dashboard, I see a different footer than the one being shown at the front page;
* Also in the Dashboard, when I clicked on 'Share your work', the dropdown is floating to the right, not beneath it;
* When adding a question, in the button group, the Markdown is not at the same line as the others;
* In the highlighted note that appears in the Dashboard, the text 'Node title by user1 from Public Lab Blog` is not aligned;
* The 'enter tag' placeholder is not possible to read here, for example, https://unstable.publiclab.org/getting-started (maybe removing the caret solves this, since it's already visible that it's a button?)
* The button group here is not aligned https://unstable.publiclab.org/wiki/plots-staff
* Align the button hat the /subscriptions page;
* I think these buttons for Questions and Research notes are too big https://unstable.publiclab.org/wiki/organizers
* Just the 'logout from all devices' option is showing up, not sure if this is intentional;

I think that was all, good job! :tada:

**Comment by gauravano** [comment]
> I would love to contribute in this issue! Thanks!

Most welcome @gautamig54 !!

**Comment by Souravirus** [comment]
The issue you reported with the input button is happening in google chrome
![image](https://user-images.githubusercontent.com/17192149/56715097-51df1900-6754-11e9-87cd-dc9829645134.png)

**Comment by Souravirus** [comment]
Hi @jywarren that input button problem is now solved. Here is the screenshot of it:
![image](https://user-images.githubusercontent.com/17192149/56828907-fad66280-687f-11e9-93f6-e3b5897c4f6c.png)
I am pushing the fixes in #5613.

**Comment by jywarren** [comment]
Awesome, thanks!!!!

**Comment by Souravirus** [comment]
Reopening this issue as some of the bugs were not solved.

**Comment by jywarren** [comment]
Thanks, @Souravirus -- i'm trying to paste in your gist for the front-page carousel, and the Features system is a little strange looking; it also errors when I try to make a new feature:

![image](https://user-images.githubusercontent.com/24359/57086503-3b910a00-6ccc-11e9-8600-87eaa59ad33f.png)

I know you're in exams, so if anyone else is able to help out with this, that'd be great!

**Comment by jywarren** [comment]
Looks like there are pretty minimal changes to the form: 
https://github.com/publiclab/plots2/commit/7744d91e9bf03544da2f38e7e66056b6f20162e0#diff-d218cc0d572a2c87e465b2f68f3a20f8R5

I'll open a PR for a functional test for this!

**Comment by jywarren** [comment]
I'm also having trouble dragging an image onto a wiki edit page; it returns an error on this line of dragdrop.js:

`($D.selected).find('#create_progress').eq(0).show();`

`Uncaught TypeError: Cannot read property 'find' of undefined`

I wonder if `$D.selected` was affected somehow? This is the kind of thing a system test (#5316) will help prevent!

**Comment by Souravirus** [comment]
Hi @jywarren, I see the carousel is fixed but there are some other problems there too like:
- [ ] No space after the carousel and the social icons
- [ ] Carousel is not changing
- [ ] There is a newline after the problem, collaboration, and the solution sections.

**Comment by jywarren** [comment]
Yes, I gave it a try, but didn't get it all the way! Here's the code:
https://gist.github.com/jywarren/3128766b5739555e6096aa12b27ab754

And i forget if you're an admin on unstable, but I put it here:
https://stable.publiclab.org/features/14908/edit?t=1556900971

I'll try again soon, we'll have to resolve this before publishing! Thanks!

**Comment by Souravirus** [comment]
I don't think I am admin in unstable as I can't see the link.

**Comment by Souravirus** [comment]
Hi @jywarren, since the previous carousel was powered by slick right? Then why didn't it worked with Bootstrap 4. What do you think about this?

**Comment by jywarren** [comment]
You know, i think if necessary we can freeze the carousel, and just show an
image as a short term fix. Just saying if that's easier! I thought the
block at this point was the rest of the page lower down, however. I will
take a look tomorrow!! Thank you!!

**Comment by Souravirus** [comment]
Yeah I can try this fix. Thanks!!

**Comment by jywarren** [comment]
awesome!!!

**Comment by Souravirus** [comment]
@jywarren  I have improved the homepage and kept only one image instead of the carousel.
Here is the gist https://gist.github.com/Souravirus/7bb63f9188f955d85e856ea14e47caff
Thank you!!

**Comment by jywarren** [comment]
It looks great, Sourav, thanks. I may mess with the white text a bit but it's already not perfect...

https://stable.publiclab.org/home

I notice that there are now only 2 columns where we used to show 4; 

![Screen Shot 2019-05-06 at 10 18 52 AM](https://user-images.githubusercontent.com/24359/57231507-a2723400-6fe8-11e9-9888-2c4cb9156a9d.png)

do we need to change a style in `views/notes/_notes.html.erb` to make it 4 column?

**Comment by Souravirus** [comment]
Hmm this seems fishy, let me see it.

**Comment by Souravirus** [comment]
Hi @jywarren, actually there was a mistake by me while doing the update. I have changed col-md-3 col-lg-6 which has been corrected to col-lg-3. So, now everything will appear fine.
Thank you!!

**Comment by jywarren** [comment]
Found a couple small ones here; one is a feature we will probably get rid of, but it uses the tag `tabbed:notes` to display tabs; compare this page (https://stable.publiclab.org/wisconsin) to the one on PublicLab.org:

![image](https://user-images.githubusercontent.com/24359/57324746-79c86800-70d6-11e9-9fd3-f4c21500dd45.png)

The other is small; i see this in a few places, but the button groups are occasionally showing discontinuities, where a left-end-button is stuck in the middle of a group:

![image](https://user-images.githubusercontent.com/24359/57324806-a2506200-70d6-11e9-83aa-703353dbe436.png)

**Comment by Souravirus** [comment]
![image](https://user-images.githubusercontent.com/17192149/57329335-34855400-7131-11e9-9382-ffc7f1e4542a.png)
Here is the error I am getting while logging in to localhost. So, this is the error @jywarren

**Comment by jywarren** [comment]
hmm, uh oh! Um, i just merged a PR that passed tests addressing this. Did
something go wrong with the merge?

**Comment by jywarren** [comment]
Huh... it should be available, no?
https://github.com/publiclab/plots2/search?q=logged_in_as

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/d55c716621d8072d0ffcd51b46c6b2b240ce5f4d/app/helpers/application_helper.rb#L3

**Comment by jywarren** [comment]
Ack, helpers are available to views but not by default to controllers. We
will need to change where we do this from controllers...

**Comment by jywarren** [comment]
OK i'm going to copy this method into application_controller for now, just
to solve this.

**Comment by jywarren** [comment]
but i want to catch this in a test -- and know why it didn't work!
https://github.com/publiclab/plots2/pull/5677

**Comment by jywarren** [comment]
OK, fixed it! https://stable.publiclab.org/dashboard -- still not sure how this didn't get caught by tests... maybe it's because we run the tests with ApplicationHelper included? I'll try to write a system test for the dashboard!

**Comment by jywarren** [comment]
OK, dashboard system test here: https://github.com/publiclab/plots2/pull/5682

**Comment by Souravirus** [comment]
![image](https://user-images.githubusercontent.com/17192149/57355726-4f38e680-718c-11e9-8a96-abc4c3e082db.png)
@jywarren, In the homepage, these items are overlapping, can you please send me the homepage features again, I will correct them.
And nice to hear that the dashboard is working fine.
:smile:

**Comment by jywarren** [comment]
Ah! Our signup spamaway quiz is a little funky!

![image](https://user-images.githubusercontent.com/24359/57410173-1d3d7980-71b8-11e9-8bd5-ac4356360eb8.png)

And here's the front page! https://gist.github.com/jywarren/3128766b5739555e6096aa12b27ab754

Thanks, @Souravirus !!!

**Comment by jywarren** [comment]
Lol i gave away the answers 🐷 🐻 🐰 ✍️

**Comment by jywarren** [comment]
Hmm, I'm actually seeing some formatting issues for the whole signup form:

![image](https://user-images.githubusercontent.com/24359/57414837-cc358180-71c7-11e9-90ae-0f8b44cdf51e.png)

@IshaGupta18 @CleverFool77 I think you both have worked with this file, and may be familiar with it. Would either of you like to try refactoring it to work well in Bootstrap 4?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/users/_create_form.html.erb

**Comment by SidharthBansal** [comment]
Awesome Work 
It is EPIC

**Comment by Souravirus** [comment]
@jywarren, that button in the sidebar which discontinues is actually a dropdown, so, I cannot append it with other buttons. So, what should I do? I guess other buttons are working fine but this one discontinues.

**Comment by jywarren** [comment]
hmm. in Bootstrap 3 there was an example for this scenario. What about
this? https://getbootstrap.com/docs/4.3/components/button-group/#nesting

**Comment by Souravirus** [comment]
Ok checking it out.

**Comment by Souravirus** [comment]
Here is the homepage updated for small screens https://gist.github.com/Souravirus/7bb63f9188f955d85e856ea14e47caff

**Comment by Souravirus** [comment]
![image](https://user-images.githubusercontent.com/17192149/57484448-aba02100-72c6-11e9-8acb-4aa44b6e5fda.png)
Ok buttons fixed

**Comment by jywarren** [comment]
awesome! Added to stable, it works perfectly.

**Comment by jywarren** [comment]
awesome!!!

**Comment by jywarren** [comment]
just adding a few more here:

* [ ] the upper-right profile picture used to be circular
* [ ] the drag to upload lead wiki image zone used to be higher up, if there is not yet an image set - basically in line with the top of the textarea
* [ ] the editing tools button groups seem to be a little too close to each other


![image](https://user-images.githubusercontent.com/24359/57954677-95472600-78c1-11e9-886b-066a6fff88b9.png)

Also some padding issues on these pages: 

I think the "methods" cards need some bottom-margin when in mobile phone widths:

![image](https://user-images.githubusercontent.com/24359/57954778-e6efb080-78c1-11e9-9fc2-5842f4ab9770.png)




Tiny stuff, but makes a difference!

**Comment by jywarren** [comment]
OK, and one more here -- the footer seems to be all in one column - we're almost there! 

![image](https://user-images.githubusercontent.com/24359/58047092-3d086200-7b15-11e9-9d29-fb4859bc10b7.png)

**Comment by jywarren** [comment]
Fixed the footer! It was in a feature!

**Comment by jywarren** [comment]
Questions page profile images seem to be inflated:

https://publiclab.org/questions/stevie/05-20-2019/what-happens-to-the-simple-air-sensor-when-the-battery-pack-runs-low#answer-0-comment-24212

![image](https://user-images.githubusercontent.com/24359/58052225-43510b00-7b22-11e9-8632-861a5216135f.png)

**Comment by jywarren** [comment]
And another small but important one -- as the navbar gets narrower, we had it set up to bump items into the dropdown menu, but they aren't displaying properly now;

![image](https://user-images.githubusercontent.com/24359/58058453-0cd1bb00-7b37-11e9-8805-c2107ae7fd58.png)

**Comment by CleverFool77** [comment]
Referencing the Issue https://github.com/publiclab/plots2/issues/5741 .
- [ ] updating forms as per bootstrap4

**Comment by CleverFool77** [comment]
Hi everyone, I would like to some of the follow-up fixes for bootstrap4.
Thanks !!!

**Comment by jywarren** [comment]
Hi, we'd love your help! Especially with the navbar, actually, as that
affects every page!

**Comment by steviepubliclab** [comment]
Hi all! thanks for all the work on this. Wow!! 

One suggestion, I've been finding since the update that I'm reducing the zoom on my Public Lab windows to 75% so I can see enough on one page to make out what's going on. Anyone else experiencing this? Is there a way to decrease the font size?

**Comment by Souravirus** [comment]
Hi @CleverFool77 really nice work here. Keep it up!!
