### ISSUE TITLE
Weekly Community Communication #1 🙋‍♀️🙋🙋‍♂️ 

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#5627]
Welcome!  Below you will find links to our weekly community check-ins.   Feel free to introduce yourself, ask questions in the current one, and explore past check-ins to get a feeling for the community.

### Where to communicate this week:

**Issue Link:** https://github.com/publiclab/plots2/issues/9526 🎉 
**Theme:**  -  99 by @TildaDares 
🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌 

### Upcoming Check-in:
* [ ] 101

### Check-in Ideas:
https://github.com/publiclab/plots2/issues/9480

### Past Check-ins:

* [x] 1. Gaurav Sachdeva (@gauravano) https://github.com/publiclab/plots2/issues/4327
* [x] 2. Sidharth Bansal (@SidharthBansal) https://github.com/publiclab/plots2/issues/4369
* [x] 3. Cess (@cesswairimu) https://github.com/publiclab/plots2/issues/4476
* [x] 4. Harman Jolly (@CoderJolly) https://github.com/publiclab/plots2/issues/4548
* [x] 5. Rishabh Rawat (@Rishabh570) https://github.com/publiclab/plots2/issues/4607
* [x] 6. Sasha Boginsky (@sashadev-sky) https://github.com/publiclab/plots2/issues/4676
* [x] 7. Rishabh Kr Bothra (@geekychaser) https://github.com/publiclab/plots2/issues/4711
* [x] 8. Shubham Sangamnerkar (@shubhscoder) https://github.com/publiclab/plots2/issues/4757
* [x] 9. Siddhant N Trivedi (@sidntrivedi012) https://github.com/publiclab/plots2/issues/4784
* [x] 10. Isha Gupta (@IshaGupta18) https://github.com/publiclab/plots2/issues/4844
* [x] 11. Gaurav Sachdeva (@gauravano) https://github.com/publiclab/plots2/issues/4879
* [x] 12. Harshith Pabbati (@Harshithpabbati) https://github.com/publiclab/plots2/issues/4917
* [x] 13. Gaurav Sachdeva (@gauravano) https://github.com/publiclab/plots2/issues/5034
* [x] 14. Harshith Pabbati (@Harshithpabbati) https://github.com/publiclab/image-sequencer/issues/883
* [x] 15. Harman Jolly (@CoderJolly) https://github.com/publiclab/mapknitter/issues/447
* [x] 16. Divya Baid (@divyabaid16) https://github.com/publiclab/PublicLab.Editor/issues/317
* [x] 17. Gautami Gupta (@gautamig54) https://github.com/publiclab/leaflet-environmental-layers/issues/164
* [x] 18. Sasha Boginsky (@sashadev-sky) https://github.com/publiclab/Leaflet.DistortableImage/issues/215
* [x] 19. Sagarpreet Chadha (@sagarpreet-chadha) https://github.com/publiclab/leaflet-blurred-location/issues/198
* [x] 20. Harsh (@HarshKhandeparkar) https://github.com/publiclab/spectral-workbench/issues/451
* [x] 21. Pranshu Srivastava (@rexagod) https://github.com/publiclab/inline-markdown-editor/issues/72
* [x] 22. Divy Khare (@Divy123) https://github.com/publiclab/image-sequencer/issues/1065
* [x] 23. Aashna (@aashna27) https://github.com/publiclab/leaflet-blurred-location-display/issues/78
* [x] 24. Atibhi Agrawal (@aSquare14) -  https://github.com/publiclab/plots2/issues/5828
* [x] 25. Gaurav Sachdeva (@gauravano) -  https://github.com/publiclab/simple-data-grapher/issues/41
* [x] 26. Sasha Boginsky (@sashadev-sky ) -  https://github.com/publiclab/plots2/issues/5943
* [x] 27. Álax (@alaxalves ) - https://github.com/publiclab/mapknitter/issues/772
* [x] 28. Ananya Arun (@ananyaarun ) https://github.com/publiclab/leaflet-environmental-layers/issues/231
- [x] 29. Vidit(@ViditChitkara) -  https://github.com/publiclab/mapknitter/issues/851
- [x] 30. Cess (@cesswairimu) -  https://github.com/publiclab/community-toolbox/issues/237 
- [x] 31. Rishabh (@Rishabh570) - https://github.com/publiclab/image-sequencer/issues/1195
- [x] 32. Naman (@namangupta01 ) - #6130 
- [x] 33. Gaurav (@gauravano) #6205
- [x] 34. Sidharth (@SidharthBansal ) - #6270 - Welcoming the youth
- [x] 35. Cess (@cesswairimu ) https://github.com/publiclab/webjack/issues/119 -  Hackoberfest is here.
- [x] 36. Cess (@cesswairimu ) https://github.com/publiclab/plots2/issues/6470 -  Create first-timer issues.
- [x] 37. Vaibhav (@vaibhavmatta  ) https://github.com/publiclab/image-sequencer/issues/1280 -  Making new FTO's and Making IS UI stable.
- [x] 38. Sidharth (@SidharthBansal) https://github.com/publiclab/plots2/issues/6762 - Planning GCI and Prize Guidelines
- [x] 39. Sagarpreet (@sagarpreet-chadha)  https://github.com/publiclab/plots2/issues/6792 - Ask for help
- [x] 40. Sudipto Ghosh (@pydevsg ) https://github.com/publiclab/plots2/issues/6845 - Pre GCI Preparation! 
- [x] 41. Cess (@cesswairimu ) https://github.com/publiclab/mapknitter/issues/1150 -  Everybody Struggles 
- [x] 42. Cess (@cesswairimu ) https://github.com/publiclab/leaflet-blurred-location/issues/227 -  Happy Holidays
- [x] 43. Cess (@cesswairimu)https://github.com/publiclab/community-toolbox/issues/308 -  Exciting Moments at PL
- [x] 44. Uzay-G (@Uzay-G )https://github.com/publiclab/mapknitter/issues/1199 - Learning with Public Lab
- [x] 45. Barun Acharya (@daemon1024 )https://github.com/publiclab/image-sequencer/issues/1540 - The First Step
- [x] 46. Sudipto Ghosh (@pydevsg  )https://github.com/publiclab/plots2/issues/7364 - End of GCI , start for SoCs.
- [x] 47. Emily Ashley (@emilyashley ) https://github.com/publiclab/plots2/issues/7429 - Software Contributor Community Survey is Live
- [x] 48. Natalie St Jean (@nstjean) [#394](https://github.com/publiclab/leaflet-environmental-layers/issues/394) Career Options
- [x] 49. Cess (@cesswairimu)-https://github.com/publiclab/spectral-workbench/issues/482 - Tech conferences recommendations 
- [x] 50. Cess (@cesswairimu) https://github.com/publiclab/leaflet-blurred-location/issues/237 - Favorite text editors 
- [x] 51.  Cess (@cesswairimu)https://github.com/publiclab/infragram/issues/102 - GSoC and Outreachy applications are open
* [x] 52. Cess (@cesswairimu) https://github.com/publiclab/plots2/issues/7711 - Stay Safe 
* [x]  53. Govind Goel (@govindgoel) https://github.com/publiclab/plots2/issues/7749 - Be Productive
* [x] 54. Uwagbae Alexander Obayagbona (@Alexjake660) https://github.com/publiclab/plots2/issues/7793 - Don't Give Up 
* [x] 55. Cess (@cesswairimu ) https://github.com/publiclab/spectral-workbench/issues/498 - How are you doing?- Check-in with us
* [x] 56.  Sneha Mishra (@Tlazypanda  ) https://github.com/publiclab/plots2/issues/7844 - Be generous, support and spread the word! 
* [x] 57. Sidharth Bansal (@SidharthBansal)  #7866 - GSoC & Outreachy Commences
* [x] 58. nicoleiocana (@nicoleiocana)  https://github.com/publiclab/plots2/issues/7899 - Acceptance
* [x] 59. Shulammite (@Shulammite-Aso) https://github.com/publiclab/plots2/issues/7926   - Always Communicate
* [x] 60. Cess (@cesswairimu) - https://github.com/publiclab/plots2/issues/7950 - Soc Community Bonding wrap up
* [x] 61. Cess (@cesswairimu) - https://github.com/publiclab/PublicLab.Editor/issues/523 - Bash aliases
* [x] 62. Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8002 - Help New Contributors!
* [x] 63. Keshav Sethi (@keshavsethi ) - https://github.com/publiclab/plots2/issues/8040 - Stay Updated!
* [x] 64. Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8059 - We are here for you.
* [x] 65. Cess (@cesswairimu )- https://github.com/publiclab/spectral-workbench/issues/520 -  GSoC first Eval due this week
* [x] 66. Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8113 - Books/Podcasts/Movies that you draw Inspiration from
* [x] 67. Cess (@cesswairimu )- https://github.com/publiclab/plots2/issues/8143 -  GSoC first Eval due this week
* [x] 68. Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8172 - Share new and exciting technologies/tools
* [x] 69. Sagarpreet (@sagarpreet-chadha) - https://github.com/publiclab/PublicLab.Editor/issues/578 - Share your free time hobbies
* [x] 70. Shulammite (@Shulammite-Aso) - https://github.com/publiclab/PublicLab.Editor/issues/585 - Share your adventures for the next few weeks and months
* [x] 71. Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8280 - Creating FTO's from our internship tasklist
* [x] 72. Cess (@cesswairimu  ) - https://github.com/publiclab/community-toolbox/issues/386 - Outreachy Wrap up
* [x] 73. Shulammite (@Shulammite-Aso) - https://github.com/publiclab/spectral-workbench/issues/541- GSoC Wrap up
* [x] 74. Sagarpreet (@sagarpreet-chadha)  - https://github.com/publiclab/plots2/issues/8374 - Retrospect of the work done
* [x] 75. Cess (@cesswairimu) - https://github.com/publiclab/plots2/issues/8394 - Thank you GSoC and Outreachy folks 
* [x] 76. Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8419 - Let's create some Hacktoberfest 
issues
* [x] 77.  Cess (@cesswairimu) - https://github.com/publiclab/plots2/issues/8440 - Hacktober and Outreachy October
* [x] 78. Cess (@cesswairimu) -  https://github.com/publiclab/PublicLab.Editor/issues/634 -  Create ftos for Outreachy aspirants
* [x] 79. Ruth Njeri (@RuthNjeri ) - https://github.com/publiclab/plots2/issues/8619 -  Draft Your Outreachy Proposal
* [x] 80.  Audrey(@Cadreia) - https://github.com/publiclab/plots2/issues/8676 - Outreachy Application (Winter 2020) Ends Soon! 
* [x] 81. @KarenEfereyan - #8709 - Do That Which Scares you (#8709)
* [x] 82. TAWAH (@tawahpeggy) - https://github.com/publiclab/plots2/issues/8719 We Rise By Lifting Others
* [x] 83. Cess(@cesswairimu ) - https://github.com/publiclab/image-sequencer/issues/1768 - Check in with us
* [x] 84. TAWAH (@tawahpeggy) - https://github.com/publiclab/plots2/issues/8760  - See Beyond its Flaws
* [x] 85.  Sneha Mishra (@Tlazypanda ) - https://github.com/publiclab/plots2/issues/8791 - Outreachy is here
 * [x] 86. Cess(@cesswairimu) -https://github.com/publiclab/mapknitter/issues/1474 - Check-in 86
 * [x]  87. Cess(@cesswairimu ) - https://github.com/publiclab/plots2/issues/8877 -  Everybody Struggles
 * [x] 88. Ruth (@RuthNjeri) - https://github.com/publiclab/plots2/issues/8931 - Tools, Tips, & Tricks
 * [x] 89 Cess(@cesswairimu) - https://github.com/publiclab/plots2/issues/9077 - Create FTOs
 * [x] 90 Will (@noi5e) - https://github.com/publiclab/plots2/issues/9112 - Modifying Expectations
 * [x] 91 Ruth (@RuthNjeri) -https://github.com/publiclab/plots2/issues/9158 - Breaking Down Tasks
 * [x] 92 Cess(@cesswairimu ) - https://github.com/publiclab/plots2/issues/9205 - Lets talk BurnOut
 * [x] 93. Cess(@cesswairimu ) - https://github.com/publiclab/plots2/issues/9229 - SoC Preparation
 * [x] 94. Cess(@cesswairimu ) - https://github.com/publiclab/plots2/issues/9274 - Congratulations winter 2020 Outreachy interns
 * [x] 95. Cess(@cesswairimu)  - https://github.com/publiclab/plots2/issues/9318 - Outreachy Presentations
 * [x] 96. Ruth(@RuthNjeri) - https://github.com/publiclab/plots2/issues/9350 - Understanding Your Users and The Product
 * [x] 97, Cess(@cesswairimu ) - https://github.com/publiclab/plots2/issues/9389 - GSoC and Outreachy applications are open 
 * [x] 98, Anirudh (@anirudhprabhakaran3) - https://github.com/publiclab/plots2/issues/9444 - GSoC and Outreachy applications still open!
 * [x] 99, Elukoye (@Elukoye) - https://github.com/publiclab/plots2/issues/9496 - 99 
 * [x] 100, Tilda (@TildaDares) - https://github.com/publiclab/plots2/issues/9526 - the  100th

**Comment by SidharthBansal** [comment]
Can anyone from @publiclab/soc update this?

**Comment by skilfullycurled** [comment]
@SidharthBansal, I'm not in soc (I don't think) but what type of updating are you referring to?

**Comment by Harshithpabbati** [comment]
@SidharthBansal  This was already updated right ? And will be updated after next check-in.

**Comment by SidharthBansal** [comment]
@Harshithpabbati oh sorry. I misread it. It is correct. thanks all

**Comment by sashadev-sky** [comment]
@skilfullycurled hi! I wrote a [research note](https://publiclab.org/notes/sashadev-sky/05-16-2019/public-lab-s-contribution-framework-deep-dive-2019?_=1558316207) this week and I mentioned your work to improve PL's checkins :) 

I mentioned you then realized that's not your PL account handle - do you have one? You should consider making one; I would love to give you credit!

**Comment by skilfullycurled** [comment]
@sashadev-sky!  I'm [bsugar](https://publiclab.org/profile/bsugar#2/33.0/-84.0/BL1)!!  This is my comment [here](https://publiclab.org/notes/sashadev-sky/05-16-2019/public-lab-s-contribution-framework-deep-dive-2019?_=1558316207#c24171).  I must not have noticed my own handle because I wasn't expecting my github account on PL.  

It's such a great piece.  What makes PL "work" is something that I find fascinating to the level of resaerch-able.  That was so nice of you to acknowledge me!  I didn't know you had implemented the weekly check-in's (which I love!), so for you to include my refinement in the same sentence as your actual invention is really touching and just put me int he best mood to start off the week.  Thank you!

**Comment by skilfullycurled** [comment]
Oh, @sashadev-sky, feel free to "resolve" these comments after you read them.  I don't think I have those permissions.

**Comment by sashadev-sky** [comment]
@skilfullycurled aw that's really sweet!! Glad to include you - listing them here is a great idea.

I just updated this today, which is probably why you didn't see it before. I will update it to use your correct handle right now

**Comment by aSquare14** [comment]
https://github.com/publiclab/plots2/issues/5828

**Comment by skilfullycurled** [comment]
@jywarren, just be careful, that's actually a load bearing pin.  : P

![load_bearing_poster](https://user-images.githubusercontent.com/950291/64976805-2f26db80-d880-11e9-862d-97349275d1ef.gif)

**Comment by pydevsg** [comment]
#6845

**Comment by SidharthBansal** [comment]
Mentors are requested to fill the form
https://docs.google.com/forms/d/1UcmXtNEVjZW6fozpW_9gWduRpnfVNG816JTswx85_VA/edit asap
DEADLINE 27 January 18 IST
Thanks all

**Comment by RuthNjeri** [comment]
Hi @skilfullycurled 👋🏾 

You could add @Cadreia for the upcoming check-in (80) and @KarenEfereyan for the next one (81) 🎉 🎉

**Comment by cesswairimu** [comment]
Upcoming 
----------------

80th: @Cadreia 
81st: @KarenEfereyan 

Thanks @RuthNjeri

**Comment by KarenEfereyan** [comment]
Waow, I love this initiative by Public Lab. I am definitely going to go through all the previous checkins when I'm less busy. @cesswairimu when exactly is mine due?

**Comment by cesswairimu** [comment]
Next week's checkin @KarenEfereyan

**Comment by KarenEfereyan** [comment]
> Next week's checkin @KarenEfereyan

Yes ma'am

**Comment by tawahpeggy** [comment]
hello @all please i think there has been a mixup with adding recent checK-ins to the check-in list.
there is @RuthNjeri :Weekly Community Check-In # 79 - Draft Your Outreachy Proposal #8619
@Cadreia :[publiclab/plots2] Weekly Community Check-In #80 - Outreachy Application (Winter 2020) Ends Soon! (#8676)
@KarenEfereyan :[publiclab/plots2] Weekly Community Check-In #81 - Do That Which Scares you (#8709)
@tawahpeggy:  [publiclab/plots2] Weekly community Check-In #82-We Rise By Lifting Others! (#8719)
@skilfullycurled  @cess @jywarren  please help see into this

**Comment by jywarren** [comment]
Oh, are we off by one? I reformatted your comment to match the above format. Is that correct now, and shall I copy it up to the top? Thank you @tawahpeggy !!!

**Comment by jywarren** [comment]
OK, i changed it, how does it look up top now? Thanks again!!!

**Comment by tawahpeggy** [comment]
thanks for helping out @jywarren  theres still some mixup, Audrey and karen has same check-in Titles :smile: . is it possible for me to make the corrections instead of stressing you out over and over?

**Comment by KarenEfereyan** [comment]
> thanks for helping out @jywarren  theres still some mixup, Audrey and karen has same check-in Titles :smile: . is it possible for me to make the corrections instead of stressing you out over and over?

No we didnt. @Cadreia raised an issue around outrrachy applications coming to an end. Kindly refer to the issue numbers

**Comment by tawahpeggy** [comment]
yep @KarenEfereyan theres a mixup in the check-in list that needs to be corrected .your check-in title is same with @Cadreia

**Comment by cesswairimu** [comment]
My bad, updated that...Thanks everyone :heart:

**Comment by SidharthBansal** [comment]
I think it will be a great idea to move a new thread once 100 weekly Community Communications are completed. What do you suggest?

**Comment by pydevsg** [comment]
Yes, agreed with @SidharthBansal 😅

**Comment by cesswairimu** [comment]
That would be great @SidharthBansal  and @pydevsg...wow! we are 2 check-ins shy of 100 already!

Unpinning this issue for a while to pin the Outreachy welcome issue. Thanks all

**Comment by cesswairimu** [comment]
moving this to https://github.com/publiclab/plots2/issues/9600 thanks everyone :heart:
