### ISSUE TITLE
Stats Page Query Bug

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5917]
Hi all,

We are having trouble with queries in the stats page for some of data for year 2013. This is a planning issue for going about solving that and also removing spam users on the site 

Issues:
- [ ] Stats downloading returns "Page does not exist" for dates prior to early 2013 #5490 
- [ ] Stats Download And Site Overload #5524 

Affects:
- [ ] Add 'all time' option for stats #5904 

Affected by/related to:
- [ ] Spam account detection/reduction planning #5450

@skilfullycurled and anyone else feel free to edit

**Comment by skilfullycurled** [comment]
Thanks opening the discussion @cesswairimu.

Preface: not sure the best practices of using usernames so I'm including the UID.  Seems like it'd be okay considering people's usernames are public info, but just being cautious. 

In any case.

I have some very strange news to report, not sure if it's what's causing the 4/23/13 issue but there were four people who created accounts on that day.  For these users, if you go directly to their profile page by entering the username manually into the correct route (.../profile/username), all of their profiles work and none of them appear to be spam.

However! 

_Only one of those four users (UID 1205) has actually posted any content._

So what?

Here's where it gets weird.  If you search for all of the users, search works fine for everyone except the user _with_ the content (UID 1205) returns a "There was an error. Are you sure you have the right address?" page (this is our version of a 404, no?).

**Comment by jywarren** [comment]
Hi, just to help with debugging, I think it's OK to share this username because it is indeed public already and I actually know them: https://publiclab.org/profile/dorncox

How are you searching for their username? Using https://publiclab.org/api/srch/profiles?query=dorncox ? which for me works without an error?

**Comment by skilfullycurled** [comment]
Just putting the name dorncox in the search bar.

**Comment by skilfullycurled** [comment]
Just looked at your update in #5490. This seems unrelated now, although I guess that's still in progress.  Who knows, might be the linchpin of the entire memory leak!  : P

**Comment by jywarren** [comment]
Ah, well the navbar search no longer searches for usernames, as we're in
the midst of a major rework of search systems:
https://github.com/publiclab/plots2/issues/5708
https://github.com/publiclab/plots2/pull/5824. But I think i found some
related issues in #5490

**Comment by skilfullycurled** [comment]
Okay, for what it's worth to debugging those issues, the other names at least say that nothing was found.  In the meantime, please give my apologies to dorncox.  Mistakes were made.  I hold a press conference to officially apologize and make a correction in tomorrows paper.

**Comment by jywarren** [comment]
Dorn is a farmer of good humor and grace and you're surely not on his wrong
side :-)
