### ISSUE TITLE
[WIP]GCI 2019 Task List

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6239]
Please add pending issues from #3276

An uploaded task has a tick in the tasklist whereas not - uploaded task does not have a tick in the tasklist but is present in the tasklist.

## Code: writing or refactoring

- [ ] complete 'sortable headers' implementation following pattern in #2352
- [ ] additional work on the Checklists system: #2452
- [ ] calculate "answered" rate for questions posted in a certain time period (described in #2120)
- [ ] display if someone's been banned or is still active in moderator emails (https://github.com/publiclab/plots2/blob/master/app/views/admin_mailer/notify_node_moderators.html.erb) using the SVG at the above URL so moderators can tell if something's already been moderated without opening a link -- issue at #3338
- [ ] Standardize display of n Wiki and m Research Notes #2193
- [X] Code Refactoring for capture.js (https://github.com/publiclab/spectral-workbench.js/issues/141)
- [ ] Remove "scroll to top" arrow key https://github.com/publiclab/plots2/issues/6435
- [ ] Get capture.js subfiles compiling into a single file using Grunt(https://github.com/publiclab/spectral-workbench.js/issues/151)

## Design: graphic design or user interface design

- [ ] BIG TASK: Wiki page should be rendered on same page. On clicking on wiki pages nav bar on /notes/popular a new page opens up. But wiki pages should be rendered under the wiki nav bar. #3456

# IS
#### Quality Assurance: testing and ensuring code is of high quality
- [ ] CodeClimate smells linked to IS's code climate: https://codeclimate.com/github/publiclab/image-sequencer

#### Code 
- [ ] Feature to get input image from URL https://github.com/publiclab/image-sequencer/issues/1241
# LBL
#### Quality Assurance: testing and ensuring code is of high quality
- [ ] CodeClimate smells linked to LBL's code climate: https://codeclimate.com/github/publiclab/leaflet-blurred-location

# LDI 
- [x] Install LDI on local machine (these are published on dashboard already for all other repos) B -- GCI dashboard
#### Coding
- [x] Write a `#replaceTool` method [#6793](https://github.com/publiclab/Leaflet.DistortableImage/issues/367) M -- GCI dashboard
- [x] Disable mouse pointer on disabled images [#382](https://github.com/publiclab/Leaflet.DistortableImage/issues/382) M -- GCI dashboard
- [x] Image handles still active when hidden [#429](https://github.com/publiclab/Leaflet.DistortableImage/issues/429) B -- GCI dashboard
- [x] Remove try...catch from _addToolbar [#383](https://github.com/publiclab/Leaflet.DistortableImage/issues/383) B -- GCI dashboard
- [ ] Expose toolbar "action" methods [Leaflet.DistortableImage] https://github.com/publiclab/Leaflet.DistortableImage/issues/268 H
- [x] Expose degrees of rotation of the overlay (image) layer [Leaflet.DistortableImage] https://github.com/publiclab/Leaflet.DistortableImage/issues/102 H -- GCI dashboard
- [x] Set degrees of rotation of the overlay (image) layer [Leaflet.DistortableImage] https://github.com/publiclab/Leaflet.DistortableImage/issues/102 H -- GCI dashboard
- [x] Implement (and expose) Image Selection Event Listeners https://github.com/publiclab/Leaflet.DistortableImage/issues/460 H -- GCI dashboard
- [ ] Implement (and expose) Image Deselection Event Listeners https://github.com/publiclab/Leaflet.DistortableImage/issues/460 H
- [ ] Difficulty moving images at high zoom levels https://github.com/publiclab/Leaflet.DistortableImage/issues/466 M
- [ ] Option to change strings https://github.com/publiclab/Leaflet.DistortableImage/issues/406 M
- [x] Add meaningful return values for toolbar manipulation methods
[#469](https://github.com/publiclab/Leaflet.DistortableImage/issues/469) M -- GCI dashboard
- [x] use `#replaceTool` method in MapKnitter [#6793](https://github.com/publiclab/Leaflet.DistortableImage/issues/367) M -- GCI dashboard
- [x] Remove spinner after an export is complete [#470](https://github.com/publiclab/Leaflet.DistortableImage/issues/470) H -- GCI dashboard
- [x] Add a `#cancelExport` method
[#479](https://github.com/publiclab/Leaflet.DistortableImage/issues/479) H -- GCI dashboard
- [x] feature: arrow-key placement [#338](https://github.com/publiclab/Leaflet.DistortableImage/issues/338) H 
- [x] Make collection export option dynamic [#522](https://github.com/publiclab/Leaflet.DistortableImage/issues/522) H
- [x] Scaling relative to corner [#403](https://github.com/publiclab/Leaflet.DistortableImage/issues/403) H

#### Design
- [ ] Display Bootstrap-like tooltips for menu items #104 B

#### Documentation/training
- [x] Add code of conduct badge to readme [#465](https://github.com/publiclab/Leaflet.DistortableImage/issues/465) B -- GCI dashboard
- [x] Write a test demonstrating how `#_calculateProjectiveTransform` works [#484](https://github.com/publiclab/Leaflet.DistortableImage/issues/484) H -- GCI dashboard

#### Quality Assurance
- [ ] Cleaning Up! #397 B
- [ ] Making sure the toolbar stays in viewport during image drags on zooming in M

# MapKnitter
#### Code
- [x] Update initializers to class factory syntax [#888](https://github.com/publiclab/mapknitter/issues/888) B -- GCI dashboard
#### Outreach/Research
- [x] Research and document anonymous editing and the purpose of MK (https://github.com/publiclab/mapknitter/issues/1021) H -- GCI dashboard

#### Quality Assurance: testing and ensuring code is of high quality
- [ ] CodeClimate smells linked to MK's code climate - https://codeclimate.com/github/publiclab/mapknitter

# Plots2
#### Quality Assurance: testing and ensuring code is of high quality
- [ ] CodeClimate smells linked to plots2's code climate: Read through Code Climate "smells" and open issues related to solving them with code links included and recommendations: https://codeclimate.com/github/publiclab/plots2/issues?severity%5B%5D=critical&severity%5B%5D=major&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication (described in #3706) 
- [x] Fix pluralization logic III #6810 B -- GCI dashboard
- [x] Fix pluralization logic IV #6827 M -- GCI dashboard
- [x] Expand use of x icon for tags #6849 B  -- GCI dashboard

# PublicLab.Editor
- [ ] Toggling to rich text mode using shortcut key, disables the button https://github.com/publiclab/PublicLab.Editor/issues/341 M

# simple-data-grapher
#### Quality Assurance: 
- [ ] Setup Travis CI in the project https://github.com/publiclab/simple-data-grapher/issues/98

#### Code: writing or refactoring: 
- [ ] Remove unnecessary console.log statements https://github.com/publiclab/simple-data-grapher/issues/97
# SWB
#### Quality Assurance: testing and ensuring code is of high quality
- [ ] CodeClimate smells linked to SWB's code climate: https://codeclimate.com/github/publiclab/spectral-workbench
- [X] Make Graph div responsive (https://github.com/publiclab/spectral-workbench.js/issues/110)  -- GCI dashboard

#### Outreach/Research
- [x] Update Issue Template for spectral-workbench.js (https://github.com/publiclab/spectral-workbench.js/issues/129) -- GCI dashboard

#### Coding
- [ ] Auto-stretch for webcam NDVI https://github.com/publiclab/infragram/issues/90 H
- [ ] Pivot to a "full-height/width mode" (all devices) https://github.com/publiclab/infragram/issues/92 H
#### Design
- [ ] "Start by uploading an image source" popover on false localStorage flag https://github.com/publiclab/infragram/issues/89 M
- [ ] Eliminate Bootstrap to increase load times (and redesign landing page in plain HTML) https://github.com/publiclab/infragram/issues/91 H

#### Supportive Tasks / Outreach/Research
- [x] Suggest new changes & Report Bugs (described in #3460) -- GCI dashboard
- [x] Create a welcoming "first-timers-only" issue to invite new software contributors -- GCI dashboard
- [x] Help add code links to existing issues (described in #3424)  -- GCI dashboard
- [x] Add screenshots or GIFs to open pull requests to illustrate new features (described in #3513)

Refer: https://github.com/publiclab/plots2/wiki/Supportive-Tasks

## WIP
- [ ] When a person submits an empty sign up form, error should also come that the fields are empty #3340 - NEEDS CODE LINKS 
- [ ]  #2151 - Fix "Show 0 more" on inline people lists - Personally (@sashadev-sky ) I do not understand what this issue is asking for. Can @SidharthBansal fix it or message me to try and explain so I can fix it? It also has 2 pending PRs which need to be looked at and closed if they are not relevant
- [ ] [multiple-user]Copy welcomebot and first-timers-only templates into other projects - #3681 --  pending to discuss if we want to move forward with issues such as these
- [ ] https://github.com/publiclab/plots2/issues/6297#issuecomment-531892595 Turn this into a GCI worthy task
- [ ] https://github.com/publiclab/plots2/issues/6230 Make note/comment email titles match so they are threaded together
- [ ] this needs breaking up, but could provide some nice FTOs: https://github.com/publiclab/plots2/issues/2378 - cleaning/redesigning the digest page

**Comment by SidharthBansal** [comment]
Please edit the issue body itself

**Comment by sashadev-sky** [comment]
@SidharthBansal going through them today! not sure well find that many (a lot of them are completed just not checked off or stale) but I will port any usable ones over here :)

**Comment by SidharthBansal** [comment]
Great thanks

**Comment by sidntrivedi012** [comment]
## Code: writing or refactoring

- [ ] complete 'sortable headers' implementation following pattern in #2352
- [ ] additional work on the Checklists system: #2452
- [ ] calculate "answered" rate for questions posted in a certain time period (described in #2120)
- [ ] display if someone's been banned or is still active in moderator emails (https://github.com/publiclab/plots2/blob/master/app/views/admin_mailer/notify_node_moderators.html.erb) using the SVG at the above URL so moderators can tell if something's already been moderated without opening a link -- issue at #3338
- [ ] Use of common functions in /maps page : #3316
- [ ] Standardize display of n Wiki and m Research Notes #2193
- [ ] When a person submits an empty sign up form, error should also come that the fields are empty #3340 -- GCI dashboard
- [ ] Test for the the above task

## Outreach/Research: community management, marketing, or studying problems and recommending solutions

- [ ] Reporting Bugs on PL /Reporting Suggestions #3460 -- GCI dashboard
- [ ] Help add code links to existing issues (described in #3424) -- GCI dashborad

## Quality Assurance: testing and ensuring code is of high quality

- [ ]  #2151 - Fix "Show 0 more" on inline people lists
- [ ] Read through Code Climate "smells" and open issues related to solving them with code links included and recommendations: https://codeclimate.com/github/publiclab/plots2/issues?severity%5B%5D=critical&severity%5B%5D=major&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication (described in #3706) -- GCI dashboard.

## Design: graphic design or user interface design

- [ ] BIG TASK: Wiki page should be rendered on same page. On clicking on wiki pages nav bar on /notes/popular a new page opens up. But wiki pages should be rendered under the wiki nav bar. #3456
- [ ] [multiple-user]Copy welcomebot and first-timers-only templates into other projects - #3681 -- GCI dashboard

**Comment by sidntrivedi012** [comment]
@SidharthBansal Have added the tasks from #3276 which have an issue open for them and is currently open too. PTAL. Thanks.

**Comment by sashadev-sky** [comment]
@sidntrivedi012 thanks :) moved your tasks into the issue body and hid your comment

**Comment by SidharthBansal** [comment]
Yeah great work.

**Comment by SidharthBansal** [comment]
*POINTS TO REMEMBER WHILE WRITING ISSUES IN ISSUE LIST*
1. The task should be unclaimed and unsolved.
2. Please provide a proper subjective title in the above list with reference to the issue number.
3. Please use Keywords ``GCI Dashboard`` when it is published on the GCI Dashboard(Future work).
4. Please have explanatory issues.
5. Please tag the issues with `gci-candidate` label. Please mark `easy`, `medium` and `hard` category. (Scores will be decided later. We are still discussing scoring system rules and regulations.)
6. Please have the following on each GCI issue.
`` We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more``
This means we are reserving issues for GCI folks. So please redirect new comers to other issues if they are not participating in GCI.
7. Edit above list ONLY.
8. When you upload the GCI task on the GCI dashboard(in near future) please do following two things:
8.1 Comment `` Uploaded on GCI dashboard``under respective issue.
8.2 Update the above list too.

Please feel free to update these guidelines. We are having a better mentoring team this year. :+1:

**Comment by oorjitchowdhary** [comment]
From last year's experience, I mainly faced problems in understanding the task/issue when reading on the GCI dashboard as it wasn't properly stated what's to be done, and also I think we should add a link to the respective files found in the codebase to fix the error, and the issue # on GitHub on the GCI task description itself.

**Comment by SidharthBansal** [comment]
Sure! Nice suggestion!

**Comment by debck** [comment]
Hello @sashadev-sky  I think we can add these to the task list too https://github.com/publiclab/plots2/issues/3534 , https://github.com/publiclab/plots2/issues/5181

**Comment by sashadev-sky** [comment]
@debck I updated #3534 to #6297 which is now at the bottom of this page. would you want to check out #5181 confirm its what needs to be done, rewrite and add to list?

**Comment by debck** [comment]
Yes, it is a good fto issue. So, I think it should be added to the list.

**Comment by SidharthBansal** [comment]
Debasish go ahead. Please don't forget to add labels and link it over here.
Thanks

**Comment by pydevsg** [comment]
Can I refer some issues for GCI, @SidharthBansal . I am willing to mentor GCI this year.

**Comment by SidharthBansal** [comment]
Yeah sure.
Go ahead!

**Comment by ananyaarun** [comment]
Hey everyone, I have noticed a few issues on the GCI tasks dashboard, (basically tasks reserved for GCI) already have PR's by non GCI candidates. These are mainly issues labeled both as GCI candidate and First time issues.

I think we should be more specific while creating issues and let people know if an issue is reserved for GCI before they claim and open a PR. This would cause a lot of confusion to GCI students, if they claim a task officially and it has a PR made.

Thanks!

**Comment by SidharthBansal** [comment]
We need to ensure that the ftos reserved by gci have a tagline `Reserved
for GCI` as we did last year.
Mentors need to ensure non gci folks don't solve gci issues.
We need to be alert.
Thanks Ananya for bringing this to our attention.

**Comment by SidharthBansal** [comment]
Please add checks in the checkboxes that are complete!

**Comment by sashadev-sky** [comment]
@SidharthBansal why does it say Read through Code Climate "smells", Suggest new changes & Report Bugs (described in #3460), and Help add code links to existing issues (described in #3424) are published on GCI dashboard (what I think is indicated by "-- gci dashboard") but they are not? Did we decide to delete them for some reason? Were we planning to do google forms for these or something?

**Comment by SidharthBansal** [comment]
Please edit it as it is copied from last year. Thanks

**Comment by sashadev-sky** [comment]
@SidharthBansal cool ill fix them up and add them later today!

**Comment by SidharthBansal** [comment]
That will be awesome, thank you

**Comment by sashadev-sky** [comment]
@SidharthBansal what would be awesome? I was asking which we were doing lol

**Comment by SidharthBansal** [comment]
I am sorry, I actually didn't receive any image on my Gmail and replied to you without the image.
Apologies.

**Comment by SidharthBansal** [comment]
I have updated the guidelines. Mentors are requested to re-read it!
@ananyaarun @IshaGupta18 @Divy123 @jywarren @debck @gauravano @sagarpreet-chadha etc.

**Comment by sashadev-sky** [comment]
all supportive tasks uploaded to GCI dashboard! 2 still pending publish

**Comment by SidharthBansal** [comment]
Thanks

**Comment by VladimirMikulic** [comment]
@keshav234156 @SidharthBansal are we allowed to solve these issue before they are uploaded to the GCI dashboard or do we have to wait for them to be uploaded? Thanks.

**Comment by sashadev-sky** [comment]
@VladimirMikulic I responded in gitter but pasting here as well -  

> i will try to add some GCI tasks this weekend!!
> 
> Sasha Boginsky @sashadev-sky 02:25
> if you guys see an open issue and are interested in solving it - I am not opposed to you commenting that and i'll get it uploaded to the dashboard quickly / assign it the difficulty level. Otherwise most tasks take me a bit of time to write

**Comment by SidharthBansal** [comment]
You can solve it. Once merged we will upload it to the dashboard
If we forget to upload due to some reason then I am there to consider
points for that task
No worries

**Comment by SidharthBansal** [comment]
@CodeSarthak kindly get it approved https://codein.withgoogle.com/dashboard/tasks/5689351694974976/

**Comment by SidharthBansal** [comment]
@VladimirMikulic @Uzay-G are you willing to refactor this folks?

**Comment by SidharthBansal** [comment]
Open up a new issue with ONLY changes that are needed.
You can do it after 30 January whenever you are free and if you want to do.
By 30th January we will submit the GCI results. 🚀 
To be fair, we decided cool down period for this week. 👍

**Comment by VladimirMikulic** [comment]
Of course @SidharthBansal.
If I understand you correctly, you want us to finish the unsolved issues?

**Comment by Uzay-G** [comment]
No I think he wants us to open a new reactors issues with potential tasks
for the next gci. I'd love to work on it :+1:

**Comment by SidharthBansal** [comment]
I think it will be great to refactor the list as @Uzay-G said before finishing this list @VladimirMikulic 
I know you are really interested to close all the above issues. But I will not allow you to work for some days 🎉 You all should relax and enjoy. You all did a great job!

**Comment by Uzay-G** [comment]
Hey @SidharthBansal I am working on refactoring this now and I had a question. I think it would be useful to just group tasks by type (design, code, outreach) instead of by repository. What do you think?

**Comment by SidharthBansal** [comment]
Idea accepted. Great thinking
Thanks

**Comment by Uzay-G** [comment]
Refactored in #7408
