### ISSUE TITLE
Making FTO issues from translation function

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6579]
Here's a list of all the template files that have the t(...) function. They all need to be changed into translation(...). They are great for first-time-only issues! Just mark it off or leave a comment so we can mark it off to keep track.

- [x] app/views/comments/_comments.html.erb #6549  #6550 
- [x] app/views/comments/_edit.html.erb #6547  #6548
- [ ] app/views/comments/_form.html.erb
- [ ] app/views/dashboard/_activity.html.erb
- [ ] app/views/dashboard/_comment_moderate.html.erb
- [ ] app/views/dashboard/_header.html.erb
- [ ] app/views/dashboard/_node_comment.html.erb
- [x] app/views/dashboard/_comment_moderate.html.erb #6551 
- [ ] app/views/dashboard/_node_meta.html.erb
- [ ] app/views/dashboard/_node_moderate.html.erb
- [ ] app/views/dashboard/_node_question.html.erb
- [ ] app/views/dashboard/_node_wiki.html.erb
- [ ] app/views/dashboard/_wiki.html.erb
- [ ] app/views/dashboard/dashboard.html.erb
- [ ] app/views/grids/_thumbnail.html.erb
- [ ] app/views/grids/_wikis.html.erb
- [ ] app/views/home/subscriptions.html.erb
- [ ] app/views/layouts/_alerts.html.erb
- [ ] app/views/layouts/application.html.erb
- [ ] app/views/like/index.html.erb
- [ ] app/views/notes/_coauthored_notes.html.erb
- [ ] app/views/notes/_comment.html.erb
- [ ] app/views/notes/_comments.html.erb
- [ ] app/views/notes/_draft_notes.html.erb
- [ ] app/views/notes/_notes.html.erb
- [ ] app/views/notes/_responses.html.erb
- [ ] app/views/notes/_tagged_notes.html.erb
- [ ] app/views/notes/index.html.erb
- [ ] app/views/notes/show.html.erb
- [ ] app/views/notes/tools_places.html.erb
- [ ] app/views/questions/_new_question.html.erb
- [ ] app/views/search/profiles.html.erb
- [ ] app/views/sidebar/_author.html.erb
- [ ] app/views/sidebar/_dasbhoard.html.erb
- [ ] app/views/sidebar/_events.html.erb
- [ ] app/views/sidebar/_list.html.erb
- [ ] app/views/sidebar/_notes.html.erb
- [ ] app/views/sidebar/_post_button.html.erb
- [ ] app/views/sidebar/_related.html.erb
- [ ] app/views/sidebar/_wikis.html.erb
- [ ] app/views/stats/_range.html.erb
- [ ] app/views/stats/index.html.erb
- [ ] app/views/tag/_contributors.html.erb
- [ ] app/views/tag/_form.html.erb
- [ ] app/views/tag/_profileCard.html.erb
- [ ] app/views/tag/_topicCard.html.erb
- [ ] app/views/tag/blog.html.erb
- [ ] app/views/tag/contributors.html.erb
- [ ] app/views/tag/index.html.erb
- [ ] app/views/tag/show.html.erb
- [ ] app/views/tag/show/_contributors.html.erb
- [ ] app/views/tag/show/_nav_tabs.html.erb
- [ ] app/views/tag/show/_tab_content.html.erb
- [ ] app/views/tag/show/_user_controls.html.erb
- [ ] app/views/talk/show.html.erb
- [ ] app/views/user_sessions/_form.html.erb
- [ ] app/views/user_tags/index.html.erb
- [ ] app/views/users/_create_form.html.erb
- [ ] app/views/users/_edit_form.html.erb
- [ ] app/views/users/_likes.html.erb
- [ ] app/views/users/_photo.html.erb
- [x] app/views/users/_spamaway.html.erb #6542
- [x] app/views/users/edit.html.erb #6541
- [ ] app/views/users/likes.html.erb
- [ ] app/views/users/list.html.erb
- [ ] app/views/users/map.html.erb
- [x] app/views/users/new.html.erb #6539 
- [ ] app/views/users/profile.html.erb
- [ ] app/views/users/reset.html.erb
- [ ] app/views/wiki/_header.html.erb
- [ ] app/views/wiki/_wikis.html.erb
- [ ] app/views/wiki/edit.html.erb
- [ ] app/views/wiki/index.html.erb
- [x] app/views/wiki/methods.html.erb #6540
- [ ] app/views/wiki/revisions.html.erb

**Comment by stefanosu** [comment]
Hey, @nstjean is this still available to work on??

**Comment by jaywahr** [comment]
@nstjean please assign any issue to me. I will help out 😃

**Comment by nstjean** [comment]
Hi @stefanosu and @jaywahr ! I added a note to the post with some info!

**Comment by swathi-0901** [comment]
Hey I made an issue regarding wiki/_wikis to change the t to translation [#6704 ](https://github.com/publiclab/plots2/issues/6704)

**Comment by nstjean** [comment]
@swathi-0901 Thanks! I've updated the list.

I also noticed that an issue for dashboard/_wiki was opened #6701 so I've updated that one too.

**Comment by nitish81299** [comment]
@nstjean 
I've opened the issue for `dashboard/dashboard.html.erb` have a look #6721

**Comment by Abhinav1299** [comment]
@nstjean 
I have opened the issue for `layouts/_alerts.html.erb` #6727

**Comment by gptshubham595** [comment]
I have opened the issue for app/views/sidebar/_author.html.erb #6730

**Comment by swathi-0901** [comment]
Another issue was opened for app/views/grids/_thumbnail [#6736 ](https://github.com/publiclab/plots2/issues/6736)

**Comment by Utiwari1999** [comment]
@nstjean I have opened the issue for layouts/application.html.erb have a look at #6734

**Comment by coder-cracker** [comment]
@nstjean I have opened the issue for like/index.html.erb have a look at #6728

**Comment by nstjean** [comment]
@nitish81299 @Abhinav1299 @gptshubham595 @swathi-0901 @Utiwari1999 @coder-cracker Thank you all! I've updated the list.

**Comment by Sakku9009** [comment]
I have opened the issue for wiki/_wikis.html.erb have a look at #6738

**Comment by gptshubham595** [comment]
@nstjean I have opened 

app/views/notes/_coauthored_notes.html.erb #6754 
 app/views/notes/_comment.html.erb #6755 
 app/views/notes/_comments.html.erb #6756

**Comment by nstjean** [comment]
@Sakku9009 Thanks for helping! There is already an issue open for wiki/_wikis.html.erb, please make sure you check the list. You can do any of the open ones.

Thanks @gptshubham595 I've updated the list.

**Comment by govindgoel** [comment]
Hey I made an issue regarding app/views/users/_likes.html.erb to change the t to translation #6880

**Comment by govindgoel** [comment]
@nstjean  Another issue I opened regarding t to translation in app/views/talk/_show.html.erb #6881

**Comment by nstjean** [comment]
@govindgoel Great! I'll add them to my list!

**Comment by nstjean** [comment]
Here is a list of first-time-issues that are still open for someone to complete!

- app/views/dashboard/_activity.html.erb #6597 open
- app/views/dashboard/_comment_moderate.html.erb #6598 open
- app/views/layouts/_alerts.html.erb #6727 open
- app/views/layouts/application.html.erb #6734 open
- app/views/notes/_coauthored_notes.html.erb #6754 open
- app/views/notes/_comments.html.erb #6756 open
- app/views/sidebar/_author.html.erb #6730 open
- app/views/wiki/_wikis.html.erb #6704 open

**Comment by nstjean** [comment]
@jywarren @SidharthBansal I've updated the list above with which are open, merged, or needing attention.

**Comment by SidharthBansal** [comment]
Oh great!Pinging @cesswairimu

**Comment by govindgoel** [comment]
@nstjean Another fto #7347

**Comment by NitinBhasneria** [comment]
@nstjean another fto #7456

**Comment by NitinBhasneria** [comment]
@nstjean  new FTO #7490 and #7475

**Comment by sssash18** [comment]
@nstjean Made new fto #7493

**Comment by sssash18** [comment]
@nstjean Made new ftos #7538, #7537

**Comment by sssash18** [comment]
New ftos #7627

**Comment by Tlazypanda** [comment]
New ftos #7636 #7637 @nstjean

**Comment by Tlazypanda** [comment]
New ftos #7655 #7654 #7653 @nstjean

**Comment by sssash18** [comment]
New ftos #7664 , #7665

**Comment by Tlazypanda** [comment]
New ftos #7688 #7689 #7690 #7691

**Comment by govindgoel** [comment]
New fto #7721

**Comment by jywarren** [comment]
Hi all, thank you SO MUCH -- i just referenced this when noting there may have been some issues with the string parsing done here. I don't know if you have any availability to help us figure this out? Thanks again for your great work! https://github.com/publiclab/plots2/issues/7798

I think possibly we need some more careful checking before merging these, and I included in #7798 a URL for turning translations on locally so that people can do this. Any help appreciated!!!
