### ISSUE TITLE
Planning issue for 2019-20 geographic features work

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6801]
A lot of projects are coming together for the 2019-20 Outreachy session, and I wanted to start organizing and collecting them up here. Not all are fully fleshed out but we're trying to break these into small tasks. Please ask questions, and if you do manage to break them out, link out to them and we'll check them off as we go!

Note this will be the lead organizing issue for the [Geographic Features milestone](https://github.com/publiclab/plots2/milestone/7).

### Tasks

Let's organize this list as we go... but initially i'll just add a lot. cc @cesswairimu @sagarpreet-chadha @SidharthBansal @publiclab/reviewers

* [x] is there a way to preserve the /zoom/ of the map in the /post button from an inline map? Maybe we need that zoom tag? Or should it use the number of digits the same way the shortcode does?
https://github.com/publiclab/plots2/issues/6804
* [x] add a `zoom:9` override tag for map zoom
* [x] get popups showing title, link for each wiki, note, and question
* [x] add “Add a location” button to un-geotagged wikis/notes where “View map” would have appeared (#6876)
~* [ ] add "Places" or "Regions" (/map) to the navbar as in #1621~
* [x] redirect /maps to /map, leave /archive as archive

#### /map related work

https://publiclab.org/map/gulf-coast#6/30/-90

Moving these to track in https://github.com/publiclab/plots2/issues/6993 :

* [x] Make `/map/_wiki_slug_` routes that source lat/lon/zoom from matching wiki page
* [x] get permalinks on `/map/_wiki_slug_#zoom/lat/lon` pages as you drag
* [ ] get notes, wikis, and people all showing on `/map/SLUG` pages (these work except people have some bugs)
* [x] make “#” link in grey appear on wiki page popups that show `/map/SLUG` permalinks
* [x] add “View map” button to geotagged page sidebars, opening `/map/SLUG` for wikis, and `/map#zoom/lat/lon` permalink for notes
* [x] add a “Add to map +” button on `/map/…` pages to add a note, question or wiki at that location (go to a selection page between these options, at `/post/choose?tags=lat:10,lon:10` -- preserving params!)

### Later

Lower priority!

* [ ] wiki powertag like “layers:a,b,c” to set default visible layers on /map/sentinel, and on top-of-page maps
* [ ] figure out how to set text of prompt button? (maybe -- currently it's "Add your story" but it could just be "Add +" or "Post +"?)

**Comment by sagarpreet-chadha** [comment]
`is there a way to preserve the /zoom/ of the map in the /post button from an inline map? Maybe we need that zoom tag? Or should it use the number of digits the same way the shortcode does?`

-> we need to pass zoom also along with lat and lon, we need to change in **PL.editor** also to consume zoom level.

**Comment by jywarren** [comment]
This is looking great. Sagarpreet, can you offer an update on this so far? Thanks!

**Comment by SidharthBansal** [comment]
@jywarren @sagarpreet-chadha can we create some minor projects from the above list as hall of fame tasks for GCI?
This way we can get small projects completed in GCI and can keep big projects for outreachy or gsoc.

**Comment by sagarpreet-chadha** [comment]
Yes great idea!

**Comment by NitinBhasneria** [comment]
@gptshubham595 @SidharthBansal I would like to work on this issue.

**Comment by SidharthBansal** [comment]
Oh great.
Coordinate with Sagar and Cess on this

**Comment by NitinBhasneria** [comment]
@sagarpreet-chadha @cesswairimu Can I work?

**Comment by cesswairimu** [comment]
Hey @NitinBhasneria, thank you for the interest...This a planning issue and most of the issues discussed are in progress/assigned to other collaborators..let me know if you need help finding another issue. Thanks

**Comment by NitinBhasneria** [comment]
Yea @cesswairimu If you have some issues for me pls suggest.

**Comment by jywarren** [comment]
Closing this as I believe these are all complete! Thanks, all!
