### ISSUE TITLE
Follow-up tasks for new /map... route

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6993]
@sagarpreet-chadha updated us that:

> I had implemented a new route /map (https://github.com/publiclab/plots2/pull/6874) with a full screen map with URL Hash implemented. Check this link:

https://publiclab.org/map/mapknitter#lat=60.23981116999893&lon=5.976562500000001&zoom=4

It looks great!

![image](https://user-images.githubusercontent.com/24359/71008012-e9afbf80-20b5-11ea-91ca-b0d840b95800.png)

Follow up tasks:

* [x] use CSS to hide the footer OR (maybe better) let's make the map 90% of window height, but fixed position, so you can scroll down to content lower on the page, since we may add some stuff there later. Not absolute-positioning it may naturally push the footer down. https://github.com/publiclab/plots2/issues/7047
* [x] There seems to be an error when we just go to https://publiclab.org/map with no layers specified - https://github.com/publiclab/plots2/issues/7045

Copied from https://github.com/publiclab/plots2/issues/6801

* [x] Make `/map/_wiki_slug_` routes that source lat/lon/zoom from matching wiki page #7061
* [x] get permalinks on `/map/_wiki_slug_#zoom/lat/lon` pages as you drag #7061
* [x] get notes, wikis, and people all showing on `/map/SLUG` pages
* [x] make “#” link in grey appear on wiki page popups that show `/map/SLUG` permalinks
* [x] add “View map” button to geotagged page sidebars, opening `/map/SLUG` for wikis, and `/map#zoom/lat/lon` permalink for notes #7061
* [x] add a “Add to map +” button on `/map/…` pages to add a note, question or wiki at that location (go to a selection page between these options, at `/post/choose?tags=lat:10,lon:10` -- preserving params!)

![image](https://user-images.githubusercontent.com/24359/71007382-e831c780-20b4-11ea-948c-55d8020df0dd.png)

**Comment by jywarren** [comment]
A couple notes that may be helpful to @nstjean @sagarpreet-chadha @crisner --

https://github.com/publiclab/plots2/blob/570a3bb96ef0c467f9ddd582e0e6b177c2e6703f/app/assets/stylesheets/style.css#L545-L561

These styles can bust out of the Bootstrap margins to become full-width, when applied to divs in the main content column. I used them in https://publiclab.org/wiki/inline-maps and they work on mobile too!

For the `View on a map` buttons, we can use the same style buttons as the "Add a location" buttons:

![image](https://user-images.githubusercontent.com/24359/71009151-c2f28880-20b7-11ea-8c2e-18a3a9ab3456.png)

But with this nice "map" icon maybe? `<i class="fa fa-map" aria-hidden="true"></i>`

![image](https://user-images.githubusercontent.com/24359/71009167-ca199680-20b7-11ea-9813-ab535b1a00c8.png)

and actually the same locations for those buttons - they should appear whenever there IS a location, so exactly the opposite condition from when the `Add a location` button appears. 

What do you think?

**Comment by nstjean** [comment]
It all looks good!

I like the thought of having the footer still exist below it, it has a lot of information in there and would allow the map page to feel like still part of the overall website.

For these two options:
> Make `/map/_wiki_slug_` routes that source `lat/lon/zoom` from matching wiki page
> get notes, wikis, and people all showing on `/map/SLUG` pages

How will the code decide if it's a wiki page or if it's supposed to grab all the notes/wikis/people for the slug? Should there be a route like `/map/tag/SLUG` to differentiate?

The "Add your location" button opens the popup modal, right?

Should the "view on a map" button have a red icon as well, or just the default color?

**Comment by jywarren** [comment]
Ah, sorry - so, at `/map/_wiki_slug_`, it would look up the lat/lon from the corresponding wiki page; for `/map/providence` it would look for lat/lon at `/wiki/providence` for example. Then it would show the content/people for that location, just as the first maps on this page do (though they're missing people; we need to sort that out in #3090): https://publiclab.org/wiki/inline-maps

Re "add your location" that's right!

The View on a map button could also have a red icon, i suppose, to match the Add location button?

Awesome!

**Comment by nstjean** [comment]
Excellent. :smile:

**Comment by nstjean** [comment]
@sagarpreet-chadha  @jywarren  What should happen if a wiki doesn't have a lat/lon? If it has a lat/lon and no zoom we can calculate zoom, but what if it doesn't have any location information?

And what should be the default for the page /map  when there is no lat/lon/zoom specified?

**Comment by jywarren** [comment]
If there's no coord info, we won't show the map button, and if someone
manually goes to that path, we can just display an alert that the page has
no location information, maybe?

As to the main /map/ page, we should default to user profile location and
fall back to a global map, I think, what do you think?

Thanks!

**Comment by nstjean** [comment]
Ok that sounds just fine!

**Comment by nstjean** [comment]
@jywarren `.inline-fullwidth-content` is not working on the /map/ page for some reason. So strange! This is what I get when I apply that class with no other width specificiations.
![FireShot Capture 130 - 🎈 Public Lab_ Map - localhost](https://user-images.githubusercontent.com/49460529/71488400-56ca0000-27ee-11ea-9d27-fd88bdd0d5f0.png)

**Comment by nstjean** [comment]
You can take a look here: https://github.com/publiclab/plots2/pull/7048

**Comment by nstjean** [comment]
@jywarren In your instructions you say `/map/_wiki_slug_#zoom/lat/lon` as the URL. But @sagarpreet-chadha had already implemented a URL hash in the format `/map/layernames#lat=6.3&lon=-10.7&zoom=11` Do you prefer that I keep what Sagarpreet has done and build around that format? Or do you want me to change it all to the format you initially described?

I'm working on these all as-is but I can change it if you want me to.

**Comment by jywarren** [comment]
Hi! Regarding the inline style, it's designed to work with the #content div
as in the wiki and note page templates, so perhaps your page is differently
structured?

Let's go with the shorter url I proposed! Just to ask, was layernames a
param or just a static string?

Thanks! Happy New Year!

**Comment by nstjean** [comment]
Yes it might be structured differently!

Ok, I'll change the hash! The layernames was set up as a route param. I think it would be better to add it to the end of the url as an optional string.

Happy new year!!

**Comment by nstjean** [comment]
I've checked off the items that are completed in the current PRs!

**Comment by nstjean** [comment]
@jywarren @sagarpreet-chadha I need some clarification on these items:

>  get notes, wikis, and people all showing on /map/SLUG pages
>  make “#” link in grey appear on wiki page popups that show /map/SLUG permalinks

And from #6801 
> get popups showing title, link for each wiki, note, and question

By popups you mean markers on the map with an info popup that shows up on hover or click? And for each wiki page map you want it showing **all** the data from the site, all notes, wikis and people?

**Comment by jywarren** [comment]
> get notes, wikis, and people all showing on /map/SLUG pages

Here, just wanting them to be like the map on this page, in that it shows site content, whether pages, notes, or people: https://publiclab.org/wiki/puerto-rico -- but I think we have to address this in https://github.com/publiclab/plots2/issues/3090

> make “#” link in grey appear on wiki page popups that show /map/SLUG permalinks

For this, I was thinking something like this:

![image](https://user-images.githubusercontent.com/24359/71694051-0c132f80-2d7c-11ea-87ef-9d47fdcc550e.png)

Very roughly (i'm sure we can make it look better) but where the `#` link is a permalink to the `/map/_slug_` URL for that node. Does that make sense?

Regarding popups, yeah, that's right! I think we can refine the popups that are shown a lot. The best thing would be if they appeared as they do on pages like this: https://publiclab.org/tag/water-quality

But as a map popup: 

![image](https://user-images.githubusercontent.com/24359/71694212-7b891f00-2d7c-11ea-8d72-77c45000f687.png)

You both have some excellent mockup/design skills. Would you like to try giving the popup design a go?

**Comment by nstjean** [comment]
Yeah sure! I'll do some designing!

**Comment by nstjean** [comment]
> get notes, wikis, and people all showing on /map/SLUG

Do we want notes, wikis and people showing on `/map/`? Or just `/map/wikislug/`?

**Comment by NitinBhasneria** [comment]
@jywarren If this issue is incomplete I would    
like to do try this .

**Comment by nstjean** [comment]
Hi @NitinBhasneria This is a project I am almost done with. :) Thanks for offering to help, though!

**Comment by jywarren** [comment]
> Do we want notes, wikis and people showing on /map/? Or just /map/wikislug/?

On both, thank you!

**Comment by jywarren** [comment]
I believe this is all complete! Closing!!!
