### ISSUE TITLE
[WIP] GCI 2020 Check List

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7408]
This is a staging area. Each task has (or will soon have) a link to a full issue including relevant lines of code, screenshots, and other helpful information as we prepare them for solving 

 # Coding

   * [ ]  complete 'sortable headers' implementation following pattern in #2352 **hard**
   * [ ]  additional work on the Checklists system: #2452 **easy**
   * [ ]  calculate "answered" rate for questions posted in a certain time period (described in #2120) **hard**
   * [ ]  Standardize display of n Wiki and m Research Notes #2193 **easy**
    * [ ]  Feature to get input image from URL [publiclab/image-sequencer#1241](https://github.com/publiclab/image-sequencer/issues/1241) **hard**
   * [ ]  Auto-stretch for webcam NDVI [publiclab/infragram#90](https://github.com/publiclab/infragram/issues/90) **hard**
 
   * [ ]  Pivot to a "full-height/width mode" (all devices) [publiclab/infragram#92](https://github.com/publiclab/infragram/issues/92) **hard**
  * [] Refactor search service code #6882 **medium**
 # Design: graphic design or user interface design
 
   * [ ]  BIG TASK: Wiki page should be rendered on same page. On clicking on wiki pages nav bar on /notes/popular a new page opens up. But wiki pages should be rendered under the wiki nav bar. #3456 **hard**
  * [ ] Powertagging the profile #5105 **hof** for all features
   * [ ]  "Start by uploading an image source" popover on false localStorage flag [publiclab/infragram#89](https://github.com/publiclab/infragram/issues/89) **medium**

   * [ ]  Eliminate Bootstrap to increase load times (and redesign landing page in plain HTML) [publiclab/infragram#91](https://github.com/publiclab/infragram/issues/91) **hard**

 # Quality Assurance: testing and ensuring code is of high quality
   * [ ]  CodeClimate smells linked to IS's code climate: https://codeclimate.com/github/publiclab/image-sequencer
   * [ ]  CodeClimate smells linked to LBL's code climate: https://codeclimate.com/github/publiclab/leaflet-blurred-location
   * [ ]  CodeClimate smells linked to MK's code climate - https://codeclimate.com/github/publiclab/mapknitter
    * [ ]  CodeClimate smells linked to plots2's code climate: Read through Code Climate "smells" and open issues related to solving them with code links included and recommendations: https://codeclimate.com/github/publiclab/plots2/issues?severity%5B%5D=critical&severity%5B%5D=major&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication (described in #3706)

   * [ ]  CodeClimate smells linked to SWB's code climate: https://codeclimate.com/github/publiclab/spectral-workbench
  * [ ]  Making sure the toolbar stays in viewport during image drags on zooming in M

 # Supportive Tasks / Outreach/Research
 
   * []  Suggest new changes & Report Bugs (described in #3460)
 
   * []  Create a welcoming "first-timers-only" issue to invite new software contributors
 
   * []  Help add code links to existing issues (described in #3424)
 
   * []  Add screenshots or GIFs to open pull requests to illustrate new features (described in #3513)
   * [] write a document explaining how to start contributing at Public Lab for RGSoc (needs own issue)
   * [] write documentation on how to open a Pull Request for first - timer contributor (needs own issue)
   * [] the table of contents on the github.com/publiclab/plots2 is inconsistent with the content present after it (needs own issue)
   * []  embed our welcome page in full at https://publiclab.org/code (needs own issue)
 
 Refer: https://github.com/publiclab/plots2/wiki/Supportive-Tasks
 ## WIP

   * [ ]   #2151 - Fix "Show 0 more" on inline people lists - Personally (@sashadev-sky ) I do not understand what this issue is asking for. Can @SidharthBansal fix it or message me to try and explain so I can fix it? It also has 2 pending PRs which need to be looked at and closed if they are not relevant

  * [ ]  Expand issue templates to other publiclab repositories #7141

  * [ ]  #6230 Make note/comment email titles match so they are threaded together

  * [ ]  this needs breaking up, but could provide some nice FTOs: #2378 - cleaning/redesigning the digest page

   * [ ]  Expose toolbar "action" methods [Leaflet.DistortableImage] [publiclab/Leaflet.DistortableImage#268](https://github.com/publiclab/Leaflet.DistortableImage/issues/268) H
   * [ ]  Implement (and expose) Image Deselection Event Listeners [publiclab/Leaflet.DistortableImage#460](https://github.com/publiclab/Leaflet.DistortableImage/issues/460) H

**Comment by SidharthBansal** [comment]
Please check the task. Check their availability. Categorize them as hard
medium etc.

**Comment by Uzay-G** [comment]
I have checked all for availabilty and will add difficulty

**Comment by SidharthBansal** [comment]
Please close previous two issues for task lists.
I will be less available for some days. Little busy with publishing
something. But will be happy to help intermittently. So expect delayed
replies.

**Comment by SidharthBansal** [comment]
Please ensure that separate issues are linked and/or made for each of them.
Also, let anyone do it. We need to refactor it again at time of GCI 2020

**Comment by SidharthBansal** [comment]
@Uzay-G any progress on this?

**Comment by SidharthBansal** [comment]
@Uzay-G

**Comment by Uzay-G** [comment]
@SidharthBansal should I create issues labeled `gci-candidate`?

**Comment by sashadev-sky** [comment]
Closing this don't need it now!
