### ISSUE TITLE
Update translation in notes show.html

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#7684]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

### TODO: 
On line https://github.com/publiclab/plots2/blob/master/app/views/notes/index.html.erb#L12 AND  https://github.com/publiclab/plots2/blob/master/app/views/notes/index.html.erb#L114, replace `raw t(` to `raw translation(`

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by guArroyo** [comment]
Hey, can i take this up as a contribution? :)

**Comment by cesswairimu** [comment]
Hi @guArroyo, yeah sure, go ahead

**Comment by cschweipert** [comment]
Hi @cesswairimu I would like to work in this. @guArroyo. Did you already make a pull request? Maybe I can I help out if you are stuck?

**Comment by cesswairimu** [comment]
@guArroyo  are you still working on this? If not please let @cschweipert know .

**Comment by mackenzieros** [comment]
Hello, if this is still available I would like to claim it!

**Comment by jywarren** [comment]
@mackenzieros you're welcome to take this up as it looks like nobody else is working on this! Thank you!

**Comment by mackenzieros** [comment]
@jywarren okay, claimed! Thank you.

**Comment by mackenzieros** [comment]
Looks like this issue has already been resolved.

**Comment by sarthak-choudhary** [comment]
hello, if this is available and not solved yet I would like to claim it.

**Comment by esiebomaj** [comment]
5th of june and this issue is still open 
lemme work on it 
@jywarren

**Comment by cesswairimu** [comment]
Hi @esiebomaj, we were having some trouble with changing the traslation...some were not picking up correctly on the live site..amybe we could hold this one for now...Feel free to claim https://github.com/publiclab/plots2/issues/8000 if you are looking for a fto...Thanks

**Comment by avats-dev** [comment]
@cesswairimu this was resolved by #7759 but it was not referenced in the PR, so this could be also closed. :+1: 
> Also @SidharthBansal have merged a lot of PRs which were not mentioning the issue concerned and hence left a lot of clutter, so might be good to avoid that in future. Just an observation :pleading_face:, no worries.

**Comment by cesswairimu** [comment]
Thanks @avats-dev,  seems like the PR reference the same PR and not an issue, sometimes its easy to miss that esp if you already know what the issue fixes. Closing this. Thanks
