### ISSUE TITLE
Update readme to match the new ruby version used

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8156]
### Please describe the problem (or idea)

The ruby version has been upgraded from 2.4.4 to 2.6.6 by #8145 we need to update the readme to reflect the change to ensure new contributors don't have an issue in setting up the project on their systems.

## Todo 
Update this file https://github.com/publiclab/plots2/blob/main/README.md change this part  under *Standard Installation* section from
```
You may need to first run bundle install if you have older gems in your environment from previous Rails work. If you get an error message like Your Ruby version is 2.x.x, but your Gemfile specified 2.4.4 then you need to install the ruby version 2.4.4 using rvm or rbenv.
Using rvm: rvm install 2.4.4 followed by rvm use 2.4.4
Using rbenv: rbenv install 2.4.4 followed by rbenv local 2.4.4
```
 to 
```
You may need to first run bundle install if you have older gems in your environment from previous Rails work. If you get an error message like Your Ruby version is 2.x.x, but your Gemfile specified 2.4.4 then you need to install the ruby version 2.6.6 using rvm or rbenv.
Using rvm: rvm install 2.6.6 followed by rvm use 2.6.6
Using rbenv: rbenv install 2.6.6 followed by rbenv local 2.6.6
````

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Tlazypanda** [comment]
@jywarren just confirming this change is final and won't be rolled back :sweat_smile:  also should we create an fto out of this?

**Comment by jywarren** [comment]
Good idea! I agree. I think that's a great idea!

**Comment by cesswairimu** [comment]
Great, thank you  both...converting this to an fto

**Comment by cesswairimu** [comment]
Hi @nsachin08, please feel free to claim this issue if you haven't gotten an fto yet. Thanks
