### ISSUE TITLE
Ensure formatting toolbars on comments appear in all variations

### ISSUE THREAD

**Issue by Sagarpreet** [publiclab/plots2#8475]
Quoting @jywarren from https://github.com/publiclab/PublicLab.Editor/issues/490#issuecomment-668635935

> basically, the comment editor sometimes shows a formatting bar (when it's for a question) but sometimes doesn't (for comments on non-questions). The actual toolbar code is here: https://github.com/publiclab/plots2/blob/bbfd7d4431ea7fbf36ab020015af0699606b3847/app/views/editor/_toolbar.html.erb

The other issue is that when submitting a comment, new comment forms are inserted with AJAX, and they may or may not have the toolbar. What we're looking for is for all comment boxes to have the toolbar, consistently. Let's move this all into its own issue and we can plan it out?

## TODO:

Make sure that toolbar is always there in comment editor in following scenarios:

- [ ] reply to comment
- [ ] comment just posted (form inserted via AJAX)
- [ ] reply to comment just posted
- [ ] editing existing comments
- [ ] editing comments just posted
- [ ] editing comment replies
- [ ] editing comment replies just posted

## Files where we may have to solve this:
1. https://github.com/publiclab/plots2/blob/bbfd7d4431ea7fbf36ab020015af0699606b3847/app/views/editor/_toolbar.html.erb
2. https://github.com/publiclab/plots2/blob/bbfd7d4431ea7fbf36ab020015af0699606b3847/app/views/comments/_form.html.erb
3. https://github.com/publiclab/plots2/blob/bbfd7d4431ea7fbf36ab020015af0699606b3847/app/assets/javascripts/comment.js
