### ISSUE TITLE
Change http:// to https:// in several places (Fix for #6391)

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#8587]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing! This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :nerd_face: A little background:

Basically we need to remove http:// and replace it with https:// in multiple files, so that the site can continue to load content as normal. See below and issue #6391 for more information.

> Chrome will soon start blocking any http content loaded from an https page - not just scripts and iframes, but images, etc.
> [https://www.bleepingcomputer.com/news/google/google-chrome-to-gradually-start-blocking-mixed-content-by-default/](https://www.bleepingcomputer.com/news/google/google-chrome-to-gradually-start-blocking-mixed-content-by-default/)

### ✒️ What to Change

There are a few places in the codebase where we can make this change. Please select **ONE** file to make a pull request (more info below), and leave the rest for other first-timers!

- [ ] **tools_places.html.erb**:
https://github.com/publiclab/plots2/blob/76f000c8dcc82576910590f9699c92256179c20e/app/views/notes/tools_places.html.erb#L9
- [ ] **db/seeds.rb**:
https://github.com/publiclab/plots2/blob/76f000c8dcc82576910590f9699c92256179c20e/db/seeds.rb#L75
- [x] ~~**notify_moderators_of_comment_spam.html.erb**~~: claimed, awaiting merge in #8593 

### What Do I Do If Everything's Been Taken?
You can search this repository for instances of "http" like so:
![Untitled 3](https://user-images.githubusercontent.com/4361605/96181359-b95ccb80-0ee8-11eb-811e-8be766753dd0.gif)

Leave a comment here if you find one!

### Completed - Please do not claim these! They have already been completed.
- [x] ~~**drupal_content_type_map.rb**: merged in #8666~~ 
- [x] ~~**notify_moderators_of_spam.html.erb**: merged in #8669~~
- [x] ~~**_history.html.erb**: merged in #8653~~

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Make a comment on this page, claiming one of the files above. If someone else has already claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file you've chosen by navigating to it. You can edit the line directly by clicking on the little pen icon.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by yashmohan100** [comment]
Hi @noi5e , Can i work on this issue ?

**Comment by yashmohan100** [comment]
I have taken the first option
- [ ] **drupal_content_type_map.rb**:
https://github.com/publiclab/plots2/blob/76f000c8dcc82576910590f9699c92256179c20e/app/models/drupal_content_type_map.rb#L32-L34

**Comment by noi5e** [comment]
@yashmohan100 Please go ahead!

**Comment by Kennygrace** [comment]
Hello @noi5e, Please I would like to take up the second option on this issue

**Comment by sagarpreet-chadha** [comment]
Sure @Kennygrace 😄

**Comment by amanda-ariyaratne** [comment]
@noi5e I would like to work on the third option

**Comment by amanda-ariyaratne** [comment]
Hello, I've made the required change on the file plots2/app/views/admin_mailer/notify_moderators_of_comment_spam.html.erb

When trying to open a pull request I get the warning Can't automatically merge. I am attachig a screenshot here. I did not make any other changes in the code.
![Screenshot](https://user-images.githubusercontent.com/28347418/96222670-516eb980-0faa-11eb-9e1e-2ead621f58fc.png)
![Screenshot 2](https://user-images.githubusercontent.com/28347418/96222841-985caf00-0faa-11eb-9497-28e026281d33.png)
![Screenshot 3](https://user-images.githubusercontent.com/28347418/96222878-a4e10780-0faa-11eb-8f54-f948cdc4fc25.png)

**Comment by MinervaLong** [comment]
Hello, @noi5e I would like to work on the fourth option, thank you.

**Comment by DhrutikPatel** [comment]
Hello, @noi5e I would like to do PR on fifth option

**Comment by MadhaviG97** [comment]
Hi, I would like to work on the sixth option

**Comment by alvesitalo** [comment]
Hi @noi5e , I would like to work on the seventh option

**Comment by cesswairimu** [comment]
Maybe we should separate each file changes to individual issues  for review and merging purposes(we have automatic closure of issue once a linked PR is merged) @noi5e would you like to separate these? please ping me if you need any help. Thanks a lot for opening this :100:

**Comment by noi5e** [comment]
@cesswairimu Okay, got it. I think I'll have some time later today or tomorrow to make separate issues.

**Comment by cesswairimu** [comment]
Thanks @noi5e

**Comment by ebarry** [comment]
Thank you @noi5e ! Excellent signposting for the community.

**Comment by tejaswini22199** [comment]
Hey @noi5e  is there any box that is not merged yet? or all the 6 files have been modified?

**Comment by cesswairimu** [comment]
Reopening

**Comment by mscreation28** [comment]
Hey @noi5e I am trying to to do my first pull request. Can you assign me this task if any left and tell me what to change in reopened issue?

**Comment by noi5e** [comment]
@cesswairimu Okay, I opened new FTO issues for 5 out of the 6 instances (in the 6th instance, the PR was already merged). Hope that helps the organization a little bit.

Any first-time contributor that's reading this and still looking for an FTO issue: I believe that there are **still** instances of http left in the codebase that need to be converted to https. Please read the initial notes I posted for this issue and look at the animated GIF on how to search the codebase for http. 

From there you can write your own FTO issue for the file... Or maybe someone who just made an FTO contribution and wants to make an issue can do it (after writing 6 FTO issues, I'm kinda looking forward to contributing to Public Lab in another way 😋)

**Comment by jwalit21** [comment]
hey @noi5e..

Till i've found these 2 new issues in files where we might have to change http to https based on how you have explained in GIF.
Those files are  **1. notes_controller_test.rb**  **2. critical_path_css.yml**

I'm a first-timer, and i want to contribute in this project.
so can you please confirm that the issues i founded i correct and valid or not? 

And if it is **valid** then can you please assign this issue to me by creating new FTO issue?

Thank you @noi5e

**Comment by noi5e** [comment]
@jwalit21 Awesome, that's great! I'll leave it to @jywarren and @cesswairimu to decide if they want the changes to be made in those files...

Also, I encourage you to make your own FTO issue. (I'm pretty new to this codebase and only just recently completed my own FTO issue). More info here: https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

**Comment by cesswairimu** [comment]
Great :tada: , thanks @noi5e  :tada:  @jwalit21 I will check if the hyperlinks can be changed on the tests and revert. Thanks

**Comment by jayaram2000** [comment]
Hey, I'm new to open source and would love to contribute. Are there any open issue?

**Comment by evansusu** [comment]
hi I'd like to make changes to db/seeds.rb:

**Comment by evansusu** [comment]
Hi which ones still need to replaced?

**Comment by cesswairimu** [comment]
Hi @evansusu, these all have been assigned to people. Thanks

**Comment by noi5e** [comment]
@evansusu @jayaram2000 Even though these six instances have already been claimed by other people, there are still other places which have http instead of https.

You can search for http in plots2 like so:

![](https://user-images.githubusercontent.com/4361605/96181359-b95ccb80-0ee8-11eb-811e-8be766753dd0.gif)

If you find a place that needs the change, leave a comment here and let us know! You can make a first-timers-only issue, and assign yourself to it :)

**Comment by YubaNeupane** [comment]
Can I fix this issue?

**Comment by jayaram2000** [comment]
@noi5e  Can I take up  ***openid_test.rb*** file?

**Comment by cesswairimu** [comment]
@jwalit21 sorry this skipped my mind. Replacing the test looks like it would be okay. Feel free to create an issue for that. Thanks

**Comment by symrin** [comment]
@noi5e Can I take the **user_tags.yml** file, and make the change there?

**Comment by cesswairimu** [comment]
Hi @symrin, you can take it up as a trial issue...not sure it will affect the tests. If you are up to so the changes and do the PR and see if the tests will be all good please go ahead. Thanks

**Comment by cesswairimu** [comment]
All the issues broken out from here have all been solved and merged :tada: :tada:... Thanks a lot everyone and many thanks to @noi5e  for opening this and helping all the new comers :raised_hands: :raised_hands:  

I have opened some more ftos for the remaining instances on app/views... and linking back to the main issue [here](https://github.com/publiclab/plots2/issues/6391) for further discussions . Thanks again all :heart:
