### ISSUE TITLE
Comment Editor Overhaul Project [Outreachy]

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#9069]
### **_(Last updated Saturday January 23rd)_**

Here's a planning issue that I made to cover my 13-week internship with Outreachy and Public Lab!

I will update this comment at least once a week to show my progress. I'm also compiling issues relevant to the Comment Editor in this already existing [Milestone](https://github.com/publiclab/plots2/milestone/28). 

## `Week Eight`
I'm starting to work on refactoring comment editor code:

### Open PRs (merge from top-to-bottom)
1. Add Unique IDs to Comment Forms ❗ **[open PR: #9062]** **(merge first!)**
  - [x] standardize `<form>` and `preview` IDs in reply and main comment forms
2. Integrate Edit Comment Form JS with editor.js ❗ **[open PR: #9067]**
  - [x] delete `<script>` in `_edit.html.erb` and point it toward `editor.js` instead
  - [x] standardize edit form's `textarea` and `preview` IDs for `editor.js`
  - [x] remove `setInit` call on `#edit-btn` click
  - [x] move `$E.initialize` to higher-level views
 
### Start Refactoring Comment Editor Code:
- object-oriented refactor of `editor.js`: 💬 **[issue #9004]**
- [ ] assign `$D.selected` using unique IDs, not `div.comment-form-wrapper`
  - [ ] remove `$D.selected` altogether?
  - [ ] possible to remove `$E.refresh` call in `$E.wrap`?
  - [ ] remove `handleClick()` function and call when opening reply forms.
- [ ] `$E.initialize({ default main editor form ID })`
- [ ] refactor save & recover methods
- [ ] remove functionality for DRAG onto edit form's `.dropzone` to upload image

## `Coming Up Soon`
- continue filling out comment system tests 🔍 **[issue #8810]**:
  - [ ] **priority:** rich-text changes on freshly posted comments
  - [ ] **priority:** image upload for freshly posted comments
  - [ ] editing existing comments
  - [ ] editing existing comment replies
  - [ ] editing freshly posted comment replies
  - [ ] preview buttons working correctly?
  - [ ] unit tests for new wiki, note, question: `$E.textarea` must initialize correctly
  - [ ] image progress bars show on `/wiki/new` and `/wiki/edit` routes
- responsive design: `choose one` upload in comment forms gets set to `display: none` on window resizing
  - this causes inconsistencies with image upload
- toggle preview in edit comments isn't selecting the whole form
- consider separating, or refactoring comment form code where it's reused for posting new pages (eg. `/wiki/new`)
  - at the very least, research `/wiki/new`'s `.dropzone` and how it's different from comments'
- find instances where we can use `addComment` as the commenting mechanism of choice:
  - https://github.com/publiclab/plots2/blob/484bf69ead7a1f69c9047a25b3f63b9d6f875728/app/assets/javascripts/comment.js#L62-L70
  - [jeffrey mentioned](https://github.com/publiclab/plots2/issues/8775#issuecomment-739518669) that using `addComment` more widely has benefits, including streamlining comment testing.

**Issues to Research More:**
Sourced from [this document](https://docs.google.com/document/d/1hOqa4tC0jqEuSaur1zKMtnxnknkARui3HTKqO3AUFMA/edit
) (scanning under **Comment Editor** and **Reply to Comment Editor**. If I'm not mistaken, most of these need their own dedicated issue page:
- add formatting toolbar (similar to question, research, and wiki editors)
- remove templates button.
- ensure grey "drag-and-drop to insert images" is everywhere (can't reproduce, would like some examples)
- issues with liking comments (See "Comment Likes Does Not Work #5113"). i understand the issue, basically I need to clarify what the expected behavior here is.

## `Late-Stage Internship Tasks (Last Two Weeks):`
- [ ] clean up system tests & fixtures
  - [ ] use `node.add_comment` where necessary to reduce redundant fixtures
  - [ ] refactor `drop_in_dropzone` helper method for efficiency
  - [ ] ensure that tests targeting reply forms are **not** using the 1st reply form
- [ ] style fixes for comments:
  - [ ] reactions, and superfluous grey bar: https://github.com/publiclab/plots2/issues/8775#issuecomment-762424107
  - [ ] responsive design is weird for editor toolbar - header button disappears entirely
  - [ ] reaction button is sliiightly too big
- [ ] write issues for wishlist/stretch goals:
  - [ ] close reply comment form upon submission
  - [ ] notification for submitting emoji reaction 
  - [ ] `h2` rich-text button provides drop-down options for `h1`, `h3`, `h4`, etc.
  - [ ] textarea should remain focused, and cursor should be present after clicking rich-text button
  - [ ] improve speed to post comment: https://github.com/publiclab/plots2/issues/8775#issuecomment-764164242
- [ ] write FTO issues
  - [ ] some comment forms POST to `URL?type=question`. we can remove the `type=question` parameter as it's no longer widely used: https://github.com/publiclab/plots2/pull/8801#issuecomment-740075410
  - [ ] rename `comment.add_comment` to `comment_from_email`
  - [ ] hide spam comment responses: #8854
- [ ] check-in with community about state of comment editor.
- [ ] consider whether reorganizing, consolidating comment Editor code, organization, or architecture would simplify reduce redundancy, or ease maintenance. (Perhaps spinning out into other library makes sense, eg: https://github.com/publiclab/inline-markdown-editor)

## `What I've Done`
**Completed Tests:**
- [x] **note:** comment with addComment(comment_text, URL), assert comment_text exists in DOM _(merged in #8809)_
- [x] **question:** comment with addComment(comment_text, URL), assert comment_text exists in DOM _(merged in #8801)_
- [x] **note:** respond to existing comment with addComment(comment_text, URL, parent_id) _(merged in #8844)_
- [x] **question:** respond to existing comment with addComment(comment_text, URL, parent_id) _(merged in #8845)_
- [x] **note:** comment, then respond to freshly posted comment _(merged in: #8860)_
- [x] **question:** comment, then respond to freshly posted comment  _(merged in #8851)_
- [x] consolidate and organize tests so we can run each type of test on each variant of the Comment Editor. _(merged in #8860)_
- [x] edit freshly posted comment
  - _(I decided not to write this test, deciding it would be redundant. There's an already existing test that does this.)_
  - _Follow my research into this topic [here](https://github.com/publiclab/plots2/issues/8810#issuecomment-747867020)_
- [x] user posts fresh page, then posts fresh comment  _(merged in #8879)_
- [x] open a mixture of _"Reply to comment"_ boxes, and post comments in each. _(merged in #8881)_
- [x] image DRAG & DROP into EDIT form isn't cross-wired with MAIN form  _(merged in #8897)_
- [x] IMMEDIATE image CLICK to upload in REPLY comment form works _(merged in #8987)_
- [x] IMMEDIATE image CLICK to upload in EDIT comment form works _(merged in #8987)_
- [x] CROSS-WIRING: DROP image onto MAIN, CLICK on EDIT form's `.dropzone`  _(merged in #8987)_
- [x] CROSS-WIRING: DROP image onto MAIN, CLICK on REPLY form's `.dropzone`  _(merged in #8987)_
- [x] IMMEDIATE rich-text input into MAIN works _(merged in #9011)_ 
- [x] CROSS-WIRING: open EDIT comment form, rich-text input into REPLY comment form _(merged in #9011)_
- [x] show progress bars for DRAG & DROP image upload in MAIN comment form _(merged in #9019)_
- [x] show progress bars for CLICK to upload in EDIT comment form  _(merged in #9019)_
- [x] reduce test coverage to save runtime: run comment tests for just comments on research notes (not wikis and questions) _(merged in #9045)_

**Completed Bug Fixes/Features:**
- [x] consolidate comment toolbar JS scripts; rename `dragdrop.js` to `editorToolbar.js` _(merged in #9044)_
- [x] rewrite script-loading of `comment.js` and `dragdrop.js` so they're not [loaded once per comment](https://github.com/publiclab/plots2/blob/86641a7bbd9b13d5872f236d6eb95c1e423ab4ac/app/views/comments/_form.html.erb#L106) _(merged in #9037)_
- [x] write `$E.setState()` method using ES6 default parameters _(merged in #9035)_
  - [x] set preview state inside of `$E.setState()` calls _(merged in #9035)_
- [x] show progress bars when clicking-to-upload images in edit comment form _(fixes #9018, merged in #9019)_
  - [x] assign unique IDs and common classes to progress bars
  - [x] style fixes for image upload progress bars, drag & drop hover, edit comment forms _(merged in #9019)_
- [x] add unique IDs and common classes for comment preview buttons _(merged in #9012)_
- [x] fix cross-wiring for rich-text (bold, italic) buttons _(fixes #8478, merged in #9011)_
  - [x] assign unique HTML IDs to rich-text toolbar buttons _(merged in #8995)_
  - [x] assign `$E.textarea` as `e.target` when clicking rich-text buttons. _(merged in #9011)_
- [x] assign unique HTML IDs to rich-text toolbar buttons _(merged in #8995)_
- [x] fix cross-wiring for **click** to image upload _(fixes #8926, merged in #8987)_
  - [x] rewrite `click` and `drop` event handlers to set `$D.selected` _(merged in #8987)_
- [x] fix cross-wiring for edit/main **drag-and-drop** image upload _(fixes #8670, merged in #8897)_
  - [x] assign unique IDs to comment textareas _(merged in #8897)_
  - [x] rewrite drop listener in dragdrop.js so that $E can be re-initialized for single & multi-form pages _(merged in #8897)_
  - [x] wrap `comments/_edit.html.erb` in `div.comment-form-wrapper`, reassign `$D.selected` _(merged in #8897)_
  - [x] rewrite `drop_in_dropzone` test helper to be reused for multiple drops _(merged in #8897)_
- [x] add unique HTML IDs to image upload elements _(merged in #8927)_
- [x] don't show emojis from banned users _(fixes #8618, merged in #8875)_

---
- [My Outreachy Internship Blog](https://noi5e.hashnode.dev/)
- [My original planning issue from Outreachy application](https://publiclab.org/notes/noi5e/10-30-2020/outreachy-proposal-overhaul-improve-and-harmonize-public-lab-s-comment-editor-s)

## `Project Description from Public Lab`
_We have a collection of improvements, bugfixes, and refinements to our aging Comment editor subcomponent on the PublicLab.org website. The comment editor is used in various “variants” with shared code, complicating debugging (i.e. fixing the bug in one place can introduce a bug in another). This is a great case for system tests, where we can ensure behaviors are preserved, and for writing these tests before making any major code changes - as well as for identifying bugs by writing tests to demonstrate them, followed by submitting a fix within the same pull request, which gets the test to pass -- Test Driven Development. We have prioritized a list of bugs and refinements we’d like to fix first, and have then outlined a set of changes that could make the code more compact, readable, and maintainable to reduce future workload._

**Comment by noi5e** [comment]
I copied the contents of my old planning issue over here... I thought it would be nice for the late-stage of the internship to have things be more readable here.

If you need to look at the old issue for any reason, it's here: #8775.

**Comment by jywarren** [comment]
TY for the ordered list of merges!!!!!
