### ISSUE TITLE
New Dashboard Transition Tasks

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9277]
Hello 👋🏾 

The new dashboard implementation is almost 100% complete https://github.com/publiclab/plots2/issues/8513 🎉  
There are a few tasks, listed below, that will need to be implemented and discussed as the new dashboard replaces the old dashboard. 

- [x]  Moving the old dashboard to `/v1/dashboard` once the new Dashboard has been approved (possible FTO issue) #8843
- [x]  Remove old Dashboard tests (possible FTO issue)#8842
- [x]  Rename/replace dashboard `v2` references with main dashboard `/dashboard `https://github.com/publiclab/plots2/issues/9278
- [ ]  Ways to integrate a bit more imagery on the new dashboard #8967

**Comment by YogeshSharma01** [comment]
@RuthNjeri Can I work on this?

**Comment by RuthNjeri** [comment]
Hi,  @YogeshSharma01  Thank you for reaching out. This issue is still pending, please have a look at our weekly check-in, where you can work on some issues posted that we need urgent help on https://github.com/publiclab/plots2/issues/9318

**Comment by jywarren** [comment]
I added `(actually instead moving the old dashboard to /v1/dashboard)` to the above just to be sure! Thanks!

**Comment by jywarren** [comment]
I believe that as of https://github.com/publiclab/plots2/pull/9642 we have no more tasks before transition can begin. Now we consult with @publiclab/community-reps on the timing of the changeover. Thanks, all!

**Comment by jywarren** [comment]
Solving this in #10036 - with the exception of the new imagery in #8967 which is coming soon!
