### ISSUE TITLE
[Phase 2] React Rewrite of Comment System

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#9365]
The first phase of the React rewrite of the Comment/Legacy System was merged in #9176. Yay! 🥳 

To anyone who wants to see the React system in production, visit any research note, and add the following parameter to the end of the URL:

`?react=true`

I'm going to do a lot of follow-up work (in multiple PRs) in the next two weeks to try to get it as close to the fully functioning system as possible.

Including:
- system tests comparing performance with the Rails system
- emoji reaction system
- comment preview
- moderated comments

### `To-Do List` _(last edited Tuesday March 23rd)_
- [ ] ❗ system tests showing that React can properly do CRUD with comments
- [ ] ❗ assign propTypes to nested elements
- [ ] ❗ implement useReducer hook
- [ ] ❗ guest browsing: show link to `/login` instead of the main comment form
- [ ] ❗ temporarily disable user submission & clicking for comment publishing, updating, and deleting; add loading spinners
- [ ] functional tests for the controller making React's initial props
- [ ] add prompt before deleting comment
- [ ] get ESLint for React & React Hooks working again, and working with codeclimate CI too
- [ ] move `get_initial_react_props` method from the controller to the `Comment` model
- [ ] make initial Component on `document.load` a spinner; AJAX request afterward for initial props

**Comment by noi5e** [comment]
I'm back!

Starting to add system tests ensure that basic functionality for React comments exists. See #9665, which tests posting comments, and comment replies.

An added benefit of system tests for React comments is that we can use test runtime as a rough measure of whether or not React comments are faster than the Rails comment system.

**React**:
<img width="381" alt="Screen Shot 2021-05-24 at 2 15 11 PM" src="https://user-images.githubusercontent.com/4361605/119410525-d71fb980-bc9d-11eb-8213-82015f576b70.png">

**Rails**:
<img width="379" alt="Screen Shot 2021-05-24 at 2 16 20 PM" src="https://user-images.githubusercontent.com/4361605/119410561-e6066c00-bc9d-11eb-8dc1-90764254671d.png">

A difference of .707 seconds, or 3% faster!

**Comment by jywarren** [comment]
This is awesome. Thanks @noi5e !!!

**Comment by noi5e** [comment]
Opened PR for editing comments.

Here's the new speed breakdown for all 3 new tests:

**React:**
<img width="375" alt="Screen Shot 2021-05-31 at 6 43 32 PM" src="https://user-images.githubusercontent.com/4361605/120255874-ce9d2500-c241-11eb-9e60-83fa9b74652a.png">

**Rails:**
<img width="382" alt="Screen Shot 2021-05-31 at 6 45 35 PM" src="https://user-images.githubusercontent.com/4361605/120255886-d361d900-c241-11eb-950a-11d130f771b6.png">

10% speed difference this time! I guess it can vary a lot depending on many factors, including whether or not processes are slowing down Terminal on my computer.
